<?php

/**
 * Implements hook_menu().
 */
function ext_admin_menu()
{
//  $items['admin/config/system/website'] = array(
//    'title' => 'Site configuration',
//    'description' => 'Настройки сайта и дополнительный функционал для админа',
//    'page callback' => 'drupal_get_form',
//    'page arguments' => array('ext_admin_settings_form'),
//    'access arguments' => array('access manager settings'),
//    'weight' => -100,
//  );
//  $items['admin/config/system/website/settings'] = array(
//    'title' => 'Site configuration',
//    'page callback' => 'drupal_get_form',
//    'page arguments' => array('ext_admin_settings_form'),
//    'access arguments' => array('access manager settings'),
//    'type' => MENU_DEFAULT_LOCAL_TASK,
//  );

  $items['admin/config/custom'] = array(
    'title' => 'Custom',
    'position' => 'right',
    'weight' => -100,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/custom/settings'] = array(
    'title' => 'Настройки',
    'weight' => 0,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ext_admin_settings_form'),
    'access arguments' => array('access manager settings'),
  );
  $items['admin/config/custom/migration'] = array(
    'title' => 'Обработка данных',
    'weight' => 1,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ext_admin_migration_form'),
    'access arguments' => array('access manager settings'),
  );

  return $items;
}


/**
 * Implements hook_cron_queue_info().
 */
function ext_admin_cron_queue_info()
{
  $queues['database_processing_queue'] = array(
    'worker callback' => 'ext_admin_database_process_record',
  );
  $queues['database_processing_queue_2'] = array(
    'worker callback' => 'ext_admin_database_process_record_2',
  );
  $queues['database_processing_queue_3'] = array(
    'worker callback' => 'ext_admin_database_process_record_3',
  );
  $queues['database_processing_queue_4'] = array(
    'worker callback' => 'ext_admin_database_process_record_4',
  );
  $queues['database_processing_queue_5'] = array(
    'worker callback' => 'ext_admin_database_process_record_5',
  );

  return $queues;
}

function ext_admin_settings_form($form, &$form_state)
{
  /** - Настройки содержимого ------------------------------------------------------------------------------------- */
  $form['import'] = array(
    '#type' => 'fieldset',
    '#title' => 'Настройки импорта',
    '#collapsible' => TRUE,
    '#collapsed' => false,
  );
  $form['import']['admin_import_enabled'] = [
    '#type' => 'checkbox',
    '#title' => 'включить импорт',
    '#default_value' => variable_get('admin_import_enabled', false),
  ];

  return system_settings_form($form);
}

function ext_admin_migration_form($form, &$form_state)
{
  $function = '';
  $function = 'ext_admin_queue_database_processing_4';

  $form['message'] = array(
    '#markup' => ($function ? '<p>Будет запущена функция ' . $function . '</p>' : '<p>Функция для запуска не задана</p>'),
  );
  $form['control'] = array(
    '#type' => 'checkbox',
    '#title' => 'контрольная галка',
    '#description' => 'установить перед запуском',
    '#default_value' => false,
  );
  $form['function'] = array(
    '#type' => 'hidden',
    '#value' => $function,
  );
  $form['run'] = [
    '#type' => 'submit',
    '#value' => 'Пуск!',
  ];

  return $form;
}
function ext_admin_migration_form_validate($form, &$form_state)
{
  if (!$form_state['values']['function']) {
    form_set_error('','Нужно задать функцию, которая будет запущена');
    return false;
  }
  if (!function_exists($form_state['values']['function'])) {
    form_set_error('', 'Заданная функция ' . $form_state['values']['function'] . ' не существует');
    return false;
  }
  if (!$form_state['values']['control']) {
    form_set_error('control', 'Нужно установить контроль');
    return false;
  }
}
function ext_admin_migration_form_submit($form, &$form_state)
{
  $function = $form_state['values']['function'];
  if ($function()) {
    drupal_set_message('Запуск выполнен успешно');
  } else {
    drupal_set_message('Неуспешный пуск', 'warning');
  }
}

function ext_admin_queue_database_processing_terms()
{
  // получить записи с незаполненным полем и поставить в очередь
  $dbr = db_select('taxonomy_term_data', 't');
  $dbr->condition('t.vid', taxonomy_vocabulary_machine_name_load('clients')->vid);
  $dbr->leftjoin('field_data_field_kccc_company', 'fa', 'fa.entity_id = t.tid');
  $dbr->isNull('fa.field_kccc_company_tid');
  $dbr->addField('t', 'tid');
  if ($terms = $dbr->execute()->fetchAllAssoc('tid')) {

    $queue = DrupalQueue::get('database_processing_queue');
    $queue->deleteQueue();

    foreach($terms as $term) {
      $queue->createItem($term->tid);
    }

    drupal_set_message('Записей, помещённых в очередь: ' . count($terms));
  }
}
function ext_admin_queue_database_processing()
{
  // получить записи с незаполненным полем и поставить в очередь
//  $dbr = db_select('eck_plan', 't');
//  $dbr->condition('t.vid', taxonomy_vocabulary_machine_name_load('nomenklatura_td')->vid);
//  $dbr->leftjoin('field_data_field_nom_artikul', 'fa', 'fa.entity_id = t.tid');
//  $dbr->isNull('fa.field_nom_artikul_value');
//  $dbr->addField('t', 'tid');
//  if ($terms = $dbr->execute()->fetchAllAssoc('tid')) {
//
//    $queue = DrupalQueue::get('database_processing_queue');
//    $queue->deleteQueue();
//
//    foreach($terms as $term) {
//      $queue->createItem($term->tid);
//    }
//  }
}

function ext_admin_database_process_record($term_id)
{
  $company = dash_term_get_by_1c_id('companies', DASH_INN_AH);
  $term_wr = entity_metadata_wrapper('taxonomy_term', $term_id);
  $term_wr->field_1c_id = $term_wr->field_client_id->value();
  $term_wr->field_kccc_company = $company->tid;
  $term_wr->save();
}

function ext_admin_queue_database_processing_2()
{
  // получить записи с незаполненным полем и поставить в очередь
  $q = db_select('eck_revenue', 'r');
  $q->fields('r', array('id'));

  if ($items = $q->execute()->fetchCol()) {
    $queue = DrupalQueue::get('database_processing_queue_2');
    $q->leftjoin('field_data_field_revenue_company', 'frc', 'frc.entity_id = r.id');
    $q->isNull('frc.field_revenue_company_value');

//    $queue->deleteQueue();

    foreach($items as $item) {
      $queue->createItem($item);
    }

    drupal_set_message('Записей, помещённых в очередь: ' . count($items));
    return true;
  }
}

function ext_admin_database_process_record_2($record_id)
{
  // обработать запись базы данных
//  $arr = [];
//  $revenue_wr = entity_metadata_wrapper('revenue', $record_id);
//  $arr['date'] = $revenue_wr->field_date->value();
//  $arr['type'] = $revenue_wr->field_revenue_type->value();
//  $arr['amount'] = $revenue_wr->field_amount->value();
//  $arr['company'] = $revenue_wr->field_company->value();
//  $arr['created'] = $revenue_wr->created->value();

//    $revenue = entity_create('revenue', [
//      'type' => 'revenue',
//      'created' => $arr['created'],
//    ]);
//    entity_save('revenue', $revenue);
    entity_delete('revenue', $record_id);

//    $new_wr = entity_metadata_wrapper('revenue', $revenue);
//    $new_wr->field_revenue_date = $arr['date'];
//    $new_wr->field_revenue_type = $arr['type'];
//    $new_wr->field_revenue_amount = $arr['amount'];
//    $new_wr->field_revenue_company = $arr['company'];
//    $new_wr->save();

  watchdog('message', 'Обработана запись с id: ' . $record_id);
}

function ext_admin_queue_database_processing_3()
{
  // получить записи с незаполненным полем и поставить в очередь
  $q = db_select('eck_remains', 'r');
  $q->condition('r.type', 'remains');
//  $q->leftjoin('field_data_field_rm_date', 'fd', 'fd.entity_id = r.id');
//  $q->isNull('fd.field_rm_date_value');
  $q->fields('r', array('id'));
//  $q->range(0, 50000);

  if ($items = $q->execute()->fetchCol()) {
    $queue = DrupalQueue::get('database_processing_queue_3');
//    $queue->deleteQueue();

    foreach($items as $item) {
      $queue->createItem($item);
    }

    drupal_set_message('Записей, помещённых в очередь: ' . count($items));
    return true;
  }
}

function ext_admin_database_process_record_3($record_id)
{
  // обработать запись базы данных
  $arr = [];
  $remains_wr = entity_metadata_wrapper('remains', $record_id);
  $arr['nom'] = $remains_wr->field_nomenklatura_td->value();
  $arr['wh'] = $remains_wr->field_warehouse_td->value();
  $arr['qty'] = $remains_wr->field_quantity_td->value();
  $arr['price'] = $remains_wr->field_price->value();
  $arr['date'] = $remains_wr->field_date->value();
  $arr['date_exp'] = $remains_wr->field_date_expiration->value();

    $remains = entity_create('remains', [
      'type' => 'remains',
    ]);
    entity_save('remains', $remains);
    entity_delete('remains', $record_id);

    $new_wr = entity_metadata_wrapper('remains', $remains);
    $new_wr->field_rm_nomenklatura = $arr['nom'];
    $new_wr->field_rm_warehouse = $arr['wh'];
    $new_wr->field_rm_quantity = $arr['qty'];
    $new_wr->field_rm_price = $arr['price'];
    $new_wr->field_rm_date = $arr['date'];
    $new_wr->field_rm_date_exp = $arr['date_exp'];
    $new_wr->save();

  watchdog('message', 'Обработана запись с id: ' . $record_id);
}


function ext_admin_queue_database_processing_4()
{
  // получить записи с незаполненным полем и поставить в очередь
  $q = db_select('eck_plan', 'p');
  $q->condition('p.type', 'plan_ship');
  $q->fields('p', array('id'));

  if ($items = $q->execute()->fetchCol()) {
    $queue = DrupalQueue::get('database_processing_queue_4');
    $queue->deleteQueue();

    foreach($items as $item) {
      $queue->createItem($item);
    }

    drupal_set_message('Записей, помещённых в очередь: ' . count($items) . ' (' . $items[0] . ' - ' . array_pop($items) . ')');
    return true;
  }
}

function ext_admin_database_process_record_4($record_id)
{
  // обработать запись базы данных
  $arr = [];
  $plan_wr = entity_metadata_wrapper('plan', $record_id);
  if ($plan_wr->value()) {
    $arr['type'] = $plan_wr->field_record_type_td->value();
    $arr['client'] = $plan_wr->field_client->value();
    $arr['qty'] = $plan_wr->field_quantity_td->value();
    $arr['date'] = $plan_wr->field_date->value();
    $arr['amount'] = $plan_wr->field_amount->value();
    $arr['net_cost'] = $plan_wr->field_net_cost->value();
    $arr['manual'] = $plan_wr->field_is_manual->value();
    $arr['created'] = $plan_wr->created->value();
    $arr['nom'] = $plan_wr->field_nomenklatura->value();

    if ($arr['type'] && $arr['date']) {
      $ship = entity_create('ship', [
        'type' => 'ship',
        'created' => $arr['created'],
      ]);
      entity_save('ship', $ship);

      $new_wr = entity_metadata_wrapper('ship', $ship);
      $new_wr->field_s_company = 196472; // тд
      $new_wr->field_s_date = $arr['date'];
      $new_wr->field_s_type = $arr['type'] + 1;
      $new_wr->field_s_amount = $arr['amount'];
      $new_wr->field_s_quantity = $arr['qty'];
      $new_wr->field_s_net_cost = $arr['net_cost'];
      $new_wr->field_s_is_manual = $arr['manual'] ?? 0;
      $new_wr->field_s_nomenklatura = $arr['nom'];
      $new_wr->field_s_client = $arr['client'];
      $new_wr->save();
    }
  }

  entity_delete('plan', $record_id);

  watchdog('message', 'Обработана запись с id: ' . $record_id);
}

function ext_admin_queue_database_processing_5()
{
  $dbr = db_select('taxonomy_term_data', 't');
  $dbr->condition('t.vid', taxonomy_vocabulary_machine_name_load('nomenklatura_td')->vid);
  $dbr->addField('t', 'tid');
  if ($tids = $dbr->execute()->fetchCol()) {

    $queue = DrupalQueue::get('database_processing_queue_5');
    $queue->deleteQueue();

    foreach($tids as $tid) {
      $queue->createItem($tid);
    }

    drupal_set_message('Записей, помещённых в очередь: ' . count($tids));
  }
}

function ext_admin_database_process_record_5($record_id)
{
  $arr = [];
  $term_wr = entity_metadata_wrapper('taxonomy_term', $record_id);
  $arr['name'] = $term_wr->label();
  $arr['id1c'] = $term_wr->field_1c_id->value();
  $arr['art'] = $term_wr->field_nom_artikul->value();
  $arr['unit'] = $term_wr->field_nom_unit->value();
  $arr['nds'] = $term_wr->field_nom_nds->value();
  $arr['status'] = $term_wr->field_status->value();

  $vid = taxonomy_vocabulary_machine_name_load('nomenklatura')->vid;
  $new_term = (object)array(
    'vid' => $vid,
    'name' => $arr['name'],
    'field_1c_id' => ['und' => [0 => ['value' => $arr['id1c']]]],
    'field_kccc_company' => ['und' => [0 => ['tid' => 196472]]], // тд
  );
  taxonomy_term_save($new_term);

  $new_wr = entity_metadata_wrapper('taxonomy_term', $new_term);
  $new_wr->field_status = $arr['status'];
  $new_wr->field_nom_artikul = $arr['art'];
  $new_wr->field_nom_unit = $arr['unit'];
  $new_wr->field_nom_nds = $arr['nds'];
  $new_wr->save();

  $q = db_select('eck_plan', 'p');
  $q->condition('p.type', 'plan_ship');
  $q->innerjoin('field_data_field_nomenklatura_td', 'fc', 'fc.entity_id = p.id');
  $q->condition('fc.field_nomenklatura_td_tid', $record_id);
  $q->fields('p', array('id'));
  if ($items = $q->execute()->fetchCol()) {
    foreach ($items as $item) {
      $wr = entity_metadata_wrapper('plan', $item);
      $wr->field_nomenklatura = $new_term->tid;
      $wr->save();
    }
  }

  $q = db_select('eck_analog_price', 'p');
  $q->innerjoin('field_data_field_ap_nom_td', 'fc', 'fc.entity_id = p.id');
  $q->condition('fc.field_ap_nom_td_tid', $record_id);
  $q->fields('p', array('id'));
  if ($items = $q->execute()->fetchCol()) {
    foreach ($items as $item) {
      $wr = entity_metadata_wrapper('analog_price', $item);
      $wr->field_ap_nomenklatura = $new_term->tid;
      $wr->save();
    }
  }

  $q = db_select('eck_registration', 'r');
  $q->innerjoin('field_data_field_nomenklaturas_td', 'fc', 'fc.entity_id = r.id');
  $q->condition('fc.field_nomenklaturas_td_tid', $record_id);
  $q->fields('r', array('id'));
  if ($items = $q->execute()->fetchCol()) {
    foreach ($items as $item) {
      $wr = entity_metadata_wrapper('registration', $item);
      $wr->field_r_nomenklaturas[] = $new_term->tid;
      $wr->save();
    }
  }

  watchdog('message', 'Обработана запись с id: ' . $record_id);
}

