<?php

/**
 * Implements hook_menu().
 */
function ext_admin_menu()
{
//  $items['admin/config/system/website'] = array(
//    'title' => 'Site configuration',
//    'description' => 'Настройки сайта и дополнительный функционал для админа',
//    'page callback' => 'drupal_get_form',
//    'page arguments' => array('ext_admin_settings_form'),
//    'access arguments' => array('access manager settings'),
//    'weight' => -100,
//  );
//  $items['admin/config/system/website/settings'] = array(
//    'title' => 'Site configuration',
//    'page callback' => 'drupal_get_form',
//    'page arguments' => array('ext_admin_settings_form'),
//    'access arguments' => array('access manager settings'),
//    'type' => MENU_DEFAULT_LOCAL_TASK,
//  );

  $items['admin/config/custom'] = array(
    'title' => 'Custom',
    'position' => 'right',
    'weight' => -100,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/custom/settings'] = array(
    'title' => 'Настройки',
    'weight' => 0,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ext_admin_settings_form'),
    'access arguments' => array('access manager settings'),
  );
  $items['admin/config/custom/migration'] = array(
    'title' => 'Обработка данных',
    'weight' => 1,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ext_admin_migration_form'),
    'access arguments' => array('access manager settings'),
  );

  return $items;
}


/**
 * Implements hook_cron_queue_info().
 */
function ext_admin_cron_queue_info()
{
  $queues['database_processing_queue'] = array(
    'worker callback' => 'ext_admin_database_process_record',
  );
  $queues['database_processing_queue_2'] = array(
    'worker callback' => 'ext_admin_database_process_record_2',
  );

  return $queues;
}

function ext_admin_settings_form($form, &$form_state)
{
  /** - Настройки содержимого ------------------------------------------------------------------------------------- */
  $form['import'] = array(
    '#type' => 'fieldset',
    '#title' => 'Настройки импорта',
    '#collapsible' => TRUE,
    '#collapsed' => false,
  );
  $form['import']['admin_import_enabled'] = [
    '#type' => 'checkbox',
    '#title' => 'включить импорт',
    '#default_value' => variable_get('admin_import_enabled', false),
  ];

  return system_settings_form($form);
}

function ext_admin_migration_form($form, &$form_state)
{
  $function = '';
  $function = 'ext_admin_queue_database_processing_2';

  $form['message'] = array(
    '#markup' => ($function ? '<p>Будет запущена функция ' . $function . '</p>' : '<p>Функция для запуска не задана</p>'),
  );
  $form['control'] = array(
    '#type' => 'checkbox',
    '#title' => 'контрольная галка',
    '#description' => 'установить перед запуском',
    '#default_value' => false,
  );
  $form['function'] = array(
    '#type' => 'hidden',
    '#value' => $function,
  );
  $form['run'] = [
    '#type' => 'submit',
    '#value' => 'Пуск!',
  ];

  return $form;
}
function ext_admin_migration_form_validate($form, &$form_state)
{
  if (!$form_state['values']['function']) {
    form_set_error('','Нужно задать функцию, которая будет запущена');
    return false;
  }
  if (!function_exists($form_state['values']['function'])) {
    form_set_error('', 'Заданная функция ' . $form_state['values']['function'] . ' не существует');
    return false;
  }
  if (!$form_state['values']['control']) {
    form_set_error('control', 'Нужно установить контроль');
    return false;
  }
}
function ext_admin_migration_form_submit($form, &$form_state)
{
  $function = $form_state['values']['function'];
  if ($function()) {
    drupal_set_message('Запуск выполнен успешно');
  } else {
    drupal_set_message('Неуспешный пуск', 'warning');
  }
}

function ext_admin_queue_database_processing_terms()
{
  // получить записи с незаполненным полем и поставить в очередь
  $dbr = db_select('taxonomy_term_data', 't');
  $dbr->condition('t.vid', taxonomy_vocabulary_machine_name_load('clients')->vid);
  $dbr->leftjoin('field_data_field_kccc_company', 'fa', 'fa.entity_id = t.tid');
  $dbr->isNull('fa.field_kccc_company_tid');
  $dbr->addField('t', 'tid');
  if ($terms = $dbr->execute()->fetchAllAssoc('tid')) {

    $queue = DrupalQueue::get('database_processing_queue');
    $queue->deleteQueue();

    foreach($terms as $term) {
      $queue->createItem($term->tid);
    }

    drupal_set_message('Записей, помещённых в очередь: ' . count($terms));
  }
}
function ext_admin_queue_database_processing()
{
  // получить записи с незаполненным полем и поставить в очередь
//  $dbr = db_select('eck_plan', 't');
//  $dbr->condition('t.vid', taxonomy_vocabulary_machine_name_load('nomenklatura_td')->vid);
//  $dbr->leftjoin('field_data_field_nom_artikul', 'fa', 'fa.entity_id = t.tid');
//  $dbr->isNull('fa.field_nom_artikul_value');
//  $dbr->addField('t', 'tid');
//  if ($terms = $dbr->execute()->fetchAllAssoc('tid')) {
//
//    $queue = DrupalQueue::get('database_processing_queue');
//    $queue->deleteQueue();
//
//    foreach($terms as $term) {
//      $queue->createItem($term->tid);
//    }
//  }
}

function ext_admin_database_process_record($term_id)
{
  $company = dash_term_get_by_1c_id('companies', DASH_INN_AH);
  $term_wr = entity_metadata_wrapper('taxonomy_term', $term_id);
  $term_wr->field_1c_id = $term_wr->field_client_id->value();
  $term_wr->field_kccc_company = $company->tid;
  $term_wr->save();
}

function ext_admin_queue_database_processing_2()
{
  // получить записи с незаполненным полем и поставить в очередь
  $q = db_select('eck_revenue', 'r');
  $q->fields('r', array('id'));

  if ($items = $q->execute()->fetchCol()) {
    $queue = DrupalQueue::get('database_processing_queue_2');
    $queue->deleteQueue();

    foreach($items as $item) {
      $queue->createItem($item);
    }

    drupal_set_message('Записей, помещённых в очередь: ' . count($items));
    return true;
  }
}

function ext_admin_database_process_record_2($record_id)
{
  // обработать запись базы данных
  $arr = [];
  $revenue_wr = entity_metadata_wrapper('revenue', $record_id);
  $arr['date'] = $revenue_wr->field_date->value();
  $arr['type'] = $revenue_wr->field_revenue_type->value();
  $arr['amount'] = $revenue_wr->field_amount->value();
  $arr['company'] = $revenue_wr->field_company->value();
  $arr['created'] = $revenue_wr->created->value();

  if ($arr['date'] && $arr['type'] && $arr['amount'] && $arr['company']) {
    $revenue = entity_create('revenue', [
      'type' => 'revenue',
      'created' => $arr['created'],
    ]);
    entity_save('revenue', $revenue);
    entity_delete('revenue', $record_id);

    $new_wr = entity_metadata_wrapper('revenue', $revenue);
    $new_wr->field_revenue_date = $arr['date'];
    $new_wr->field_revenue_type = $arr['type'];
    $new_wr->field_revenue_amount = $arr['amount'];
    $new_wr->field_revenue_company = $arr['company'];
    $new_wr->save();
  }

  watchdog('message', 'Обработана запись с id: ' . $record_id);
}

