<?php

define ('DASH_REV_DIVIDER', 1000000);       // делитель для единиц выручки
define ('DASH_REV_SUFFIX', 'млн руб.');     // суффикс (ед. изм.) для отгрузки
define ('DASH_PROD_DIVIDER', 1000);         // делитель для единиц выручки
define ('DASH_PROD_SUFFIX', 'тыс. ед.');    // суффикс (ед. изм.) для производства

define ('DASH_TYPE_PLAN_DEPR', 0);               // тип План
define ('DASH_TYPE_FACT_DEPR', 1);               // тип Факт
define ('DASH_TYPE_DEAL_DEPR', 2);               // тип Неоплаченный контракт

define ('DASH_COLOR_BLUE', '#2B94C9');
define ('DASH_COLOR_LIGHT_BLUE', '#89BDDF');
define ('DASH_COLOR_AQUA', '#2DAD9E');
define ('DASH_COLOR_GREEN', '#47AD9E');
define ('DASH_COLOR_GLOW_GREEN', '#A6B727');
define ('DASH_COLOR_LIGHT_GREEN', '#a6c96a');
define ('DASH_COLOR_RED', '#DF5327');
define ('DASH_COLOR_DARK_RED', '#c42525');
define ('DASH_COLOR_ORANGE', '#F69200');
define ('DASH_COLOR_LIGHT_ORANGE', '#FFC000');
define ('DASH_COLOR_PURPLE', '#CD5B8F');

define ('DASH_COLOR_SET_1', [DASH_COLOR_RED, DASH_COLOR_DARK_RED, DASH_COLOR_ORANGE, DASH_COLOR_LIGHT_ORANGE, DASH_COLOR_PURPLE]);
define ('DASH_COLOR_SET_2', [DASH_COLOR_BLUE, DASH_COLOR_LIGHT_BLUE, DASH_COLOR_AQUA, DASH_COLOR_GLOW_GREEN, DASH_COLOR_LIGHT_GREEN]);

define ('DASH_HISTORY_LENGTH', 5);            // максимальное количество лет истории
define ('DASH_HISTORY_START_YEAR_TD', 2020);  // начало истории сезонов ТД, год
define ('DASH_PERIOD_START_MONTH_TD', 10);    // начало сезона, месяц

define ('DASH_INN_AH', '4312128282');
define ('DASH_INN_TD', '4312138026');
define ('DASH_INN_ST', '4312136043');
const DASH_TD_NOM_ID_LIST_TO_EXCLUDE = [      // ТД, часть номенклатуры не нужно отражать в отчётах
  11743,                                          // 2 Этилгексиловый эфир 2,4-Д кислоты(ТД КЧХК)
  193930,                                         // 2,4-Д 2-этилгексиловый эфир техн. Китай (ТД КЧХК)
  194629,                                         // 2,4-D-кислота
  194367,194370,194371,194366,11745,11747,11746,  // этикетки
];
 const DASH_TYPE_PLAN = 1;                      // тип План
 const DASH_TYPE_FACT = 2;                      // тип Факт
 const DASH_TYPE_DEAL = 3;                      // тип Неоплаченный контракт

// вид Задолженности для таблицы Кредиты и задолженности
const DASH_DEBT_KIND_DEBITOR = 1;              // Дебиторская задолженность
const DASH_DEBT_KIND_CREDITOR = 2;             // Кредиторская задолженность
const DASH_DEBT_KIND_CREDIT = 3;               // внешние Кредиты
const DASH_DEBT_KIND_LOAN = 4;                 // внутренние займы

// Агрохимикат
define ('DASH_HISTORY_START_YEAR_AH', 2020);  // год начала статистики
define ('DASH_PERIOD_START_MONTH_AH', 1);     // месяц, с которого начинается период отчётности

date_default_timezone_set('UTC');

/**
 * Implementation of hook_menu().
 */
function dash_menu()
{
  $items['td'] = array(
    'title' => 'Торговый Дом',
    'menu_name' => 'main-menu',
    'page callback' => 'dash_frontpage',
    'expanded' => true,
    'access callback' => 'ext_user_has_roles',
    'access arguments' => [[ADMIN_RID, TRADE_HOUSE_USER_RID, DEP_2V2G_USER_RID, DEP_2A_USER_RID, DEP_4_USER_RID, DEP_7_USER_RID]],
  );

  $items['ajax-load'] = array(
    'page callback' => 'dash_ajax_load',
    'access callback' => 'ext_user_has_roles',  // todo доступ нужно проверять на уровне функции, иначе роли из списка могут получить данные друг друга
    'access arguments' => [[ADMIN_RID, TRADE_HOUSE_USER_RID, DEP_2V2G_USER_RID]],
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function dash_frontpage()
{
  // Используется при клике по корневому Торговый Дом в меню.
  // Так как главная у всех разная за счёт модуля Home Links,
  // отправляем на неё.
  drupal_goto('<front>');
}

function dash_chart_definition_alter(&$element, $chart)
{
  if (isset($element["options"]["series"])) {
    foreach ($element["options"]["series"] as &$el) {
      $el["_format"]["format"] = '#,###';
    }
  }
  if (isset($element["options"]["vAxes"][0])) {
    $element["options"]["vAxes"][0]["format"] = 'decimal';
  }
}

/**
* ----- универсальные для AH и TD графики ------------------------------------------------------------------------------
*/

/**
 * Сравнение выручки период к периоду
 * Внутри года суммируются данные за заданный период включительно
 * @param $time_from -начало периода, обязательно текущего
 * @param $time_to - конец периода, обязательно текущего
 */
function dash_column_revenue_period_to_period($company, $time_from, $time_to, $revenue_type = null)
{
  $data = [];

  // собрать данные периодов с DASH_YEAR_HISTORY_START года
  $years_shift = date('Y', $time_from) - ($company  == 'td' ? DASH_HISTORY_START_YEAR_TD : DASH_HISTORY_START_YEAR_AH);
  $years_shift = abs($years_shift)+1 > DASH_HISTORY_LENGTH ? DASH_HISTORY_LENGTH : $years_shift;
  do {
    $time_start = gmmktime(0, 0, 0,  date('n', $time_from)-12*$years_shift, date('j', $time_from), date('Y', $time_from));
    $time_end = gmmktime(0, 0, 0,  date('n', $time_to)-12*$years_shift, date('j', $time_to), date('Y', $time_to));

    $dbr = db_select('eck_revenue', 'r');
    $dbr->innerJoin('field_data_field_revenue_amount', 'fra', 'fra.entity_id = r.id');
    $dbr->condition('fra.bundle', 'revenue');
    $dbr->innerJoin('field_data_field_revenue_company', 'fc', 'fc.entity_id = r.id');
    $dbr->condition('fc.field_revenue_company_value', $company);
    $dbr->innerJoin('field_data_field_revenue_date', 'frd', 'frd.entity_id = r.id');
    $dbr->condition('frd.bundle', 'revenue');
    $dbr->condition('frd.field_revenue_date_value', $time_start, '>=');
    $dbr->condition('frd.field_revenue_date_value', $time_end, '<');
    $dbr->addExpression('SUM(fra.field_revenue_amount_value)', 'amount');
    $dbr->innerJoin('field_data_field_revenue_type', 'frt', 'frt.entity_id = r.id');
    $dbr->condition('frt.field_revenue_type_value', 'Прочая реализация', '!=');
    if ($revenue_type) {
//      $dbr->innerJoin('field_data_field_revenue_type', 'frt', 'frt.entity_id = r.id');
      $dbr->condition('frt.field_revenue_type_value', $revenue_type, 'IN');
    }
    $data[date('Y', $time_start)] = [
      'time_start' => $time_start,
      'time_end' => $time_end,
      'amount' => $dbr->execute()->fetchField() / DASH_REV_DIVIDER
    ];

    $years_shift--;
  } while ($years_shift >= 0);

  if ($revenue_type) {
    $title = 'Отгрузка по категории "' . $revenue_type[0] . '" (' . DASH_REV_SUFFIX . ')';
    $colors = [DASH_COLOR_RED, DASH_COLOR_PURPLE, DASH_COLOR_ORANGE, DASH_COLOR_DARK_RED, DASH_COLOR_AQUA, DASH_COLOR_GLOW_GREEN,  DASH_COLOR_BLUE];
  } else {
    $title = 'Суммарная отгрузка по данным бухгалтерии (' . DASH_REV_SUFFIX . ')';
    $colors = [];
  }

  $chart = array(
    '#type' => 'chart',
    '#chart_type' => 'column',
    '#title' => $title,
    '#height' => '350',
    '#data_labels' => TRUE,
    '#legend_position' => 'bottom',
    'yaxis' => [
      '#type' => 'chart_yaxis',
      '#min' => 0,
      '#raw_options' => ['textStyle' => ['fontName' => '<global-font-name>']],
    ],
    '#raw_options' => [
      'titleTextStyle' => ['bold' => 'true', 'fontName' => '<global-font-name>', 'fontSize' => '16'],
      'chartArea' => [
        'width' => '85%',
        'height' => '70%',
        'left' => 50,
      ],
    ],
  );

  if ($colors) $chart += ['#colors' => $colors];

  $year_prev = $delta = null;
  foreach ($data as $year => $item) {
    $chart[$year] = [
      '#type' => 'chart_data',
      '#title' => (string)(date('Y', $time_from) == date('Y', $time_to-1) ? $year : date('Y', $item['time_start']) . '-' . date('y', $item['time_end'])),
      '#data' => [$item['amount']],
    ];
    if ($year_prev && $data[$year_prev]) {
      $delta = ($item['amount'] > $data[$year_prev]['amount'] ? '+' : '') . number_format(($item['amount']/$data[$year_prev]['amount']*100)-100, 0, null, ' ') . '%';
    }
    $chart[$year][0] = [
      '#type' => 'chart_data_item',
      '#raw_options' => [
        'annotation' => number_format($item['amount'], 0, '', ' ') . ($delta ? ' (' . $delta . ')' : ''),
      ],
    ];
    $year_prev = $year;
  }

  return $chart;
}

function dash_pie_revenue_year($company, $time_from, $time_to)
{
  $dbr = db_select('eck_revenue', 'r');
  $dbr->innerJoin('field_data_field_revenue_company', 'fc', 'fc.entity_id = r.id');
  $dbr->condition('fc.field_revenue_company_value', $company);
  $dbr->innerJoin('field_data_field_revenue_type', 'frt', 'frt.entity_id = r.id');
  $dbr->addField('frt', 'field_revenue_type_value', 'type');
  $dbr->innerJoin('field_data_field_revenue_amount', 'fra', 'fra.entity_id = r.id');
  $dbr->condition('fra.bundle', 'revenue');
  $dbr->groupBy('frt.field_revenue_type_value');
  $dbr->innerJoin('field_data_field_revenue_date', 'frd', 'frd.entity_id = r.id');
  $dbr->condition('frd.bundle', 'revenue');
  $dbr->condition('frd.field_revenue_date_value', $time_from, '>=');
  $dbr->condition('frd.field_revenue_date_value', $time_to, '<');
  $dbr->addExpression('SUM(fra.field_revenue_amount_value)', 'amount');
  $results = $dbr->execute()->fetchAll();

  $total = 0;
  $rev_by_types = [];
  $types_to_unite = dash_types_to_merge_get();
  foreach($results as $item) {
    $total += $item->amount;
    $type = $types_to_unite[$item->type] ?? $item->type;
    if (!isset($rev_by_types[$type])) $rev_by_types[$type] = 0;
    $rev_by_types[$type] += $item->amount;
  }
  $total = $total/DASH_REV_DIVIDER;

  $types = [];
  $types_data = [];
  $other = 0;
  foreach($rev_by_types as $type => $amount) {
    // выводим значения больше 4% от общей суммы
    $amount = $amount/DASH_REV_DIVIDER;
    if ($amount/$total*100 > 4 || $type == 'Услуги хранения') {
      $types[$amount] = $type;
      $types_data[$amount] = $amount;
    } else {
      $other += $amount;
    }
  }
  if ($other) {
    $types[$other] = 'Прочее';
    $types_data[$other] = $other;
  }

  krsort($types);
  krsort($types_data);

  $period = '';
  if (date('Y', $time_to) != date('Y')) {
    $period = (date('Y', $time_from) == date('Y', $time_to - 1) ? date('Y', $time_from) : date('Y', $time_from) . '-' . date('y', $time_to)) . ' года ';
  }

  $chart = array(
    '#type' => 'chart',
    '#title' => 'Структура отгрузки за период ' . $period . 'по данным бухгалтерии (' . DASH_REV_SUFFIX . ')',
//    '#title_position' => 'center',
    '#chart_type' => 'pie',
    '#legend_position' => 'right',
    '#legend_title_font_size' => '10px',
    '#data_labels' => TRUE,
    '#tooltips' => TRUE,
    '#height' => '350',
    '#raw_options' => [
      'titleTextStyle' => ['bold' => 'true', 'fontName' => '<global-font-name>', 'fontSize' => '16'],
      'legend' => ['textStyle' => ['fontSize' => '14', 'fontName' => '<global-font-name>']],
      'chartArea' => ['width' => '85%'],
    ],
  );
  $chart['pie_data'] = array(
    '#type' => 'chart_data',
    '#title' => 'Продукция',
    '#labels' => array_values($types),
    '#data' => array_values($types_data),
  );

  return $chart;
}

function dash_column_revenue_by_types($company, $time_from, $time_to)
{
  $types_to_unite = dash_types_to_merge_get();

  // получаем возможные типы продукции
  $dbr = db_select('eck_revenue', 'r');
  $dbr->innerJoin('field_data_field_revenue_type', 'frt', 'frt.entity_id = r.id');
  $dbr->addField('frt', 'field_revenue_type_value');
  $dbr->innerJoin('field_data_field_revenue_company', 'fc', 'fc.entity_id = r.id');
  $dbr->condition('fc.field_revenue_company_value', $company);
  $dbr->innerJoin('field_data_field_revenue_date', 'frd', 'frd.entity_id = r.id');
  $dbr->condition('frd.bundle', 'revenue');
  $dbr->distinct();
  $types = $dbr->execute()->fetchCol();

  // собираем по типам за все сезоны
  $rev_by_types = [];
  foreach($types as $type) {
    // собрать данные периодов с DASH_YEAR_HISTORY_START года (именно этот график для ТД берём с 2021, так как в 1с не получается разделить продукцию 2020 года)
    $amounts = [];
    $years_shift = date('Y', $time_from) - ($company == 'td' ? 2021 : DASH_HISTORY_START_YEAR_AH);
    $years_shift = abs($years_shift)+1 > DASH_HISTORY_LENGTH ? DASH_HISTORY_LENGTH : $years_shift;
    do {
      $time_start = gmmktime(0, 0, 0,  date('n', $time_from)-12*$years_shift, date('j', $time_from), date('Y', $time_from));
      $time_end = gmmktime(0, 0, 0,  date('n', $time_to)-12*$years_shift, date('j', $time_to), date('Y', $time_to));

      $dbr = db_select('eck_revenue', 'r');
      $dbr->innerJoin('field_data_field_revenue_type', 'frt', 'frt.entity_id = r.id');
      $dbr->condition('frt.field_revenue_type_value', $type);
      $dbr->innerJoin('field_data_field_revenue_company', 'fc', 'fc.entity_id = r.id');
      $dbr->condition('fc.field_revenue_company_value', $company);
      $dbr->innerJoin('field_data_field_revenue_amount', 'fra', 'fra.entity_id = r.id');
      $dbr->condition('fra.bundle', 'revenue');
      $dbr->innerJoin('field_data_field_revenue_date', 'frd', 'frd.entity_id = r.id');
      $dbr->condition('frd.bundle', 'revenue');
      $dbr->condition('frd.field_revenue_date_value', $time_start, '>=');
      $dbr->condition('frd.field_revenue_date_value', $time_end, '<');
      $dbr->addExpression('SUM(fra.field_revenue_amount_value)', 'amount');
      $amounts[date('Y', $time_start)] = $dbr->execute()->fetchField()/DASH_REV_DIVIDER;

      $years_shift--;
    } while ($years_shift >= 0);

    // если какие-то группы нужно объединить, определяем целевой тип
    $type = isset($types_to_unite[$type]) ? $types_to_unite[$type] : $type;

    foreach($amounts as $year => $amount) {
      if (!isset($rev_by_types[$type])) $rev_by_types[$type] = [];
      if (!isset($rev_by_types[$type][$year])) $rev_by_types[$type][$year] = 0;
      $rev_by_types[$type][$year] += $amount;
    }
  }

  // подготовить массив и отсортировать по выручке последнего отчётного периода
  $rev_by_amount = [];
  foreach($rev_by_types as $type => $amounts) {
    $amount_curr = $amounts[date('Y', $time_from)];

    $rev_by_amount[$amount_curr] = [
      'type' => $type,
      'amounts' => $amounts
    ];
  }
  krsort($rev_by_amount);

  $total = 0;
  foreach($rev_by_amount as $amount => $item) {
    $total += $amount;
  }
  foreach($rev_by_amount as $amount => $item) {
    // выводим значения больше 4% от общей суммы
    if ($total && $amount/$total*100 <= 4) {
      unset($rev_by_amount[$amount]);
    }
  }

  $chart = array(
    '#type' => 'chart',
    '#chart_type' => 'column',
    '#title' => 'Отгрузка по основным видам продукции по данным бухгалтерии (' . DASH_REV_SUFFIX . ')',
    '#legend_position' => 'bottom',
    '#height' => '400',
    'xaxis' => [
      '#type' => 'chart_xaxis',
      '#labels' => [],
      '#raw_options' => ['textStyle' => ['fontName' => '<global-font-name>']],
    ],
    'yaxis' => [
      '#type' => 'chart_yaxis',
      '#raw_options' => ['textStyle' => ['fontName' => '<global-font-name>']],
    ],
    '#raw_options' => [
      'titleTextStyle' => ['bold' => 'true', 'fontName' => '<global-font-name>', 'fontSize' => '16'],
      'bar' => ['groupWidth' => "61%"],
      'legend' => [ 'position' => 'bottom', 'textStyle' => ['fontSize' => '13', 'fontName' => '<global-font-name>'] ],
      'chartArea' => [
        'width' => '95%',
        'height' => '70%',
        'left' => 50,
      ],
    ],
  );

  foreach($rev_by_amount as $rt) {
    $chart['xaxis']['#labels'][] = $rt['type'];
  }

  $year_prev = 0;
  $i = 0;
  foreach($rev_by_amount as &$rt) {
    ksort($rt['amounts']);

    foreach($rt['amounts'] as $year => $amount) {

      if (!isset($chart[$year])) {
        $chart[$year] = array(
          '#type' => 'chart_data',
          '#title' => (string)$year,
          '#data' => [],
        );
      }
      $delta = empty($rt['amounts'][$year_prev]) ? '' : ($rt['amounts'][$year] > $rt['amounts'][$year_prev] ? '+' : '') . number_format(($rt['amounts'][$year]/$rt['amounts'][$year_prev]*100)-100, 0, null, ' ') . '%';
      $year_prev = $year;

      $chart[$year]['#data'][] = $rt['amounts'][$year];
      $chart[$year][$i] = array(
        '#type' => 'chart_data_item',
        '#raw_options' => [
          'annotation' => number_format($rt['amounts'][$year], 0, '', ' ') . ($delta ? ' (' . $delta . ')' : ''),
        ],
      );
    }
    $i++;
    $year_prev = 0;
  }

  return $chart;
}


/**
 * ----- Выборка данных ------------------------------------------------------------------------------------------------
 */

/**
 *  Вернуть данные по ОТГРУЗКЕ продукции (сущность plan/plan_ship)
 *  с учётом заданных параметров
 * @param $conditions
 *   - type - тип записи (план, факт, неотгруженные контракты)
 *   - manual (bool) - данные из 1с или ручной ввод (если не задано, то только данные из 1с)
 *   - period - массив ['from' => , 'to' => не включительно]
 *   - noms - массив ID номенклатуры, которые нужно отобрать
 *   - regions - массив ID регионов, которые нужно отобрать
 *   - exclude - массив условий, которые нужно исключить
 *     - noms - массив ID номенклатуры, которые нужно исключить
 *     - regions - массив ID регионов, которые нужно исключить
 * @return array|mixed|null
 */
function dash_plan_ship_get_by_conditions($conditions)
{
  $fid = drupal_hash_base64(__FUNCTION__ . serialize($conditions));
  $result = &drupal_static($fid);

  if (!isset($result)) {
    $dbr = db_select('eck_plan', 'p');
    $dbr->condition('p.type', 'plan_ship');
    $dbr->addField('p', 'id');

    $dbr->innerJoin('field_data_field_record_type_td', 'frt', 'frt.entity_id = p.id');
    $dbr->condition('frt.bundle', 'plan_ship');
    $dbr->condition('frt.field_record_type_td_value', $conditions['type']);

    $dbr->innerJoin('field_data_field_date', 'frd', 'frd.entity_id = p.id');
    $dbr->condition('frd.bundle', 'plan_ship');
    if (!empty($conditions['period'])) {
      $dbr->condition('frd.field_date_value', $conditions['period']['from'], '>=');
      $dbr->condition('frd.field_date_value', $conditions['period']['to'], '<');
    }
    $dbr->addField('frd', 'field_date_value', 'date');

    $dbr->leftJoin('field_data_field_quantity_td', 'fq', 'fq.entity_id = p.id');
    $dbr->condition(db_or()
      ->isNull('fq.bundle')
      ->condition('fq.bundle', 'plan_ship')
    );
    $dbr->addField('fq', 'field_quantity_td_value', 'qty');

    $dbr->leftJoin('field_data_field_amount', 'fa', 'fa.entity_id = p.id');
    $dbr->condition(db_or()
      ->isNull('fa.bundle')
      ->condition('fa.bundle', 'plan_ship')
    );
    $dbr->addField('fa', 'field_amount_value', 'amount');

    $dbr->leftJoin('field_data_field_net_cost', 'fnc', 'fnc.entity_id = p.id');
    $dbr->condition(db_or()
      ->isNull('fnc.bundle')
      ->condition('fnc.bundle', 'plan_ship')
    );
    $dbr->addField('fnc', 'field_net_cost_value', 'net_cost');

    $dbr->leftJoin('field_data_field_nomenklatura', 'fn', 'fn.entity_id = p.id');
    $dbr->condition(db_or()
      ->isNull('fn.bundle')
      ->condition('fn.bundle', 'plan_ship')
    );
    $dbr->condition('fn.field_nomenklatura_tid', DASH_TD_NOM_ID_LIST_TO_EXCLUDE, 'NOT IN');
    $dbr->leftJoin('taxonomy_term_data', 't', 't.tid = fn.field_nomenklatura_tid');
    $dbr->fields('t', ['tid', 'name']);
    if (!empty($conditions['noms'])) {
      $dbr->condition('fn.field_nomenklatura_tid', $conditions['noms'], 'IN');
    }
    if (!empty($conditions['exclude']['noms'])) {
      $dbr->condition('fn.field_nomenklatura_tid', $conditions['exclude']['noms'], 'NOT IN');
    }

    $dbr->leftJoin('field_data_field_nom_nds', 'fnds', 'fnds.entity_id = fn.field_nomenklatura_tid');
    $dbr->addField('fnds', 'field_nom_nds_value', 'nds');

    $dbr->leftJoin('field_data_field_client', 'fct', 'fct.entity_id = p.id');
    $dbr->condition(db_or()
      ->isNull('fct.bundle')
      ->condition('fct.bundle', 'plan_ship')
    );
    $dbr->leftJoin('field_data_field_region', 'fr', 'fr.entity_id = fct.field_client_tid');
    $dbr->leftJoin('taxonomy_term_data', 'tr', 'tr.tid = fr.field_region_tid');
    $dbr->addField('tr', 'tid', 'region_tid');
    $dbr->addField('tr', 'name', 'region_name');
    if (!empty($conditions['regions'])) {
      $dbr->condition('fr.field_region_tid', $conditions['regions'], 'IN');
    }
    if (!empty($conditions['exclude']['regions'])) {
      $dbr->condition('fr.field_region_tid', $conditions['exclude']['regions'], 'NOT IN');
    }

    // для полей, добавленных позже нужно учитывать, что данные могут быть не заданы
    $dbr->leftJoin('field_data_field_is_manual', 'fm', 'fm.entity_id = p.id');
    $dbr->condition(db_or()
      ->isNull('fm.bundle')
      ->condition('fm.bundle', 'plan_ship')
    );
    if (isset($conditions['manual']) && $conditions['manual']) {
      $dbr->condition('fm.field_is_manual_value', 1);
    } else {
      $dbr->condition(db_or()
        ->isNull('fm.field_is_manual_value')
        ->condition('fm.field_is_manual_value', 0)
      );
    }
    $dbr->addField('fm', 'field_is_manual_value', 'manual');

    $dbr->orderBy('date');
    $result = $dbr->execute()->fetchAll();
  }

  return $result;
}

/**
 *  Вернуть данные по ОТГРУЗКЕ продукции (сущность ship/ship)
 *  с учётом заданных параметров
 *   Таблица на замену plan/plan_ship.
 *   todo перенести данные из plan/plan_ship.
 *
 * @param $conditions
 *   - company_id* - по какой компании KCCC собирать данные
 *   - type - тип записи (план, факт, неотгруженные контракты)
 *   - period - массив ['from' => , 'to' => не включительно]
 *   - manual (bool) - данные из 1с или ручной ввод (если не задано, то только данные из 1с)
 * @return array|mixed|null
 */
function dash_ship_get_by_conditions($conditions)
{
  $fid = drupal_hash_base64(__FUNCTION__ . serialize($conditions));
  $result = &drupal_static($fid);

  if (!isset($result)) {
    $dbr = db_select('eck_ship', 's');
    $dbr->condition('s.type', 'ship');
    $dbr->addField('s', 'id');

    $dbr->innerJoin('field_data_field_s_company', 'fc', 'fc.entity_id = s.id');
    $dbr->condition('fc.field_s_company_tid', $conditions['company_id']);
    $dbr->addField('fc', 'field_s_company_tid', 'company');

    $dbr->innerJoin('field_data_field_s_type', 'ft', 'ft.entity_id = s.id');
    if (!empty($conditions['type'])) {
      $dbr->condition('ft.field_s_type_value', $conditions['type']);
    }
    $dbr->addField('ft', 'field_s_type_value', 'type');

    $dbr->innerJoin('field_data_field_s_date', 'frd', 'frd.entity_id = s.id');
    if (!empty($conditions['period'])) {
      $dbr->condition('frd.field_s_date_value', $conditions['period']['from'], '>=');
      $dbr->condition('frd.field_s_date_value', $conditions['period']['to'], '<');
    }
    $dbr->addField('frd', 'field_s_date_value', 'date');

    $dbr->innerJoin('field_data_field_s_quantity', 'fq', 'fq.entity_id = s.id');
    $dbr->addField('fq', 'field_s_quantity_value', 'qty');

    $dbr->innerJoin('field_data_field_s_amount', 'fa', 'fa.entity_id = s.id');
    $dbr->addField('fa', 'field_s_amount_value', 'amount');

    $dbr->innerJoin('field_data_field_s_net_cost', 'fnc', 'fnc.entity_id = s.id');
    $dbr->addField('fnc', 'field_s_net_cost_value', 'net_cost');

    // todo пока не перенесёны записи ТД, детализация по номенклатуре и клиентам не нужна
//    $dbr->innerJoin('field_data_field_s_nomenklatura', 'fn', 'fn.entity_id = s.id');
//    $dbr->condition('fn.field_s_nomenklatura_tid', DASH_TD_NOM_ID_LIST_TO_EXCLUDE, 'NOT IN');
//    $dbr->leftJoin('taxonomy_term_data', 't', 't.tid = fn.field_s_nomenklatura_tid');
//    $dbr->fields('t', ['tid', 'name']);
//    if (!empty($conditions['noms'])) {
//      $dbr->condition('fn.field_s_nomenklatura_tid', $conditions['noms'], 'IN');
//    }
//    if (!empty($conditions['exclude']['noms'])) {
//      $dbr->condition('fn.field_s_nomenklatura_tid', $conditions['exclude']['noms'], 'NOT IN');
//    }
//    $dbr->leftJoin('field_data_field_nom_nds', 'fnds', 'fnds.entity_id = fn.field_s_nomenklatura_tid');
//    $dbr->addField('fnds', 'field_nom_nds_value', 'nds');

//    $dbr->leftJoin('field_data_field_client', 'fct', 'fct.entity_id = s.id');
//    $dbr->condition(db_or()
//      ->isNull('fct.bundle')
//      ->condition('fct.bundle', 'plan_ship')
//    );
//    $dbr->leftJoin('field_data_field_region', 'fr', 'fr.entity_id = fct.field_client_tid');
//    $dbr->leftJoin('taxonomy_term_data', 'tr', 'tr.tid = fr.field_region_tid');
//    $dbr->addField('tr', 'tid', 'region_tid');
//    $dbr->addField('tr', 'name', 'region_name');
//    if (!empty($conditions['regions'])) {
//      $dbr->condition('fr.field_region_tid', $conditions['regions'], 'IN');
//    }
//    if (!empty($conditions['exclude']['regions'])) {
//      $dbr->condition('fr.field_region_tid', $conditions['exclude']['regions'], 'NOT IN');
//    }

    // для полей, добавленных позже нужно учитывать, что данные могут быть не заданы
    $dbr->leftJoin('field_data_field_s_is_manual', 'fm', 'fm.entity_id = s.id');
    if (empty($conditions['manual'])) {
      $dbr->condition('fm.field_s_is_manual_value', 0);
    } else {
      $dbr->condition('fm.field_s_is_manual_value', 1);
    }
    $dbr->addField('fm', 'field_s_is_manual_value', 'manual');

    $dbr->orderBy('date');
    $result = $dbr->execute()->fetchAll();
  }

  return $result;
}

/**
 *  Вернуть данные по поступлению ДС (сущность cash_income/cash_income)
 *  с учётом заданных параметров.
 *  Таблица на замену plan/plan_revenue.
 *
 * @param $conditions
 *   - company_id* - tid компании kccc
 *   - period - массив ['from' =>, 'to' => не включительно]           * - обязательно
 *   - type - тип записи (план, факт, неотгруженные контракты)
 *   - manual - данные из 1с или ручной ввод (если не задано, то только данные из 1с)
 * @return array|mixed|null
 */
function dash_cash_income_get_by_conditions($conditions)
{
  $fid = drupal_hash_base64(__FUNCTION__ . serialize($conditions));
  $result = &drupal_static($fid);

  if (!isset($result)) {
    $dbr = db_select('eck_cash_income', 'ci');
    $dbr->condition('ci.type', 'cash_income');
    $dbr->addField('ci', 'id');

    $dbr->innerJoin('field_data_field_ci_company', 'fc', 'fc.entity_id = ci.id');
    $dbr->condition('fc.field_ci_company_tid', $conditions['company_id']);
    $dbr->addField('fc', 'field_ci_company_tid', 'company');

    $dbr->innerJoin('field_data_field_ci_type', 'ft', 'ft.entity_id = ci.id');
    if (isset($conditions['type'])) {
      $dbr->condition('ft.field_ci_type_value', $conditions['type']);
    }
    $dbr->addField('ft', 'field_ci_type_value', 'type');

    $dbr->innerJoin('field_data_field_ci_date', 'frd', 'frd.entity_id = ci.id');
    $dbr->condition('frd.field_ci_date_value', $conditions['period']['from'], '>=');
    $dbr->condition('frd.field_ci_date_value', $conditions['period']['to'], '<');
    $dbr->addField('frd', 'field_ci_date_value', 'date');

    $dbr->innerJoin('field_data_field_ci_amount', 'fa', 'fa.entity_id = ci.id');
    $dbr->addField('fa', 'field_ci_amount_value', 'amount');

    $dbr->innerJoin('field_data_field_ci_is_manual', 'fm', 'fm.entity_id = ci.id');
    if (empty($conditions['manual'])) {
      $dbr->condition('fm.field_ci_is_manual_value', 0);
    } else {
      $dbr->condition('fm.field_ci_is_manual_value', 1);
    }
    $dbr->addField('fm', 'field_ci_is_manual_value', 'manual');

    $dbr->orderBy('date');
    $result = $dbr->execute()->fetchAll();
  }

  return $result;
}

/**
 *  Удалить данные по поступлению ДС (сущность cash_income/cash_income)
 *  с учётом заданных параметров.
 *
 * @param $conditions
 *   - company_id* - tid компании kccc
 *   - month_start - массив ['from' =>, 'to' => не включительно]           * - обязательно
 *   - type - тип записи (план, факт, неотгруженные контракты)
 *   - manual - данные из 1с или ручной ввод (если не задано, то только данные из 1с)
 * @return array|mixed|null
 */
function dash_cash_income_delete_by_month($conditions)
{
  if ($conditions['company_id'] && $conditions['month_start'] && $conditions['type'] && $conditions['manual']) {
    $next_month_start = gmmktime(0, 0, 0, date('n', $conditions['month_start'])+1, 1, date('Y', $conditions['month_start']));

    $efquery = new EntityFieldQuery();
    $efquery
      ->entityCondition('entity_type', 'cash_income')
      ->entityCondition('bundle', 'cash_income')
      ->fieldCondition('field_ci_date', 'value', $conditions['month_start'], '>=')
      ->fieldCondition('field_ci_date', 'value', $next_month_start, '<')
      ->fieldCondition('field_ci_company', 'value', $conditions['company_id'])
      ->fieldCondition('field_ci_type', 'value', $conditions['type'])
      ->fieldCondition('field_ci_is_manual', 'value', $conditions['manual']);

    $result = $efquery->execute();
    if ($result) {
      entity_delete_multiple('cash_income', array_keys($result['cash_income']));
    }
  }
}

/**
 *  Вернуть данные по Остаткам готовой продукции и сырья (remains/remains_brief)
 *  с учётом заданных параметров.
 *
 * @param $conditions
 *   - company_id* - tid компании kccc
 *   - period* - массив ['from' =>, 'to' => не включительно]
 *   - category - категория записи (1 - гп, 2 - сырьё)
 * @return array|mixed|null
 */
function dash_remains_brief_get_by_conditions($conditions)
{
  $fid = drupal_hash_base64(__FUNCTION__ . serialize($conditions));
  $result = &drupal_static($fid);

  if (!isset($result)) {
    $dbr = db_select('eck_remains', 'r');
    $dbr->condition('r.type', 'remains_brief');
    $dbr->addField('r', 'id');

    $dbr->innerJoin('field_data_field_rm_company', 'fc', 'fc.entity_id = r.id');
    $dbr->condition('fc.field_rm_company_tid', $conditions['company_id']);
    $dbr->addField('fc', 'field_rm_company_tid', 'company');

    $dbr->innerJoin('field_data_field_rm_category', 'fct', 'fct.entity_id = r.id');
    if (isset($conditions['category'])) {
      $dbr->condition('fct.field_rm_category_value', $conditions['category']);
    }
    $dbr->addField('fct', 'field_rm_category_value', 'category');

    $dbr->innerJoin('field_data_field_rm_date', 'frd', 'frd.entity_id = r.id');
    $dbr->condition('frd.field_rm_date_value', $conditions['period']['from'], '>=');
    $dbr->condition('frd.field_rm_date_value', $conditions['period']['to'], '<');
    $dbr->addField('frd', 'field_rm_date_value', 'date');

    $dbr->innerJoin('field_data_field_rm_amount', 'fa', 'fa.entity_id = r.id');
    $dbr->addField('fa', 'field_rm_amount_value', 'amount');

    $dbr->orderBy('date');
    $result = $dbr->execute()->fetchAll();
  }

  return $result;
}

/**
 * Вернуть данные по ПРОИЗВОДСТВУ продукции (сущность plan/plan)
 * с учётом заданных параметров
 *
 * @param $conditions
 *  - fact (bool) - план или факт
 *  - manual (bool) - данные из 1с или ручной ввод (если не задано, то только данные из 1с)
 *  - period - массив ['from' => , 'to' => не включительно]
 *  - noms - массив ID, которые нужно отобрать
 *  - exclude - массив условий, которые нужно исключить
 *    - noms - массив ID, которые нужно исключить
 * @return array|mixed|null
 */
function dash_plan_prod_get_by_conditions($conditions)
{
  $fid = drupal_hash_base64(__FUNCTION__ . serialize($conditions));
  $result = &drupal_static($fid);

  if (!isset($result)) {
    $dbr = db_select('eck_plan', 'p');
    $dbr->condition('p.type', 'plan');
    $dbr->addField('p', 'id');

    $dbr->innerJoin('field_data_field_is_fact', 'ff', 'ff.entity_id = p.id');
    $dbr->condition('ff.bundle', 'plan');
    if (isset($conditions['fact'])) {
      $dbr->condition('ff.field_is_fact_value', $conditions['fact']);
    }
    $dbr->addField('ff', 'field_is_fact_value', 'fact');

    // для полей, добавленных позже нужно учитывать, что данные могут быть не заданы
    $dbr->leftJoin('field_data_field_is_manual', 'fm', 'fm.entity_id = p.id');
//    $dbr->condition(db_or()
//      ->isNull('fm.bundle')
//      ->condition('fm.bundle', 'plan')
//    );
    if (isset($conditions['manual']) && $conditions['manual']) {
      $dbr->condition('fm.field_is_manual_value', 1);
    } else {
      $dbr->condition(db_or()
        ->isNull('fm.field_is_manual_value')
        ->condition('fm.field_is_manual_value', 0)
      );
    }
    $dbr->addField('fm', 'field_is_manual_value', 'manual');

    $dbr->innerJoin('field_data_field_date', 'frd', 'frd.entity_id = p.id');
    $dbr->condition('frd.bundle', 'plan');
    if (isset($conditions['period'])) {
      $dbr->condition('frd.field_date_value', $conditions['period']['from'], '>=');
      $dbr->condition('frd.field_date_value', $conditions['period']['to'], '<');
    }
    $dbr->addField('frd', 'field_date_value', 'date');

    $dbr->leftJoin('field_data_field_nomenklatura', 'fn', 'fn.entity_id = p.id');
    $dbr->condition('fn.bundle', 'plan');
    $dbr->leftJoin('taxonomy_term_data', 't', 't.tid = fn.field_nomenklatura_tid');
    if (!empty($conditions['noms'])) {
      $dbr->condition('fn.field_nomenklatura_tid', $conditions['noms'], 'IN');
    }
    if (!empty($conditions['exclude']['noms'])) {
      $dbr->condition('fn.field_nomenklatura_tid', $conditions['exclude']['noms'], 'NOT IN');
    }
    $dbr->fields('t', ['tid', 'name']);

    $dbr->innerJoin('field_data_field_output', 'fo', 'fo.entity_id = p.id');
    $dbr->condition('fo.bundle', 'plan');
    $dbr->addField('fo', 'field_output_value', 'output');

    $dbr->orderBy('date');
    $result = $dbr->execute()->fetchAll();
  }

  return $result;
}

/**
 *  Вернуть данные по Расходу денежных средств (сущность cash_outcome/cash_outcome)
 *  с учётом заданных параметров
 * @param $conditions
 *   - company_id* - tid компании kccc
 *   - period - массив ['from' =>, 'to' => не включительно] * - обязателен
 *   - type - тип записи (план, факт)
 *   - category_ids - массив статей расходов
 *   - manual - данные из 1с или ручной ввод (если не задано, то только данные из 1с)
 * @return array|mixed|null
 */
function dash_cash_outcome_get_by_conditions($conditions)
{
  $fid = drupal_hash_base64(__FUNCTION__ . serialize($conditions));
  $result = &drupal_static($fid);

  if (!isset($result)) {
    $dbr = db_select('eck_cash_outcome', 'co');
    $dbr->condition('co.type', 'cash_outcome');
    $dbr->addField('co', 'id');

    $dbr->innerJoin('field_data_field_co_company', 'fc', 'fc.entity_id = co.id');
    $dbr->condition('fc.field_co_company_tid', $conditions['company_id']);
    $dbr->addField('fc', 'field_co_company_tid', 'company');

    $dbr->innerJoin('field_data_field_co_category', 'fct', 'fct.entity_id = co.id');
    if (!empty($conditions['category_ids'])) {
      $dbr->condition('fct.field_co_category_tid', $conditions['category_ids'], 'IN');
    }
    $dbr->addField('fct', 'field_co_category_tid', 'category');

    $dbr->innerJoin('field_data_field_co_type', 'ft', 'ft.entity_id = co.id');
    if (!empty($conditions['type'])) {
      $dbr->condition('ft.field_co_type_value', $conditions['type']);
    }
    $dbr->addField('ft', 'field_co_type_value', 'type');

    $dbr->innerJoin('field_data_field_co_is_manual', 'fm', 'fm.entity_id = co.id');
    if (empty($conditions['manual'])) {
      $dbr->condition('fm.field_co_is_manual_value', 0);
    } else {
      $dbr->condition('fm.field_co_is_manual_value', 1);
    }
    $dbr->addField('fm', 'field_co_is_manual_value', 'manual');

    $dbr->innerJoin('field_data_field_co_date', 'fd', 'fd.entity_id = co.id');
    $dbr->condition('fd.field_co_date_value', $conditions['period']['from'], '>=');
    $dbr->condition('fd.field_co_date_value', $conditions['period']['to'], '<');
    $dbr->addField('fd', 'field_co_date_value', 'date');

    $dbr->innerJoin('field_data_field_co_amount', 'fa', 'fa.entity_id = co.id');
    $dbr->addField('fa', 'field_co_amount_value', 'amount');

    $dbr->orderBy('date');
    $result = $dbr->execute()->fetchAll();
  }

  return $result;
}

/**
 *  Вернуть данные по Кредитам и задолженностям (сущность debt/debt)
 *  с учётом заданных параметров
 * @param $conditions
 *   - company_id* - tid компании
 *   - period - массив ['from' =>, 'to' => не включительно] * - обязателен
 *   - type - тип записи (1 - план, 2 - факт)
 *   - kinds - массив типов записей (1 - дебиторская, 2- кредиторская, 3 - кредиты, 4 - займы)
 *   - category - категория записи (пока это 1 - статья, 2 - контрагент)
 *   - manual - данные из 1с или ручной ввод (если не задано, то только данные из 1с)
 * @return array|mixed|null
 */
function dash_debt_get_by_conditions($conditions)
{
  $fid = drupal_hash_base64(__FUNCTION__ . serialize($conditions));
  $result = &drupal_static($fid);

  if (!isset($result)) {
    $dbr = db_select('eck_debt', 'd');
    $dbr->condition('d.type', 'debt');
    $dbr->addField('d', 'id');

    $dbr->innerJoin('field_data_field_d_company', 'fc', 'fc.entity_id = d.id');
    $dbr->condition('fc.field_d_company_tid', $conditions['company_id']);
    $dbr->addField('fc', 'field_d_company_tid', 'company');

    $dbr->innerJoin('field_data_field_d_name', 'fn', 'fn.entity_id = d.id');
    $dbr->addField('fn', 'field_d_name_value', 'name');

    $dbr->innerJoin('field_data_field_d_category', 'fct', 'fct.entity_id = d.id');
    if (!empty($conditions['category'])) {
      $dbr->condition('fct.field_d_category_value', $conditions['category']);
    }
    $dbr->addField('fct', 'field_d_category_value', 'category');

    $dbr->innerJoin('field_data_field_d_type', 'ft', 'ft.entity_id = d.id');
    if (!empty($conditions['type'])) {
      $dbr->condition('ft.field_d_type_value', $conditions['type']);
    }
    $dbr->addField('ft', 'field_d_type_value', 'type');

    $dbr->innerJoin('field_data_field_d_kind', 'fk', 'fk.entity_id = d.id');
    if (!empty($conditions['kinds'])) {
      $dbr->condition('fk.field_d_kind_value', $conditions['kinds'], 'IN');
    }
    $dbr->addField('fk', 'field_d_kind_value', 'kind');

    $dbr->innerJoin('field_data_field_d_date', 'fd', 'fd.entity_id = d.id');
    $dbr->condition('fd.field_d_date_value', $conditions['period']['from'], '>=');
    $dbr->condition('fd.field_d_date_value', $conditions['period']['to'], '<');
    $dbr->addField('fd', 'field_d_date_value', 'date');

    $dbr->innerJoin('field_data_field_d_amount', 'fa', 'fa.entity_id = d.id');
    $dbr->addField('fa', 'field_d_amount_value', 'amount');

    $dbr->innerJoin('field_data_field_d_amount2', 'fa2', 'fa2.entity_id = d.id');
    $dbr->addField('fa2', 'field_d_amount2_value', 'amount2');

    $dbr->innerJoin('field_data_field_d_is_manual', 'fm', 'fm.entity_id = d.id');
    if (empty($conditions['manual'])) {
      $dbr->condition('fm.field_d_is_manual_value', 0);
    } else {
      $dbr->condition('fm.field_d_is_manual_value', 1);
    }
    $dbr->addField('fm', 'field_d_is_manual_value', 'manual');

    $dbr->orderBy('date');
    $result = $dbr->execute()->fetchAll();
  }

  return $result;
}


/**
 *  Вернуть данные по из таблицы Бюджета доходов и расходов (ручной ввод данных) (manual/bdr)
 *  с учётом заданных параметров
 * @param $conditions
 *   - company_id* - tid компании
 *   - period* - массив ['from' =>, 'to' => не включительно]
 *   - type - тип записи (план, факт, неотгруженные контракты)
 *   - category_id - статья Бюджета доходов и расходов
 * @return array|mixed|null
 */
function dash_manual_bdr_get_by_conditions($conditions)
{
  $fid = drupal_hash_base64(__FUNCTION__ . serialize($conditions));
  $result = &drupal_static($fid);

  if (!isset($result)) {
    $dbr = db_select('eck_manual', 'm');
    $dbr->condition('m.type', 'bdr');
    $dbr->addField('m', 'id');

    $dbr->innerJoin('field_data_field_m_company', 'fc', 'fc.entity_id = m.id');
    $dbr->condition('fc.bundle', 'bdr');
    $dbr->condition('fc.field_m_company_tid', $conditions['company_id']);
    $dbr->addField('fc', 'field_m_company_tid', 'company');

    $dbr->innerJoin('field_data_field_m_date', 'frd', 'frd.entity_id = m.id');
    $dbr->condition('frd.bundle', 'bdr');
    $dbr->condition('frd.field_m_date_value', $conditions['period']['from'], '>=');
    $dbr->condition('frd.field_m_date_value', $conditions['period']['to'], '<');
    $dbr->addField('frd', 'field_m_date_value', 'date');

    $dbr->innerJoin('field_data_field_m_type', 'frt', 'frt.entity_id = m.id');
    $dbr->condition('frt.bundle', 'bdr');
    if (isset($conditions['type'])) {
      $dbr->condition('frt.field_m_type_value', $conditions['type']);
    }
    $dbr->addField('frt', 'field_m_type_value', 'type');

    $dbr->innerJoin('field_data_field_m_category', 'fct', 'fct.entity_id = m.id');
    $dbr->condition('fct.bundle', 'bdr');
    if (isset($conditions['category_id'])) {
      $dbr->condition('fct.field_m_category_tid', $conditions['category_id']);
    }
    $dbr->innerJoin('taxonomy_term_data', 'tc', 'tc.tid = fct.field_m_category_tid');
    $dbr->addField('tc', 'tid', 'category_id');
    $dbr->addField('tc', 'name', 'category_name');

    $dbr->innerJoin('field_data_field_m_amount', 'fa', 'fa.entity_id = m.id');
    $dbr->condition('fa.bundle', 'bdr');
    $dbr->addField('fa', 'field_m_amount_value', 'amount');

    $dbr->orderBy('date');
    $result = $dbr->execute()->fetchAll();
  }

  return $result;
}

/**
 * ----- Формы ---------------------------------------------------------------------------------------------------------
 */
function dash_period_filter_form($form, &$form_state, $params)
{
  if (!isset($form_state['period'])) {
    $form_state['period'] = $params['period'];
  }
  $form_state['callback'] = $params['callback'];

  $form['#attributes'] = ['class' => ['dash-filter-form']];
  $form['period'] = [
    '#type' => 'container',
    '#attributes' => ['class' => ['period-container']],
  ];
  $form['period']['period_from'] = [
    '#type' => 'date_popup',
    '#title' => 'Период',
    '#default_value' => date('Y-m-d', empty($_GET['period_from']) ? $form_state['period']['from'] : $_GET['period_from']),
    '#ajax' => [
      'wrapper' => $params['wrapper'],
      'callback' => 'dash_period_filter_form_ajax_callback',
    ],
    '#date_format' => 'd.m.Y',
    '#date_year_range' => '-3:+1',
    '#date_label_position' => 'invisible',
  ];

  $form['period']['period_to'] = [
    '#type' => 'date_popup',
    '#title' => '&nbsp;',
    '#default_value' => date('Y-m-d', empty($_GET['period_to']) ? $form_state['period']['to'] - 1 : $_GET['period_to']),
    '#ajax' => [
      'wrapper' => $params['wrapper'],
      'callback' => 'dash_period_filter_form_ajax_callback',
    ],
    '#date_format' => 'd.m.Y',
    '#date_year_range' => '-3:+1',
    '#date_label_position' => 'invisible',
  ];

  return $form;
}
function dash_period_filter_form_ajax_callback($form, $form_state)
{
  $period = [
    'from' => strtotime($form_state['values']['period_from']['date']),
    'to' => strtotime($form_state['values']['period_to']['date']) + 60*60*24,  // конец периода задаётся днём, следующим за заданным
    'end' => '',
  ];

  // todo небезопасно
  $func = $form_state['callback'];

  return (function_exists($func) ? $func($period) : 'Function ' . $func . ' not found');
}

/**
 * ----- Вспомогательные функции ---------------------------------------------------------------------------------------
 */

/** Вернуть начальное и конечное (не включительно) время Unix
 * 12-и месячного периода начиная с месяца $month_num
 * и смещением $year_shift лет от текущего периода.
 * from - начало 12и месячного периода
 * to   - == end для прошлых периодов и == now для текущего
 * end  - конец 12и месячного периода
 * $year_shift = 0 - текущий период
 */
function dash_year_time_bounds_get($month_num_start, $year_shift = 0)
{
  // получить начало текущего периода
  $time_month_start = gmmktime(0, 0, 0, $month_num_start, 1, date('Y'));
  $year_start = REQUEST_TIME < $time_month_start ? date('Y')-1 : date('Y');

  // применить смещение
  $year_start = $year_start + $year_shift;

  $from = gmmktime(0, 0, 0, $month_num_start, 1, $year_start);
  $end = gmmktime(0, 0, 0, $month_num_start+12, 1, $year_start);
  // для предыдущих берем весь сезон
  if ($year_shift) {
    $to = gmmktime(0, 0, 0, $month_num_start+12, 1, $year_start);
  }
  // для текущего по сегодняшнюю дату
  else {
    $to = gmmktime(0, 0, 0, date('n'), date('j'), date('Y'));
  }

  return [
    'from' => $from,
    'to' => $to,
    'end' => $end,
  ];
}

/**
 * Вернуть начальное и конечное (не включительно) время Unix
 * 12-и месячного Сезона начиная с месяца $month_num_start.
 *
 * Сезон определяется НА ЗАДАННЫЙ МЕСЯЦ.
 * То есть, для сезона, начинающегося в Октябре ($month_num_start = 10),
 * если дата $datetime_set задана в октябре, то данные выводим по сентябрь включительно, то есть предыдущий сезон.
 * Если дата в ноябре, то это данные за октябрь, а октябрь - начало нового сезона.
 *
 * @return
 *   from - начало 12и месячного периода
 *   to   - == end для прошлых периодов и == now для текущего
 *   end  - конец 12и месячного периода
 */
function dash_season_bounds_get_by_date($month_num_start, $datetime_set)
{
  // получить начало заданного месяца
  $month_start_set = gmmktime(0, 0, 0, date('n', $datetime_set), 1, date('Y', $datetime_set));

  // год заданного месяца
  $year = date('Y', $month_start_set);

  // ищем Сезон, включающий заданный месяц
  // сравниваем с предыдущим месяцем ($month_start_set-1), так как заданный месяц определяет
  do {
    $period_from_month_start = gmmktime(0, 0, 0, $month_num_start, 1, $year);
    $period_end_month_start = gmmktime(0, 0, 0, $month_num_start + 12, 1, $year);
    $year--;
  } while (!($period_from_month_start <= ($month_start_set-1) && ($month_start_set-1) < $period_end_month_start));

  return [
    'from' => $period_from_month_start,
    'to' => $month_start_set,
    'end' => $period_end_month_start,
  ];
}

/**
 * Вернуть начальное и конечное (не включительно) время Unix
 * для периода:
 *   с месяца $month_num и смещением $year_shift (0 - текущий) лет от текущего периода
 *   до текущей даты в заданном сезоне
 *
 * from - начало 12и месячного периода
 * to   - == end для прошлых периодов и == now для текущего
 */
function dash_period_time_bounds_get($month_num_start, $year_shift = 0)
{
  // получить начало текущего периода
  $time_month_start = gmmktime(0, 0, 0, $month_num_start, 1, date('Y'));
  $year_start = REQUEST_TIME < $time_month_start ? date('Y')-1 : date('Y');

  // применить смещение
  $year_start = $year_start + $year_shift;

  $from = gmmktime(0, 0, 0, $month_num_start, 1, $year_start);
  $to = gmmktime(0, 0, 0, date('n'), date('j'), date('Y') + $year_shift);

  return [
    'from' => $from,
    'to' => $to,
  ];
}

/**
 * Вернуть смещение заданного периода на заданное количество лет
 */
function dash_period_shifted_get($period, $year_shift = 0)
{
  $from = gmmktime(0, 0, 0, date('n', $period['from']), date('j', $period['from']), date('Y', $period['from']) + $year_shift);
  $to = gmmktime(0, 0, 0, date('n', $period['to']), date('j', $period['to']), date('Y', $period['to']) + $year_shift);
  $end = gmmktime(0, 0, 0, date('n', $period['end']), date('j', $period['end']), date('Y', $period['end']) + $year_shift);

  return [
    'from' => $from,
    'to' => $to,
    'end' => $end,
  ];
}

/**
 * Вернуть для страницы период по-умолчанию
 * @param $month_start
 * @return array
 */
function dash_page_time_bounds_get($month_start)
{
  if (strpos($_GET['q'], 'period/closed') !== false) {
    $bounds = dash_year_time_bounds_get($month_start, -1);
  } else {
    $bounds = dash_year_time_bounds_get($month_start);
  }

  return $bounds;
}

function dash_types_to_merge_get()
{
  return [
    'Продукция Интер Групп' => 'Собственная регистрация',
    'Собственная продукция' => 'Собственная регистрация',
    'Продукция' => 'Заёмная регистрация',
    'Семена' => 'Товары',
    'Товар' => 'Товары',
  ];
}

/**
 * Возвращает список месяцев (unix начало и конец) для Периода на входе
 * @param $period
 * @return array
 */
function dash_months_list_get($period)
{
  // список месяцев, за которые выводим график
  $time_months_list = [];
  $time_month_start = $period['from'];
  while($time_month_start < $period['end']) {
    $time_month_end = gmmktime(0, 0, 0, date('n', $time_month_start)+1, 1, date('Y', $time_month_start));
    $time_months_list[] = [
      'start' => $time_month_start,
      'end' => $time_month_end,
    ];
    $time_month_start = $time_month_end;
  }

  return $time_months_list;
}

/**
 * Возвращает список недель (unix начало и конец) для Периода на входе
 * @param $period
 * @return array
 */
function dash_weeks_list_get($period)
{
  $time_weeks_list = [];

  // начальная неделя + 2 дня (начало нашей недели в среду)
  $week_num = date('W', $period['from']);
  $year = date('Y', $period['from']);
  $week_start =  gmmktime(0,0,0,1,1, $year) + $week_num * 7 * 86400 - date('N', gmmktime(0,0,0,1,1,$year)) * 86400 + 3*86400;

  // далее список +7 дней
  while($week_start < $period['end']) {
    $week_end =  $week_start + 7 * 86400;
    if ($week_start < $period['from']) $week_start = $period['from'];
    if ($week_end > $period['end']) $week_end = $period['end'];

    $time_weeks_list[] = [
      'start' => $week_start,
      'end' => $week_end,
    ];
    $week_start = $week_end;
  }

  return $time_weeks_list;
}

/**
 * Возвращает потомков термина на входе
 * @param $parent_tid
 * @return array
 */
function dash_term_siblings_get($parent_tid)
{
  $result = [$parent_tid];

  if ($parent_term = taxonomy_term_load($parent_tid)) {
    foreach (taxonomy_get_tree($parent_term->vid, $parent_tid) as $terms) {
      $result[] = $terms->tid;
    }
  }

  return $result;
}

/**
 * Ищет и возвращает запись по 1с ID из справочника $vid.
 * Создаёт и возвращает пустую новую, если запись не найдена.
 * @param $voc - vid словаря или его наименование
 * @param $record_1c_id
 * @return false|object
 */
function dash_term_get_by_1c_id($voc, $record_1c_id)
{
  $vid = is_numeric($voc) ? $voc : taxonomy_vocabulary_machine_name_load($voc)->vid;

  if ($vid && $record_1c_id) {
    $query = new EntityFieldQuery();
    $terms = $query
      ->entityCondition('entity_type', 'taxonomy_term')
      ->propertyCondition('vid', $vid)
      ->fieldCondition('field_1c_id', 'value', $record_1c_id)
      ->execute();
    if ($terms) {
      $term = current($terms['taxonomy_term']);
    } else {
      $term = (object)array(
        'vid' => $vid,
        'name' => '',
        'field_1c_id' => ['und' => [0 => ['value' => $record_1c_id]]],
      );
      taxonomy_term_save($term);
    }
    $entities = entity_load('taxonomy_term', [$term->tid]);
  }
  return empty($entities) ? false: current($entities);
}

function dash_nomenklatura_get_by_1c_artikul($company_inn, $artikul)
{
  // номенклатура хранится в разных словарях
  $vid = taxonomy_vocabulary_machine_name_load('nomenklatura')->vid;
  $company = dash_term_get_by_1c_id('companies', $company_inn);
  if ($vid && $artikul) {
    $query = new EntityFieldQuery();
    $query
      ->entityCondition('entity_type', 'taxonomy_term')
      ->propertyCondition('vid', $vid)
      ->fieldCondition('field_nom_artikul', 'value', $artikul);
    $query->fieldCondition('field_kccc_company', 'tid', $company->tid);
    $terms = $query->execute();
    if ($terms) {
      $term = current($terms['taxonomy_term']);
      $entities = $term ? entity_load('taxonomy_term', [$term->tid]) : null;
    }
  }
  return empty($entities) ? 0 : current($entities);
}

/**
 * Найти клиента по 1c_id или создать, если не найден

 * @param $company_inn - справочник какой компании KCCC проверять
 * @param $client_id
 * @return false|int|mixed
 */
function dash_client_get_by_1c_id($company_inn, $client_id)
{
  // клиенты хранятся в разных словарях
  $vid = taxonomy_vocabulary_machine_name_load('clients')->vid;
  $company = dash_term_get_by_1c_id('companies', $company_inn);

  if ($vid && $client_id) {
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'taxonomy_term')
      ->propertyCondition('vid', $vid)
      ->fieldCondition('field_1c_id', 'value', $client_id);
    $query->fieldCondition('field_kccc_company', 'tid', $company->tid);
    $terms = $query->execute();
    if ($terms) {
      $term = current($terms['taxonomy_term']);
    } else {
      $term = (object)array(
        'vid' => $vid,
        'name' => '',
        'field_1c_id' => ['und' => [0 => ['value' => $client_id]]],
        'field_kccc_company' => ['und' => [0 => ['tid' => $company->tid]]],
      );
      taxonomy_term_save($term);
    }
    $entities = $term ? entity_load('taxonomy_term', [$term->tid]) : null;
  }
  return empty($entities) ? 0: current($entities);
}

function dash_region_get_by_1c_id($region_1c_id)
{
  if ($region_1c_id) {
    $vid = taxonomy_vocabulary_machine_name_load('regions')->vid;
    $query = new EntityFieldQuery();
    $terms = $query
      ->entityCondition('entity_type', 'taxonomy_term')
      ->propertyCondition('vid', $vid)
      ->fieldCondition('field_1c_id', 'value', $region_1c_id)
      ->execute();
    if ($terms) {
      $term = current($terms['taxonomy_term']);
    } else {
      $term = (object)array(
        'vid' => $vid,
        'name' => '',
        'field_1c_id' => ['und' => [0 => ['value' => $region_1c_id]]],
      );
      taxonomy_term_save($term);
    }
    $entities = $term ? entity_load('taxonomy_term', [$term->tid]) : null;
  }
  return empty($entities) ? 0: current($entities);
}

/**
 * Удалить Остатки за период
 * @param $date_start
 * @param $date_end
 * @return void
 */
function dash_remains_delete_by_period($date_start, $date_end)
{
  if ($date_start && $date_end) {
    $efquery = new EntityFieldQuery();
    $efquery
      ->entityCondition('entity_type', 'remains')
      ->entityCondition('bundle', 'remains')
      ->fieldCondition('field_rm_date', 'value', $date_start, '>=')
      ->fieldCondition('field_rm_date', 'value', $date_end, '<');

    $result = $efquery->execute();
    if ($result) {
      entity_delete_multiple('remains', array_keys($result['remains']));
    }
  }

}

function dash_registration_get_by_1c_id($reg_1c_id)
{
  if ($reg_1c_id) {
    $query = new EntityFieldQuery();
    $regs = $query
      ->entityCondition('entity_type', 'registration')
      ->fieldCondition('field_1c_id', 'value', $reg_1c_id)
      ->execute();
    if ($regs) {
      $reg = current($regs['registration']);
    } else {
      $reg = entity_create('registration', [
        'type' => 'registration',
        'field_1c_id' => ['und' => [0 => ['value' => $reg_1c_id]]],
      ]);
      entity_save('registration', $reg);
    }
    $entities = entity_load('registration', [$reg->id]);
  }
  return empty($entities) ? 0: current($entities);
}

/**
 * Вернуть график по-умолчанию
 */
function dash_no_data_chart_get($title = null)
{
  return [
    '#type' => 'chart',
    '#title' => $title ?? '',
    '#chart_type' => 'pie',
    '#height' => '200',
    '#width' => '400',
    'pie_data' => [
      '#type' => 'chart_data',
      '#title' => 'Продукция',
      '#labels' => [],
      '#data' => []
    ],
    '#raw_options' => [
      'titleTextStyle' => ['bold' => 'true', 'fontName' => '<global-font-name>', 'fontSize' => '16'],
      'textStyle' => ['fontName' => '<global-font-name>']
    ],
  ];
}

/**
 * Обеспечивает выполнение запроса к заданной функции и возврат разметки с результатом
 */
function dash_ajax_load()
{
  $result = '';
  $module = $_GET['module'];
  $func = $_GET['func'];
  // Функция должна иметь префикс block_ в составе
  // для защиты от подмены функции.
  if (strpos($func, 'block_') !== false) {
    include_once(drupal_get_path('module', $module) . '/' . $module . '.module');
    $function = $module . '_' . $func;
    if (function_exists($function)) {
      $result = $function();
    }
  }

  print $result;
  drupal_exit();
}

function dash_preprocess_page(&$vars)
{
  // Для прорисовки графиков после загрузки их через ajax.
  // Подключаем вручную, тк стандартный модуль подключает её только при наличии графиков на странице,
  // а у нас одни обёртки
  drupal_add_library('charts_google', 'charts_google');

  // установить заголовки для страниц
  if (arg(0) == 'ah') {
    $vars['banner_title'] = 'Агрохимикат';
  }
  if (arg(0) == 'td') {
    $vars['banner_title'] = 'Торговый Дом';
  }
  if (arg(0) == 'fn') {
    $vars['banner_title'] = 'Финансы';
  }
}

/**
 * Вернуть смещение с заданного периода до DASH_YEAR_HISTORY_START года, но не более DASH_HISTORY_LENGTH
 */
function dash_years_shift_get($period = null)
{
  if (!$period) $period = dash_year_time_bounds_get(DASH_PERIOD_START_MONTH_TD);

  $years_shift = date('Y', $period['from']) - (DASH_HISTORY_START_YEAR_TD+1);
  return abs($years_shift)+1 > DASH_HISTORY_LENGTH ? DASH_HISTORY_LENGTH : $years_shift;
}

/**
 * Вернуть список смещений с заданного периода до DASH_YEAR_HISTORY_START года, но не более DASH_HISTORY_LENGTH
 * (например, за 3 года с текущего = [-2, -1, 0])
 */
function dash_years_shift_list_get($period = null, $month_num_start = DASH_PERIOD_START_MONTH_TD)
{
  if (!$period) $period = dash_year_time_bounds_get($month_num_start);

  $period_current = dash_year_time_bounds_get($month_num_start);

  $shift = (date('Y', $period_current['from']) - date('Y', $period['from'])) * (-1);
  $count = date('Y', $period['from']) - $month_num_start;
  $count = $count > DASH_HISTORY_LENGTH ? DASH_HISTORY_LENGTH : $count;

  $shifts = [];
  do {
    $shifts[] = $shift--;
  } while ($count-- > 0);

  return array_reverse($shifts);
}

/**
 * Определить, является ли заданный период текущим
 */
function dash_is_current_season($period)
{
  return $period['from'] < REQUEST_TIME && REQUEST_TIME < $period['end'];
}

/**
 * Вернуть отсортированный по имени список опций для селекта формы
 * @param $voc_name - имя словаря
 * @param $default_options - начальные опции, например 'all' => 'Все'
 */
function dash_form_options_get_from_taxonomy($voc_name, $default_options = null)
{
  if ($voc = taxonomy_vocabulary_machine_name_load($voc_name)) {
    if ($terms = taxonomy_get_tree($voc->vid)) {
      foreach ($terms as $term) {
        $options[$term->name] = $term->tid;
      }
    }
  }
  ksort($options);
  $options = array_flip($options);

  if (!empty($default_options)) {
    $options = array_merge($default_options, $options);
  }

  return $options;
}

/**
 * @param $tree - список терминов словаря
 * @param $parent_term - термин, для которого определить значение (имя или массив с наследниками)
 * @param $tids_include_only - отсутствующие в этом списке термины исключить из вывода
 * @return array
 *
 * получить опции в иерархическом порядке
 * вида:
 *   $options = [
 *    '11' => 'Родитель',
 *    '15' => '-Потомок',
 *    '15' => '--Потомок 2',
 *    '15' => '--Потомок 2',
 *    '16' => '-Потомок',
 *    '17' => '-Потомок',
 *    '11' => 'Родитель',
 *  ];
 *
 */
function dash_select_tree_get($tree, $parent_term = null, $tids_include_only = [])
{
  $option = false;
  $child = [];
  $tid = $parent_term->tid ?? 0;
  foreach($tree as $term) {
    if (in_array($tid, $term->parents)) {
      if ($result = dash_select_tree_get($tree, $term, $tids_include_only)) {
        $child += $result;
      }
    }
  }
  if ($child) {
    if ($tid) {
      $option[$tid] = str_repeat("-", $parent_term->depth) . $parent_term->name;
      $option += $child;
    }  else {
      $option = $child;
    }
  } else {
    if ($parent_term->name) {
      if (!$tids_include_only || in_array($tid, $tids_include_only)) $option[$tid] = str_repeat("-", $parent_term->depth) . $parent_term->name;
    }
  }

  return $option;
}

/**
 * Создать Запись плана типа cash_income
 */
function dash_cash_income_create($params)
{
  $transaction = db_transaction();
  try {
    $ci = entity_create('cash_income', [
      'type' => 'cash_income',
      'created' => $params['created'],
    ]);
    entity_save('cash_income', $ci);

    $ci_wr = entity_metadata_wrapper('cash_income', $ci);
    $ci_wr->field_ci_company = $params['company_id'];
    $ci_wr->field_ci_date = $params['month_ts'];
    $ci_wr->field_ci_type = $params['type'];
    $ci_wr->field_ci_is_manual = $params['manual'] ?? 0;
    $ci_wr->field_ci_amount = $params['amount'] ?? 0;
    $ci_wr->save();
  } catch (Exception $e) {
    $transaction->rollback();
    watchdog_exception('migration', $e);
  }

  return $ci ?? false;
}

/**
 * Создать Запись плана типа cash_outcome
 */
function dash_cash_outcome_create($params)
{
  $transaction = db_transaction();
  try {
    $co = entity_create('cash_outcome', [
      'type' => 'cash_outcome',
      'created' => $params['created'],
    ]);
    entity_save('cash_outcome', $co);

    $co_wr = entity_metadata_wrapper('cash_outcome', $co);
    $co_wr->field_co_company = $params['company_id'];
    $co_wr->field_co_category = $params['category_id'];
    $co_wr->field_co_date = $params['month_ts'];
    $co_wr->field_co_type = $params['type'];
    $co_wr->field_co_is_manual = $params['manual'] ?? 0;
    $co_wr->field_co_amount = $params['amount'] ?? 0;
    $co_wr->save();
  } catch (Exception $e) {
    $transaction->rollback();
    watchdog_exception('migration', $e);
  }

  return $co ?? false;
}

/**
 * Создать Запись плана типа plan
 */
function dash_plan_prod_create($params)
{
  $transaction = db_transaction();
  try {
    $plan = entity_create('plan', [
      'type' => 'plan',
      'created' => $params['created'],
    ]);
    entity_save('plan', $plan);

    $plan_wr = entity_metadata_wrapper('plan', $plan);
    $plan_wr->field_date = $params['month_ts'];
    $plan_wr->field_nomenklatura = $params['nom_id'];
    $plan_wr->field_is_fact = $params['fact'];
    $plan_wr->field_is_manual = $params['manual'];
    $plan_wr->field_output = $params['volume'];
    $plan_wr->save();
  } catch (Exception $e) {
    $transaction->rollback();
    watchdog_exception('migration', $e);
  }

  return $plan ?? false;
}

/**
 * Создать Запись плана типа plan
 */
function dash_plan_ship_create($params)
{
  $transaction = db_transaction();
  try {
    $plan = entity_create('plan', [
      'type' => 'plan_ship',
      'created' => $params['created'],
    ]);
    entity_save('plan', $plan);

    $plan_wr = entity_metadata_wrapper('plan', $plan);
    $plan_wr->field_record_type_td = $params['type'];
    $plan_wr->field_nomenklatura = $params['nom_id'] ?? 0;
    $plan_wr->field_client = $params['client_id'] ?? 0;
    $plan_wr->field_date = $params['month_ts'];
    $plan_wr->field_quantity_td = $params['qty'] ?? 0;
    $plan_wr->field_amount = $params['amount'] ?? 0;
    $plan_wr->field_net_cost = $params['net_cost'] ?? 0;
    $plan_wr->field_is_manual = $params['manual'] ?? 0;
    $plan_wr->save();
  } catch (Exception $e) {
    $transaction->rollback();
    watchdog_exception('database', $e);
  }

  return $plan ?? false;
}

/**
 * Создать Запись таблицы Отгрузка продукции
 */
function dash_ship_create($params)
{
  $transaction = db_transaction();
  try {
    $ship = entity_create('ship', [
      'type' => 'ship',
      'created' => $params['created'],
    ]);
    entity_save('ship', $ship);

    $ship_wr = entity_metadata_wrapper('ship', $ship);
    $ship_wr->field_s_company = $params['company_id'];
    $ship_wr->field_s_type = $params['type'];
    $ship_wr->field_s_date = $params['month_ts'];
    $ship_wr->field_s_quantity = $params['qty'] ?? 0;
    $ship_wr->field_s_amount = $params['amount'] ?? 0;
    $ship_wr->field_s_is_manual = $params['manual'] ?? 0;
    $ship_wr->field_s_net_cost = $params['net_cost'] ?? 0;
    $ship_wr->field_s_nomenklatura = $params['nom_id'] ?? 0;
    $ship_wr->field_s_client = $params['client_id'] ?? 0;
    $ship_wr->save();
  } catch (Exception $e) {
    $transaction->rollback();
    watchdog_exception('database', $e);
  }

  return $ship ?? false;
}

/**
 * Создать Запись таблицы Отгрузка продукции
 */
function dash_debt_create($params)
{
  $transaction = db_transaction();
  try {
    $debt = entity_create('debt', [
      'type' => 'debt',
      'created' => $params['created'],
    ]);
    entity_save('debt', $debt);

    $debt_wr = entity_metadata_wrapper('debt', $debt);
    $debt_wr->field_d_company = $params['company_id'];
    $debt_wr->field_d_date = $params['month_ts'];
    $debt_wr->field_d_type = $params['type'];
    $debt_wr->field_d_kind = $params['kind'];
    $debt_wr->field_d_category = $params['category'] ?? 1;
    $debt_wr->field_d_name = $params['name'] ?? '';
    $debt_wr->field_d_amount = $params['amount'];
    $debt_wr->field_d_amount2 = $params['amount2'] ?? 0;
    $debt_wr->field_d_is_manual = $params['manual'];
    $debt_wr->field_d_source = $params['source'];
    $debt_wr->save();
  } catch (Exception $e) {
    $transaction->rollback();
    watchdog_exception('database', $e);
  }

  return $debt ?? false;
}

/**
 * Создать Остатков готовой продукции и сырья
 */
function dash_remains_brief_create($params)
{
  $transaction = db_transaction();
  try {
    $remains = entity_create('remains', [
      'type' => 'remains_brief',
      'created' => $params['created'],
    ]);
    entity_save('remains', $remains);

    $remains_wr = entity_metadata_wrapper('remains', $remains);
    $remains_wr->field_rm_company = $params['company_id'];
    $remains_wr->field_rm_date = $params['month_ts'];
    $remains_wr->field_rm_category = $params['category'];
    $remains_wr->field_rm_amount = $params['amount'];
    $remains_wr->save();
  } catch (Exception $e) {
    $transaction->rollback();
    watchdog_exception('database', $e);
  }

  return $remains ?? false;
}

/**
 * Создать Остатков готовой продукции и сырья
 */
function dash_manual_bdr_create($params)
{
  $transaction = db_transaction();
  try {
    $manual = entity_create('manual', [
      'type' => 'bdr',
      'created' => $params['created'],
    ]);
    entity_save('manual', $manual);

    $manual_wr = entity_metadata_wrapper('manual', $manual);
    $manual_wr->field_m_company = $params['company_id'];
    $manual_wr->field_m_date = $params['month_ts'];
    $manual_wr->field_m_category = $params['category_id'];
    $manual_wr->field_m_type = $params['type'];
    $manual_wr->field_m_amount = $params['amount'];
    $manual_wr->save();
  } catch (Exception $e) {
    $transaction->rollback();
    watchdog_exception('database', $e);
  }

  return $manual ?? false;
}
