<?php


function dep_3_menu()
{
  $items['td/department-3'] = array(
    'title' => 'Управление 3',
    'menu_name' => 'main-menu',
    'weight' => 5,
    'page callback' => 'dep_3_page',
    'access callback' => 'ext_user_has_roles',
    'access arguments' => [[ADMIN_RID, TRADE_HOUSE_USER_RID]],
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}


function dep_3_page()
{
//  $output = '<div class="section-title">' .
//              '<h3>Какой-то заголовок</h3>' .
//              '<p>На '. date('d.m.Y') . '</p>' .
//            '</div>';

  $output =  '<div class="row">';
  $data_arr =   dep_3_line_revenue_fact_year_to_year_by_month();
  $output .=    '<div class="col-xs-12">' . drupal_render($data_arr) . '</div>';
  $output .=  '</div>';


  $output .=  '<div class="row">';
  $data_arr =   dep_3_line_revenue_fact_by_week();
  $output .=    '<div class="col-xs-12">' . drupal_render($data_arr) . '</div>';
  $output .=  '</div>';

  return '<div class="charts">' . $output . '</div>';
}

function dep_3_line_revenue_fact_year_to_year_by_month()
{
  $example['chart'] = ['#markup' => ''];

  $period_prev = dash_get_year_time_bounds(DASH_PERIOD_START_MONTH_TD, -1);
  $period_curr = dash_get_year_time_bounds(DASH_PERIOD_START_MONTH_TD);

  // собрать все записи за период
  $fact_prev = dash_get_revenue_plan_fact_by_conditions(['type' => DASH_TYPE_FACT, 'period' => $period_prev]);
  $fact_curr = dash_get_revenue_plan_fact_by_conditions(['type' => DASH_TYPE_FACT, 'period' => $period_curr]);

  // сгруппировать помесячно
  $facts_by_month = [];
  $fact_prev_today_amount = 0;  // накопительная сумма на текущую дату в прошлом периоде
  $fact_curr_today_amount = 0;  // накопительная сумма на текущую дату в текущем периоде
  foreach (dash_get_months_list($period_prev) as $month) {
    $month_num = date('n', $month['start']);
    $facts_by_month[$month_num]['prev'] = [
      'amount' => 0,
      'start' => $month['start'],
      'end' => $month['end'],
    ];

    foreach ($fact_prev as $record) {
      if ($record->date >= $month['start'] && $record->date < $month['end']) {
        $facts_by_month[$month_num]['prev']['amount'] += $record->amount;
        if ($record->date <= REQUEST_TIME) {
          $fact_prev_today_amount += $record->amount;
        }
      }
    }
  }
  foreach (dash_get_months_list($period_curr) as $month) {
    $month_num = date('n', $month['start']);
    $facts_by_month[$month_num]['curr'] = [
      'amount' => 0,
      'start' => $month['start'],
      'end' => $month['end'],
    ];
    foreach ($fact_curr as $record) {
      if ($record->date >= $month['start'] && $record->date < $month['end']) {
        $facts_by_month[$month_num]['curr']['amount'] += $record->amount;
        if ($record->date <= REQUEST_TIME) {
          $fact_curr_today_amount += $record->amount;
        }
      }
    }
  }

  $chart = array(
    '#type' => 'chart',
    '#chart_type' => 'line',
    '#title' => 'Поступление денежных средств, год к году (' . DASH_REV_SUFFIX . ')',
    '#height' => '350',
    '#colors' => ['#aaa', DASH_COLOR_BLUE],
    '#legend_position' => 'bottom',
    '#raw_options' => [
      'titleTextStyle' => ['bold' => 'true', 'fontName' => '<global-font-name>', 'fontSize' => '16'],
      'crosshair' => ['trigger' => 'both', 'orientation' => 'vertical'],
      'legend' => [ 'position' => 'top'],
      'annotations' => [
        'datum' => ['stem' => ['color' => '#ccc', 'length' => 40]],
      ],
      'chartArea' => [
        'width' => '95%',
        'left' => 70,
      ],
      'tooltip' => ['isHtml' => true],
    ],
    'xaxis' => [
      '#type' => 'chart_xaxis',
      '#raw_options' => ['textStyle' => ['fontName' => '<global-font-name>']]
    ],
    'yaxis' => [
      '#type' => 'chart_yaxis',
      '#min' => 0,
      '#raw_options' => ['textStyle' => ['fontName' => '<global-font-name>']]
    ],
    'fact_prev' => [
      '#type' => 'chart_data',
      '#title' => 'Предыдущий',
      '#data' => [],
    ],
    'fact_curr' => [
      '#type' => 'chart_data',
      '#title' => 'Текущий',
      '#data' => [],
    ],
  );

  $no_data = true;
  $total_fact_prev = $total_fact_curr = 0;
  foreach ($facts_by_month as $month) {
    $chart['xaxis']['#labels'][] = dash_month_label_ru(date('n', $month['curr']['start']));

    $fact_prev_amount = $month['prev']['amount'];
    $fact_curr_amount = $month['curr']['amount'];
    $total_fact_prev += $fact_prev_amount;
    $total_fact_curr += $fact_curr_amount;
    $total_fact_curr = (date('Y', $month['curr']['start']) != date('Y')) || (date('n', $month['curr']['start']) < date('n')) ? $total_fact_curr : null;

    if ($fact_prev_amount || $fact_curr_amount) $no_data = false;

    $chart['fact_prev']['#data'][] = $total_fact_prev/DASH_REV_DIVIDER;

    $chart['fact_curr']['#data'][] = $total_fact_curr/DASH_REV_DIVIDER;
    if ($total_fact_curr) {
      $delta = $total_fact_prev ? (int)($total_fact_curr/$total_fact_prev*100-100) : 0;
      $ratio = ($total_fact_curr > $total_fact_prev ? ' +' : ' ') . number_format($delta, 0, null, ' ') . '%';

      $tooltip = '<div style="font-family: sans-serif; padding: 8px 12px; min-width:140px;white-space: nowrap;">' .
                   '<div><div style="display:inline-block; width: 100px;">Выручка:</div><div style="display:inline-block; text-align: right; width: 100px;"><b>' . number_format($total_fact_curr, 0, ',', ' ') . '</b> руб.</div></div>' .
                  '</div>';

      $chart['fact_curr'][] = array(
        '#type' => 'chart_data_item',
        '#title' => $tooltip,
        '#raw_options' => [
          'annotation' => $delta ? $ratio : null,
        ],
      );
    }

    $tooltip =  '<div style="font-family: sans-serif; padding: 8px 12px; min-width:140px;white-space: nowrap;">' .
                  '<div><div style="display:inline-block; width: 100px;">Выручка:</div><div style="display:inline-block; text-align: right; width: 100px;"><b>' . number_format($total_fact_prev, 0, ',', ' ') . '</b> руб.</div></div>' .
                '</div>';

    $chart['fact_prev'][] = [
      '#type' => 'chart_data_item',
      '#title' => $tooltip,
    ];


    // для текущего периода вставить текущую дату
    if ($period_curr['from'] <= REQUEST_TIME && REQUEST_TIME < $period_curr['to'] && date('n', $month['curr']['start']) == date('n')) {
      $fact_prev_today_amount = $fact_prev_today_amount/DASH_REV_DIVIDER;
      $fact_curr_today_amount = $fact_curr_today_amount/DASH_REV_DIVIDER;

      $pos = count($chart['fact_prev']['#data'])-1;

      // вычислить значение плана на текущую дату пропорционально кол-ву дней в месяце
      $prev_amount_p = $chart['fact_prev']['#data'][$pos-1];
      $next_amount_p = $chart['fact_prev']['#data'][$pos];
      $curr_month_days = date('t');
      $day = date('d');
      $curr_amount_p = $prev_amount_p + ($next_amount_p - $prev_amount_p)*($day/$curr_month_days);

      // вставляем перед текущим месяцем
      array_splice($chart['xaxis']['#labels'], $pos, 0, date('d.m'));
      array_splice($chart['fact_prev']['#data'], $pos, 0, $curr_amount_p);
      array_splice($chart['fact_curr']['#data'], $pos, 0, $fact_curr_today_amount);

      if ($fact_prev_today_amount || $fact_curr_today_amount) $no_data = false;

      $pos = count($chart['fact_curr'])-1;

      $delta = $curr_amount_p ? (int)($fact_curr_today_amount/$curr_amount_p*100-100) : '0';
      $ratio = $delta ? (($fact_curr_today_amount > $fact_prev_today_amount ? ' +' : ' ') . number_format($delta, 0, null, ' ') . '%') : number_format($fact_curr_today_amount, 1, null, ' ');

      $tooltip =  '<div style="font-family: sans-serif; padding: 8px 12px; min-width:140px;white-space: nowrap;">' .
                    '<div><div style="display:inline-block; width: 100px;">Выручка:</div><div style="display:inline-block; text-align: right; width: 100px;"><b>' . number_format($fact_curr_today_amount, 0, ',', ' ') . '</b> млн руб.</div></div>' .
                  '</div>';

      array_splice($chart['fact_curr'], $pos, 0, [
        ['#type' => 'chart_data_item',
          '#title' => $tooltip,
          '#raw_options' => [
            'annotation' => $ratio,
          ]
        ]]);
      $tooltip =  '<div style="font-family: sans-serif; padding: 8px 12px; min-width:140px;white-space: nowrap;">' .
                    '<div><div style="display:inline-block; width: 100px;">Выручка:</div><div style="display:inline-block; text-align: right; width: 100px;"><b>' . number_format($curr_amount_p, 0, ',', ' ') . '</b> млн руб.</div></div>' .
                  '</div>';

      array_splice($chart['fact_prev'], $pos, 0, [
        ['#type' => 'chart_data_item',
          '#title' => $tooltip,
        ]]);
    }
  }

  if (!$no_data) {
    $example['chart'] = $chart;
  }

  return $example;
}

/**
 * Вывести линейный график выручки по неделям
 *
 */
function dep_3_line_revenue_fact_by_week()
{
  $period = dash_get_year_time_bounds(DASH_PERIOD_START_MONTH_TD);
  $fact = dash_get_revenue_plan_fact_by_conditions(['type' => DASH_TYPE_FACT, 'period' => $period]);

  // сгруппировать понедельно
  $fact_by_week = [];
  foreach (dash_get_weeks_list($period) as $week) {
    $fact_by_week[$week['start']] = [
      'amount' => 0,
      'start' => $week['start'],
      'end' => $week['end'],
    ];

    foreach ($fact as $record) {
      if ($record->date >= $week['start'] && $record->date < $week['end']) {
        $fact_by_week[$week['start']]['amount'] += $record->amount;
      }
    }
  }

  ksort($fact_by_week);

  $chart = array(
    '#type' => 'chart',
    '#title' => 'Поступление денежных средств по неделям (' . DASH_REV_SUFFIX . ')',
    '#chart_type' => 'line',
    '#colors' => [DASH_COLOR_BLUE],
    '#height' => '500',
    'xaxis' => [
      '#type' => 'chart_xaxis',
      '#raw_options' => [
        'textStyle' => ['fontName' => '<global-font-name>'],
      ]
    ],
    'yaxis' => [
      '#type' => 'chart_yaxis',
      '#min' => 0,
    ],
    '#raw_options' => [
      'titleTextStyle' => ['bold' => 'true', 'fontName' => '<global-font-name>', 'fontSize' => '16'],
      'legend' => ['position' => 'top', 'textStyle' => ['fontSize' => '12', 'fontName' => '<global-font-name>']],
      'chartArea' => [
        'height' => '80%',
        'width' => '95%',
        'left' => 70,
      ],
      'tooltip' => ['isHtml' => true],
    ],
    // прибыль по неделям
    'fact' => [
      '#type' => 'chart_data',
      '#title' => 'Поступления за неделю',
      '#data' => [],
    ],
  );

  foreach ($fact_by_week as $week) {
    $label = date('d.m', $week['start']) . '-' . date('d.m', $week['end']-1);
    $amount = $week['amount'] / DASH_REV_DIVIDER;

    $chart['xaxis']['#labels'][] = $label;
    $chart['fact']['#data'][] = $amount;
    if ($week['amount']) {
      $tooltip =  '<div style="font-family: sans-serif; padding: 8px 12px; min-width:140px;white-space: nowrap;">' .
        '<div><div style="display:inline-block; width: 160px;">Выручка за неделю:</div><div style="display:inline-block; text-align: right; width: 100px;"><b>' . number_format($week['amount'], 0, ',', ' ') . '</b> руб.</div></div>' .
        '</div>';
      $chart['fact'][] = [
        '#type' => 'chart_data_item',
        '#title' => $tooltip,
      ];

    }
  }

  return $chart;
}
