<?php

/**
 * Implementation of hook_menu().
 */
function dep_2v_2g_menu()
{
  $items['td/department-2v-2g'] = array(
    'title' => 'Управления 2В и 2Г',
    'menu_name' => 'main-menu',
    'weight' => 2,
    'page callback' => 'dep_2v_2g_current_page',
    'access callback' => 'ext_user_has_roles',
    'access arguments' => [[ADMIN_RID, TRADE_HOUSE_USER_RID]],
    'type' => MENU_NORMAL_ITEM,
  );
  $items['td/department-2v-2g/current'] = array(
    'title' => 'Текущий период',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 10,
  );
  $items['td/department-2v-2g/closed'] = array(
    'title' => 'Завершившийся период',
    'page callback' => 'dep_2v_2g_current_page',
    'page arguments' => [true],
    'access callback' => 'ext_user_has_roles',
    'access arguments' => [[ADMIN_RID, TRADE_HOUSE_USER_RID]],
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );
  $items['td/department-2v-2g/previous'] = array(
    'title' => 'Предыдущий период',
    'page callback' => 'dep_2v_2g_previous_page',
    'access callback' => 'ext_user_has_roles',
    'access arguments' => [[ADMIN_RID, TRADE_HOUSE_USER_RID]],
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
  );

  return $items;
}

/**
 * hook_import_processors_alter
 */
function dep_2v_2g_import_processors_alter(&$processors)
{
//  $path = drupal_get_path('module', 'dep_2v_2g') . '/includes/';
  //$processors['first_queue'][] = ['mask' => '/^scrum_td_storage.*\.json/', 'include' => $path . 'import.dep_2v_2g.inc', 'func' => 'dep_2v_2g_import_storages'];
  //$processors['last_queue'][] = ['mask' => '/^scrum_td_remains.*\.json/', 'include' => $path . 'import.dep_2v_2g.inc', 'func' => 'dep_2v_2g_import_remains'];
}

/**
 * ----- Страницы ------------------------------------------------------------------------------------------------------
 */

function dep_2v_2g_current_page()
{
  // страница разбита на сектора, загружаемые через ajax,
  // так как формирование всей страницы целиком занимает продолжительное время

  $period = dash_get_page_time_bounds(DASH_PERIOD_START_MONTH_TD);

  $time_yesterday = gmmktime(0, 0, 0, date('n', $period['to']), date('j', $period['to'])-1, date('Y', $period['to']));
  $output = '<div class="section-title">' .
    '<h3>Отгрузка</h3>' .
    '<p>Сезон к сезону за период с ' . date('d', $period['from']) . '.' . date('m', $period['from']) . ' по ' . date('d', $time_yesterday) . '.' . date('m', $time_yesterday) . '</p>' .
    '</div>';

  $output .= '<div class="ajax-load" data-func="row_1"><div class="ajax-progress ajax-progress-throbber"><div class="throbber">&nbsp;</div><div class="message">Пожалуйста, подождите...</div></div></div>';

  $output .= '<div class="row">';
  $output .=   '<div class="col-xs-12"><h5 class="chart-title">Суммарная отгрузка (шт/л/кг)</h5></div>';
  $form =      drupal_get_form('dep_2v_2g_td_column_plan_ship_period_to_period_filter_form');
  $output .=   '<div class="col-xs-12 col-md-4">' . drupal_render($form) . '</div>';
  $output .= '</div>';
  $output .= '<div class="ajax-load" data-func="row_2" data-delay="100"><div class="ajax-progress ajax-progress-throbber"><div class="throbber">&nbsp;</div><div class="message">Пожалуйста, подождите...</div></div></div>';

  $output .= '<div class="row">';
  $output .=    '<div class="col-xs-12"><h5 class="chart-title">Отгрузка по номенклатуре (' . DASH_REV_SUFFIX . ')</h5></div>';
  $form =       drupal_get_form('dep_2v_2g_column_ship_plan_by_nom_filter_form');
  $output .=    '<div class="col-xs-12 col-md-4">' . drupal_render($form) . '</div>';
  $output .= '</div>';
  $output .= '<div class="ajax-load" data-func="row_3" data-delay="500"><div class="ajax-progress ajax-progress-throbber"><div class="throbber">&nbsp;</div><div class="message">Пожалуйста, подождите...</div></div></div>';

  $output .= '<div class="row">';
  $output .=    '<div class="col-xs-12"><h5 class="chart-title">Выполнение плана отгрузки по номенклатуре (шт/л/кг)</h5></div>';
  $form =       drupal_get_form('dep_2v_2g_ship_plan_nom_filter_form');
  $output .=    '<div class="col-xs-12 col-md-4">' . drupal_render($form) . '</div>';
  $output .= '</div>';
  $output .= '<div class="ajax-load" data-func="row_4" data-delay="700"><div class="ajax-progress ajax-progress-throbber"><div class="throbber">&nbsp;</div><div class="message">Пожалуйста, подождите...</div></div></div>';


  $output .=  '<div class="section-title">' .
    '<h3>Планы</h3>' .
    '<p>Сезон ' . date('Y', $period['from']) . '-' . date('Y', $period['to']) . '</p>' .
    '</div>';

  $output .= '<div class="ajax-load" data-func="row_5" data-delay="2000"><div class="ajax-progress ajax-progress-throbber"><div class="throbber">&nbsp;</div><div class="message">Пожалуйста, подождите...</div></div></div>';

  // план-факт линейные
  $output .= '<div class="row">';
  $output .=    '<div class="col-xs-12"><h5 class="chart-title">Выполнение плана отгрузки (' . DASH_REV_SUFFIX . ')</h5></div>';
  $form =       drupal_get_form('dep_2v_2g_line_ship_plan_fact_by_month_filter_form');
  $output .=    '<div class="col-xs-12 col-md-4">' . drupal_render($form) . '</div>';
  $output .= '</div>';
  $output .= '<div class="ajax-load" data-func="row_6" data-delay="3000"><div class="ajax-progress ajax-progress-throbber"><div class="throbber">&nbsp;</div><div class="message">Пожалуйста, подождите...</div></div></div>';

  // отгрузка по регионам
  $output .= '<div class="row">';
  $output .=    '<div class="col-xs-12"><h5 class="chart-title">Выполнение плана отгрузки (' . DASH_REV_SUFFIX . ')</h5></div>';
  $form =       drupal_get_form('dep_2v_2g_ship_plan_region_filter_form');
  $output .=    '<div class="col-xs-12 col-md-4">' . drupal_render($form) . '</div>';
  $output .= '</div>';
  $output .= '<div class="ajax-load" data-func="row_7" data-delay="4000"><div class="ajax-progress ajax-progress-throbber"><div class="throbber">&nbsp;</div><div class="message">Пожалуйста, подождите...</div></div></div>';


  return '<div class="charts" data-module="dep_2v_2g" data-period-from="' . $period['from'] . '" data-period-to="' . $period['to'] . '">' . $output . '</div>';
}

function dep_2v_2g_row_1($period = null)
{
  $period = $period ?? ['from' => $_GET['period_from'], 'to' => $_GET['period_to']];

  $output  = '<div class="row">';
  $data_arr =   dash_column_revenue_period_to_period('td', $period['from'], $period['to']);
  $data_arr['#title'] = 'Суммарная отгрузка за сезон по данным бухгалтерии (' . DASH_REV_SUFFIX . ')';
  $output .=    '<div class="col-xs-12 col-md-6">' . drupal_render($data_arr) . '</div>';

  $data_arr =   dash_pie_revenue_year('td', $period['from'], $period['to']);
  $output .=    '<div class="col-xs-12 col-md-6">' . drupal_render($data_arr) . '</div>';
  $output .= '</div>';

  return $output;
}

function dep_2v_2g_row_2($period = null)
{
  $period = $period ?? ['from' => $_GET['period_from'], 'to' => $_GET['period_to']];

  // отчёт в литрах
  $output = '<div class="row">';
  $data_arr =   dep_2v_2g_td_column_plan_ship_period_to_period($period, 'qty');
  $data_arr['#title'] = '';
  $output .=    '<div id="summary-target" class="col-xs-12 col-md-6">' . drupal_render($data_arr) . '</div>';
  $output .= '</div>';

  return $output;
}

function dep_2v_2g_row_3($period = null)
{
  $period = $period ?? ['from' => $_GET['period_from'], 'to' => $_GET['period_to']];

  // выручка по номенклатуре
  $output = '<div class="row">';
  $data_arr =   dep_2v_2g_column_ship_plan_by_nom($period);
  $output .=    '<div id="nom-r-target" class="col-xs-12">' . drupal_render($data_arr) . '</div>';
  $output .= '</div>';

  return $output;
}

function dep_2v_2g_row_4($period = null)
{
  $period = $period ?? ['from' => $_GET['period_from'], 'to' => $_GET['period_to']];

  // валовая прибыль, понедельно, из факта
  $output = '<div class="row">';
  $data_arr =   dep_2v_2g_column_ship_fact_gross_profit_by_week($period);
  $output .=    '<div class="col-xs-12 col-md-12">' . drupal_render($data_arr) . '</div>';
  $output .= '</div>';

  return $output;
}

function dep_2v_2g_row_5($period = null)
{
  $period = $period ?? ['from' => $_GET['period_from'], 'to' => $_GET['period_to']];

  // план-факт отгрузки по номенклатуре в литрах
  $output = '<div class="row">';
  $nom = empty($_GET['nom']) ? 0 : $_GET['nom'];
  $data_arr =   dep_2v_2g_column_ship_plan_fact_by_nom_single($period, $nom);
  $output .=    '<div id="nom-target" class="col-xs-12 col-md-4">' . drupal_render($data_arr) . '</div>';

  $options = ['range' => [0,7]];
  $data_arr =   dep_2v_2g_column_ship_plan_fact_by_nom($period, $options);
  $output .=    '<div class="col-xs-12 col-md-8">' . drupal_render($data_arr) . '</div>';
  $output .= '</div>';

  $output .= '<div class="row">';
  $options = ['range' => [8, 30]];
  $data_arr =   dep_2v_2g_column_ship_plan_fact_by_nom($period, $options);
  $output .=    '<div class="col-xs-12">' . drupal_render($data_arr) . '</div>';
  $output .= '</div>';

  return $output;
}

function dep_2v_2g_row_6($period = null)
{
  $period = $period ?? ['from' => $_GET['period_from'], 'to' => $_GET['period_to']];

  // план-факт по отгрузкам помесячно линейный с подсветкой текущего значения к предыдущему на дату
  $output = '<div class="row">';
  $data_arr =   dep_2v_2g_line_ship_plan_fact_by_month($period);
  $output .=    '<div id="plan-target" class="col-xs-12">' . drupal_render($data_arr) . '</div>';
  $output .= '</div>';

  // план-факт выручки помесячно линейный с подсветкой текущего значения к предыдущему на дату
  // фильтр по регионам невозможен, тк в плане нет детализации по клиентам
  $output .= '<div class="row">';
  $data_arr =   dep_2v_2g_line_revenue_plan_fact('plan_revenue', $period);
  $output .=    '<div id="plan-m-target" class="col-xs-12">' . drupal_render($data_arr) . '</div>';
  $output .= '</div>';

  return $output;
}

function dep_2v_2g_row_7($period = null)
{
  $period = $period ?? ['from' => $_GET['period_from'], 'to' => $_GET['period_to']];

  // отгрузка по регионам
  $output = '<div class="row">';
  $region = empty($_GET['region']) ? 0 : $_GET['region'];
  $data_arr =   dep_2v_2g_bar_ship_plan_fact_by_region_single($period, $region);
  $output .=    '<div id="region-target" class="col-xs-12">' . drupal_render($data_arr) . '</div>';
  $data_arr =   dep_2v_2g_bar_ship_plan_fact_by_region($period, ['regions' => ['list' => [657]]]); // ЦО
  $output .=    '<div class="col-xs-12">' . drupal_render($data_arr) . '</div>';

  $data_arr =   dep_2v_2g_bar_ship_plan_fact_by_region($period, ['regions' => ['exclude' => [657]]]);
  $output .=    '<div class="col-xs-12">' . drupal_render($data_arr) . '</div>';
  $output .= '</div>';

  return $output;
}


function dep_2v_2g_previous_page()
{
  $period = dash_get_period_time_bounds(DASH_PERIOD_START_MONTH_TD, -1);

  $output = '<div class="section-title">' .
    '<h3>Отгрузка</h3>' .
    '<p>Сезоны ' . DASH_HISTORY_START_YEAR_TD . '-' . date('Y', $period['from']) . '</p>' .
    '</div>';

  $output .= '<div class="row">';
  $data_arr =   dash_column_revenue_period_to_period('td', $period['from'], $period['to']);
  $output .=    '<div class="col-xs-12 col-md-6">' . drupal_render($data_arr) . '</div>';

  $data_arr =   dash_pie_revenue_year('td', $period['from'], $period['to']);
  $output .=    '<div class="col-xs-12 col-md-6">' . drupal_render($data_arr) . '</div>';

  $data_arr =   dash_column_revenue_by_types('td', $period['from'], $period['to']);
  $output .=    '<div class="col-xs-12 col-md-6">' . drupal_render($data_arr) . '</div>';

//  $data_arr =   dep_2v_2g_pie_revenue_pay_plan($period['from'], $period['to']);
//  $output .=    '<div class="col-xs-12 col-md-6">' . drupal_render($data_arr) . '</div>';
  $output .= '</div>';

  // выручка по номенклатуре
  $output .= '<div class="row">';
  $data_arr =   dep_2v_2g_column_ship_plan_by_nom($period);
  $output .=    '<div class="col-xs-12"><h5 class="chart-title">Отгрузка по номенклатуре за прошлый период (' . DASH_REV_SUFFIX . ')</h5></div>';
  $output .=    '<div class="col-xs-12">' . drupal_render($data_arr) . '</div>';
  $output .= '</div>';

  $output .=  '<div class="section-title">' .
    '<h3>Планы</h3>' .
    '<p>Сезон ' . date('Y', $period['from']) . '-' . date('Y', $period['to']) . '</p>' .
    '</div>';

  $output .= '<div class="row">';

  // план-факт по отгрузкам
  $data_arr =   dep_2v_2g_line_revenue_plan_fact('plan_ship', $period);
  $output .=    '<div class="col-xs-12">' . drupal_render($data_arr) . '</div>';

  // план-факт выручки
  $data_arr =   dep_2v_2g_line_revenue_plan_fact('plan_revenue', $period);
  $output .=    '<div class="col-xs-12">' . drupal_render($data_arr) . '</div>';
  $output .= '</div>';

  return '<div class="charts">' . $output . '</div>';
}


/**
 * ----- Графики -------------------------------------------------------------------------------------------------------
 */

/**
 * Сравнение выручки период к периоду
 * Внутри года суммируются данные за заданный период включительно
 * @param $period - текущий период
 * @param $field - 'amount'/'qty', выводить сумму или количество
 */
function dep_2v_2g_td_column_plan_ship_period_to_period($period, $field, $regions = [])
{
  $data = [];

  // собираем
  $time_to = REQUEST_TIME;

  // собрать данные периодов с DASH_YEAR_HISTORY_START года
  $years_shift = date('Y', $period['from']) - DASH_HISTORY_START_YEAR_TD;
  $years_shift = abs($years_shift)+1 > DASH_HISTORY_LENGTH ? DASH_HISTORY_LENGTH : $years_shift;
  do {
    $time_start = gmmktime(0, 0, 0,  date('n', $period['from'])-12*$years_shift, date('j', $period['from']), date('Y', $period['from']));
    $time_end = gmmktime(0, 0, 0,  date('n', $time_to)-12*$years_shift, date('j', $time_to), date('Y', $time_to));

    $fact = dash_get_ship_plan_fact_by_conditions(['type' => DASH_TYPE_FACT, 'period' => ['from' => $time_start, 'to' => $time_end], 'regions' => $regions]);

    $sum = 0;
    foreach($fact as $record) {
      $sum += $field == 'qty' ? $record->qty : $record->amount;
    }

    $data[date('Y', $time_start)] = [
      'time_start' => $time_start,
      'time_end' => $time_end,
      'sum' => $sum
    ];

    $years_shift--;
  } while ($years_shift >= 0);

  $chart = array(
    '#type' => 'chart',
    '#chart_type' => 'column',
    '#title' => 'Суммарная отгрузка (' . DASH_REV_SUFFIX . ')',
    '#height' => '350',
    '#colors' => ($field == 'qty' ? [DASH_COLOR_DARK_RED, DASH_COLOR_PURPLE, DASH_COLOR_ORANGE] : []),
    '#data_labels' => TRUE,
    '#legend_position' => 'bottom',
    'yaxis' => [
      '#type' => 'chart_yaxis',
      '#min' => 0,
    ],
    '#raw_options' => [
      'titleTextStyle' => ['bold' => 'true', 'fontName' => '<global-font-name>', 'fontSize' => '16'],
      'chartArea' => [
        'height' => '90%',
        'width' => '85%',
        'left' => 80,
      ],
    ],
  );

  $year_prev = null;
  foreach ($data as $year => $item) {
    $chart[$year] = [
      '#type' => 'chart_data',
      '#title' => (string)(date('Y', $period['from']) == date('Y', $time_to-1) ? $year : date('Y', $item['time_start']) . '-' . date('y', $item['time_end'])),
      '#data' => [$item['sum']],
    ];
    $delta = 0;
    if ($year_prev && $data[$year_prev] && $data[$year_prev]['sum']) {
      $delta = ($item['sum'] > $data[$year_prev]['sum'] ? '+' : '') . number_format(($item['sum']/$data[$year_prev]['sum']*100)-100, 0, null, ' ') . '%';
    }
    $chart[$year][0] = [
      '#type' => 'chart_data_item',
      '#raw_options' => [
        'annotation' => number_format($item['sum'], 0, '', ' ') . ($delta ? ' (' . $delta . ')' : ''),
      ],
    ];
    $year_prev = $year;
  }

  return $chart;
}

// выполнение плана по отгрузкам за период (это обновлённый dep_2v_2g_line_revenue_plan_fact)
function dep_2v_2g_line_ship_plan_fact_by_month($period, $regions = [])
{
  $chart = dash_get_no_data_chart();

  // собрать все записи за период
  $plan = dash_get_ship_plan_fact_by_conditions(['type' => DASH_TYPE_PLAN, 'period' => $period, 'regions' => $regions]);
  $fact = dash_get_ship_plan_fact_by_conditions(['type' => DASH_TYPE_FACT, 'period' => $period, 'regions' => $regions]);

  if ($plan || $fact) {
    // сгруппировать помесячно
    $plan_fact_by_month = [];
    $plan_amount_current = 0;
    $fact_amount_current = 0;
    foreach (dash_get_months_list($period) as $month) {
      $plan_fact_by_month[$month['start']] = [
        'plan_amount' => 0,
        'fact_amount' => 0,
        'start' => $month['start'],
        'end' => $month['end'],
      ];

      foreach ($plan as $record) {
        if ($record->date >= $month['start'] && $record->date < $month['end']) {
          $plan_fact_by_month[$month['start']]['plan_amount'] += $record->amount;
          if ($record->date <= REQUEST_TIME) {
            $plan_amount_current += $record->amount;
          }
        }
      }
      foreach ($fact as $record) {
        if ($record->date >= $month['start'] && $record->date < $month['end']) {
          $plan_fact_by_month[$month['start']]['fact_amount'] += $record->amount;
          if ($record->date <= REQUEST_TIME) {
            $fact_amount_current += $record->amount;
          }
        }
      }
    }
    ksort($plan_fact_by_month);

    $chart = array(
      '#type' => 'chart',
      '#chart_type' => 'line',
      '#height' => '350',
      '#colors' => ['#aaa', DASH_COLOR_BLUE],
      '#legend_position' => 'bottom',
      '#raw_options' => [
        'titleTextStyle' => ['bold' => 'true', 'fontName' => '<global-font-name>', 'fontSize' => '16'],
        'crosshair' => ['trigger' => 'both', 'orientation' => 'vertical'],
        'legend' => [ 'position' => 'top'],
        'annotations' => [
          'datum' => ['stem' => ['color' => '#ccc', 'length' => 40]],
        ],
        'chartArea' => [
          'height' => '90%',
          'width' => '85%',
          'left' => 50,
        ],
      ],
      'xaxis' => [
        '#type' => 'chart_xaxis',
        '#raw_options' => ['textStyle' => ['fontName' => '<global-font-name>']]
      ],
      'yaxis' => [
        '#type' => 'chart_yaxis',
        '#min' => 0,
        '#raw_options' => ['textStyle' => ['fontName' => '<global-font-name>']]
      ],
      'plan' => [
        '#type' => 'chart_data',
        '#title' => 'План',
        '#data' => [],
      ],
      'fact' => [
        '#type' => 'chart_data',
        '#title' => 'Факт',
        '#data' => [],
      ],
    );


    $total_plan = $total_fact = 0;
    foreach ($plan_fact_by_month as $month) {
      $chart['xaxis']['#labels'][] = _month_label_ru(date('n', $month['start']));

      $plan = $month['plan_amount'] / DASH_REV_DIVIDER;
      $fact = $month['fact_amount'] / DASH_REV_DIVIDER;
      $total_plan += $plan;
      $total_fact += $fact;
      $total_fact = (date('Y', $month['start']) != date('Y')) || (date('n', $month['start']) < date('n')) ? $total_fact : null;

      if ($plan || $fact) $no_data = false;

      $chart['plan']['#data'][] = $total_plan;
      $chart['fact']['#data'][] = $total_fact;

      $delta = $total_plan ? (int)($total_fact/$total_plan*100-100) : 0;
      $ratio = ($total_fact > $total_plan ? ' +' : ' ') . number_format($delta, 0, null, ' ') . '%';

      $chart['fact'][] = array(
        '#type' => 'chart_data_item',
        '#raw_options' => [
          'annotation' => $delta ? $ratio : null,
        ],
      );

      // для текущего периода вставить текущую дату
      if ($period['from'] <= REQUEST_TIME && REQUEST_TIME < $period['to'] && date('n', $month['start']) == date('n')) {
        $plan_amount_current = $plan_amount_current/DASH_REV_DIVIDER;
        $fact_amount_current = $fact_amount_current/DASH_REV_DIVIDER;

        $pos = count($chart['plan']['#data'])-1;

        // вычислить значение плана на текущую дату пропорционально кол-ву дней в месяце
        $prev_amount_p = $chart['plan']['#data'][$pos-1];
        $next_amount_p = $chart['plan']['#data'][$pos];
        $curr_month_days = date('t');
        $day = date('d');
        $curr_amount_p = $prev_amount_p + ($next_amount_p - $prev_amount_p)*($day/$curr_month_days);

        // вставляем перед текущим месяцем
        array_splice($chart['xaxis']['#labels'], $pos, 0, date('d.m'));
        array_splice($chart['plan']['#data'], $pos, 0, $curr_amount_p);
        array_splice($chart['fact']['#data'], $pos, 0, $fact_amount_current);

        if ($plan_amount_current || $fact_amount_current) $no_data = false;

        $delta = $curr_amount_p ? (int)($fact_amount_current/$curr_amount_p*100-100) : '0';
        $ratio = $delta ? (($fact_amount_current > $plan_amount_current ? ' +' : ' ') . number_format($delta, 0, null, ' ') . '%') : number_format($fact_amount_current, 1, null, ' ');

        $pos = count($chart['fact'])-1;
        array_splice($chart['fact'], $pos, 0, [
          ['#type' => 'chart_data_item',
            '#raw_options' => [
              'annotation' => $ratio,
            ]
          ]]);
      }
    }
  }

  return $chart;
//  return $no_data ? ['#type' => 'markup', '#markup' => 'Нет данных'] : $chart;
}

function dep_2v_2g_line_revenue_plan_fact($type, $period, $regions = [])
{
   $data = [];

  // список месяцев, за которые выводим график
  $time_months_list = [];
  $time_month_start = $period['from'];
  while($time_month_start < $period['to']) {
    $time_months_list[] = $time_month_start;
    $time_month_start = gmmktime(0, 0, 0, date('n', $time_month_start)+1, 1, date('Y', $time_month_start));
  }

  // собираем по месяцам
  $total_p = $total_f = 0;
  foreach($time_months_list as $time_month_start) {
    $time_month_end = gmmktime(0, 0, 0, date('n', $time_month_start)+1, 1, date('Y', $time_month_start));
    $dbr = db_select('eck_plan', 'p');
    $dbr->condition('p.type', $type);

    $dbr->innerJoin('field_data_field_record_type_td', 'frt', 'frt.entity_id = p.id');
    $dbr->condition('frt.bundle', $type);

    $dbr->innerJoin('field_data_field_date', 'frd', 'frd.entity_id = p.id');
    $dbr->condition('frd.bundle', $type);
    $dbr->condition('frd.field_date_value', $time_month_start, '>=');
    $dbr->condition('frd.field_date_value', $time_month_end, '<');

    if (!empty($regions)) {
      $dbr->innerJoin('field_data_field_client_td', 'fct', 'fct.entity_id = p.id');
      $dbr->condition('fct.bundle', $type);
      $dbr->innerJoin('field_data_field_region', 'fr', 'fr.entity_id = fct.field_client_td_tid');
      $dbr->condition('fr.field_region_tid', $regions, 'IN');
    }

    $dbr->innerJoin('field_data_field_amount', 'fa', 'fa.entity_id = p.id');
    $dbr->condition('fa.bundle', $type);
    $dbr->addExpression('SUM(fa.field_amount_value)', 'amount');

    $dbr_f = clone($dbr);
    $dbr->condition('frt.field_record_type_td_value', DASH_TYPE_PLAN);
    $dbr_f->condition('frt.field_record_type_td_value', DASH_TYPE_FACT);

    $amount_p = (int)$dbr->execute()->fetchField();
    $amount_f = (int)$dbr_f->execute()->fetchField();
    $total_p += $amount_p;
    $total_f += $amount_f;

    $data[$time_month_start] = [$total_p/DASH_REV_DIVIDER, $total_f/DASH_REV_DIVIDER];
  }

  // для текущего периода получить данные до вчера включительно
  $curr_amount_p = $curr_amount_f = 0;
  if ($period['from'] <= REQUEST_TIME && REQUEST_TIME < $period['to']) {
    $time_current_from = gmmktime(0, 0, 0, date('n', $period['from']), 1, date('Y', $period['from']));
    $time_current_to = gmmktime(0, 0, 0, date('n'), date('j'), date('Y'));
    $dbr = db_select('eck_plan', 'p');
    $dbr->condition('p.type', $type);

    $dbr->innerJoin('field_data_field_record_type_td', 'frt', 'frt.entity_id = p.id');
    $dbr->condition('frt.bundle', $type);
    $dbr->condition('frt.field_record_type_td_value', DASH_TYPE_FACT);

    $dbr->innerJoin('field_data_field_date', 'frd', 'frd.entity_id = p.id');
    $dbr->condition('frd.bundle', $type);
    $dbr->condition('frd.field_date_value', $time_current_from, '>=');
    $dbr->condition('frd.field_date_value', $time_current_to, '<=');

    if (!empty($regions)) {
      $dbr->innerJoin('field_data_field_client_td', 'fct', 'fct.entity_id = p.id');
      $dbr->condition('fct.bundle', $type);
      $dbr->innerJoin('field_data_field_region', 'fr', 'fr.entity_id = fct.field_client_td_tid');
      $dbr->condition('fr.field_region_tid', $regions, 'IN');
    }

    $dbr->innerJoin('field_data_field_amount', 'fa', 'fa.entity_id = p.id');
    $dbr->condition('fa.bundle', $type);
    $dbr->addExpression('SUM(fa.field_amount_value)', 'amount');

    $curr_amount_f = (int)$dbr->execute()->fetchField()/DASH_REV_DIVIDER;
  }

  $title = '';
  if ($type == 'plan_ship') $title = 'Выполнение плана по отгрузкам (' . DASH_REV_SUFFIX . ')';
  if ($type == 'plan_revenue') {
    $title = 'Выполнение плана поступления денежных средств (' . DASH_REV_SUFFIX . ')';
  }

  $chart = array(
    '#type' => 'chart',
    '#chart_type' => 'line',
    '#chart_id' => 'dep_2v_2g_lines_revenue_plan_fact_' . $type,
    '#title' => $title,
    '#height' => '350',
    '#colors' => ['#aaa', DASH_COLOR_BLUE],
    '#legend_position' => 'bottom',
    '#raw_options' => [
      'titleTextStyle' => ['bold' => 'true', 'fontName' => '<global-font-name>', 'fontSize' => '16'],
      'crosshair' => ['trigger' => 'both', 'orientation' => 'vertical'],
      'legend' => [ 'position' => 'top'],
      'annotations' => [
        'datum' => ['stem' => ['color' => '#ccc', 'length' => 40]],
      ],
      'chartArea' => [
        'width' => '85%',
        'left' => 50,
      ],
    ],
    'xaxis' => [
      '#type' => 'chart_xaxis',
      '#raw_options' => ['textStyle' => ['fontName' => '<global-font-name>']]
    ],
    'yaxis' => [
      '#type' => 'chart_yaxis',
      '#min' => 0,
      '#raw_options' => ['textStyle' => ['fontName' => '<global-font-name>']]
    ],
    'plan' => [
      '#type' => 'chart_data',
      '#title' => 'План',
      '#data' => [],
    ],
    'fact' => [
      '#type' => 'chart_data',
      '#title' => 'Факт',
      '#data' => [],
    ],
  );

  $no_data = true;
  foreach ($data as $month => $datum) {

    $chart['xaxis']['#labels'][] = _month_label_ru(date('n', $month));
    $plan = $datum[0];
    $fact = (date('Y', $month) != date('Y')) || (date('n', $month) < date('n')) ? $datum[1] : null;
    if ($plan || $fact) $no_data = false;
    $chart['plan']['#data'][] = $plan;
    $chart['fact']['#data'][] = $fact;

    $delta = $datum[0] ? (int)($datum[1]/$datum[0]*100-100) : 0;
    $ratio = ($datum[1] > $datum[0] ? ' +' : ' ') . number_format($delta, 0, null, ' ') . '%';

    $chart['fact'][] = array(
      '#type' => 'chart_data_item',
      '#raw_options' => [
        'annotation' => $delta ? $ratio : null,
      ],
    );

    // для текущего периода вставить текущую дату
    // вставляем перед текущим месяцем
    $pos = count($chart['plan']['#data'])-1;
    if ($pos && $period['from'] <= REQUEST_TIME && REQUEST_TIME < $period['to'] && date('n', $month) == date('n')) {

      // вычислить значение плана на текущую дату пропорционально кол-ву дней в месяце
      $prev_amount_p = $chart['plan']['#data'][$pos-1];
      $next_amount_p = $chart['plan']['#data'][$pos];
      $curr_month_days = date('t', $time_current_to);
      $day = date('d', $time_current_to);
      $curr_amount_p = $prev_amount_p + ($next_amount_p-$prev_amount_p)*($day/$curr_month_days);

      array_splice($chart['xaxis']['#labels'], $pos, 0, date('d.m', $time_current_to));
      array_splice($chart['plan']['#data'], $pos, 0, $curr_amount_p);
      array_splice($chart['fact']['#data'], $pos, 0, $curr_amount_f);

      if ($curr_amount_p || $curr_amount_f) $no_data = false;

      $delta = $curr_amount_p ? (int)($curr_amount_f/$curr_amount_p*100-100) : '0';
      $ratio = $delta ? (($curr_amount_f > $curr_amount_p ? ' +' : ' ') . number_format($delta, 0, null, ' ') . '%') : number_format($curr_amount_f, 1, null, ' ');

      $pos = count($chart['fact'])-1;
      array_splice($chart['fact'], $pos, 0, [
        ['#type' => 'chart_data_item',
          '#raw_options' => [
            'annotation' => $ratio,
          ]
        ]]);
    }
  }

  return $no_data ? ['#markup' => 'Нет данных'] : $chart;
}

function dep_2v_2g_bar_ship_plan_fact_by_region_single($period, $regions)
{
  // выбрать препараты с наибольшим планом
  $dbr = db_select('eck_plan', 'p');
  $dbr->condition('p.type', 'plan_ship');

  if ($regions) {
    $dbr->innerJoin('field_data_field_client_td', 'fct', 'fct.entity_id = p.id');
    $dbr->condition('fct.bundle', 'plan_ship');
    $dbr->innerJoin('field_data_field_region', 'fr', 'fr.entity_id = fct.field_client_td_tid');
    $dbr->condition('fr.field_region_tid', $regions, 'IN');
    $dbr->innerJoin('taxonomy_term_data', 't', 't.tid = fr.field_region_tid');
    $dbr->addField('t', 'tid');
    $dbr->addField('t', 'name');
//    $dbr->groupBy('tid');
  }

  $dbr->innerJoin('field_data_field_record_type_td', 'frt', 'frt.entity_id = p.id');
  $dbr->condition('frt.bundle', 'plan_ship');

  $dbr->innerJoin('field_data_field_date', 'frd', 'frd.entity_id = p.id');
  $dbr->condition('frd.bundle', 'plan_ship');
  $dbr->condition('frd.field_date_value', $period['from'], '>=');

  $dbr->innerJoin('field_data_field_amount', 'fra', 'fra.entity_id = p.id');
  $dbr->condition('fra.bundle', 'plan_ship');
  $dbr->addExpression('SUM(fra.field_amount_value)', 'amount');

  // для вычисления плана на текущую дату
  // запросим план по прошлый и текущий месяц
  $dbr_c1 = clone($dbr);
  $dbr_c2 = clone($dbr);
  $time_prev_month_start = gmmktime(0, 0, 0, date('n')-1, date('j'), date('Y'));
  $time_curr_month_start = gmmktime(0, 0, 0, date('n'), date('j'), date('Y'));
  $dbr_c1->condition('frt.field_record_type_td_value', DASH_TYPE_PLAN);
  $dbr_c2->condition('frt.field_record_type_td_value', DASH_TYPE_PLAN);
  $dbr_c1->condition('frd.field_date_value', $time_prev_month_start, '<');
  $dbr_c2->condition('frd.field_date_value', $time_curr_month_start, '<');

  $dbr_f = clone($dbr);
  $dbr->condition('frd.field_date_value', $period['to'], '<');

  // факт по текущую дату (почему-то за весь год факт больше)
  $time_current_to = gmmktime(0, 0, 0, date('n'), date('j'), date('Y'));
  $dbr_f->condition('frd.field_date_value', $time_current_to, '<=');

  $dbr_d = clone($dbr);
  $dbr->condition('frt.field_record_type_td_value', DASH_TYPE_PLAN);
  $dbr_f->condition('frt.field_record_type_td_value', DASH_TYPE_FACT);
  $dbr_d->condition('frt.field_record_type_td_value', DASH_TYPE_DEAL);

  $result_plan = $dbr->execute()->fetchAll();
  $result_plan_c1 = $dbr_c1->execute()->fetchAll();
  $result_plan_c2 = $dbr_c2->execute()->fetchAll();
  $result_fact = $dbr_f->execute()->fetchAll();
  $result_deal = $dbr_d->execute()->fetchAll();

  $chart = array(
    '#type' => 'chart',
    '#chart_type' => 'bar',
    '#colors' => [DASH_COLOR_BLUE, DASH_COLOR_LIGHT_BLUE, '#bbb', '#ccc'],
    'xaxis' => [
      '#type' => 'chart_xaxis',
      '#raw_options' => [
        'textStyle' => ['fontName' => '<global-font-name>'],
      ]
    ],
    'yaxis' => [
      '#type' => 'chart_yaxis',
      '#raw_options' => [
        'textStyle' => ['fontName' => '<global-font-name>'],
      ],
    ],
    '#raw_options' => [
      'titleTextStyle' => ['bold' => 'true', 'fontName' => '<global-font-name>', 'fontSize' => '16'],
      'bar' => ['groupWidth' => "100%"],
      'legend' => ['position' => 'top', 'height' => 100, 'textStyle' => ['fontSize' => '12', 'fontName' => '<global-font-name>']],
      'chartArea' => ['width' => '80%', 'left' => 100],
      'isStacked' => 'true',
      'tooltip' => ['isHtml' => true],
      'annotations' => [
        'textStyle' => ['color' => '#000'],
        'datum' => ['stem' => ['color' => '#ccc', 'length' => 20]],
      ],
    ],
    'fact' => [
      '#type' => 'chart_data',
      '#title' => 'Факт',
      '#data' => [],
    ],
    'deal' => [
      '#type' => 'chart_data',
      '#title' => 'Неотгруженные контракты',
      '#data' => [],
    ],
    'plan_curr' => [
      '#type' => 'chart_data',
      '#title' => 'Текущий план',
      '#data' => [],
    ],
    'plan' => [
      '#type' => 'chart_data',
      '#title' => 'План на сезон',
      '#data' => [],
    ],
  );

  $amount_p =  $result_plan[0]->amount/DASH_REV_DIVIDER;
  $amount_pc1 = $result_plan_c1[0]->amount/DASH_REV_DIVIDER;
  $amount_pc2 = $result_plan_c2[0]->amount/DASH_REV_DIVIDER;
  $amount_f =  $result_fact[0]->amount/DASH_REV_DIVIDER;
  $amount_d =  $result_deal[0]->amount/DASH_REV_DIVIDER;

  $curr_month_days = date('t', $time_curr_month_start);
  $day = date('d', $time_curr_month_start);

  // пространство сверху
  $chart['fact']['#data'][] = $chart['deal']['#data'][] = $chart['plan_curr']['#data'][] = $chart['plan']['#data'][] = 0; $chart['plan_curr'][] = $chart['plan'][] = $chart['fact'][] = $chart['deal'][] = ['#type' => 'chart_data_item'];

  // первая строка
  $amount_pc = $amount_pc1+($amount_pc2-$amount_pc1)*($day/$curr_month_days);
  $chart['fact']['#data'][]       = 0;
  $chart['deal']['#data'][]       = 0;
  $chart['plan_curr']['#data'][]  = $amount_pc;
  $chart['plan']['#data'][]       = $amount_p - $amount_pc;
  // вторая строка
  $chart['fact']['#data'][]       = $amount_f;
  $chart['deal']['#data'][]       = $amount_d;
  $chart['plan_curr']['#data'][]  = 0;
  $chart['plan']['#data'][]       = 0;

  $tooltip =  '<div style="font-family: sans-serif; padding: 8px 12px; min-width:140px;white-space: nowrap;">' .
    '<div><div style="display:inline-block; width: 180px;">Текущий план:</div><div style="display:inline-block; text-align: right; width: 80px;"><b>' . number_format($amount_pc, 2, ',', ' ') . '</b>&nbsp;' . DASH_REV_SUFFIX . '</div></div>' .
    '<div><div style="display:inline-block; width: 180px;">План на сезон:</div><div style="display:inline-block; text-align: right; width: 80px;"><b>' . number_format($amount_p, 2, ',', ' ') . '</b>&nbsp;' . DASH_REV_SUFFIX . '</div></div>' .
    '</div>';

  $chart['plan_curr'][] = array(
    '#type' => 'chart_data_item',
    '#title' => $tooltip,
  );
  $chart['plan'][] = array(
    '#type' => 'chart_data_item',
    '#title' => $tooltip,
  );
  $chart['fact'][] = $chart['deal'][] = ['#type' => 'chart_data_item'];

  $tooltip =  '<div style="font-family: sans-serif; padding: 8px 12px; min-width:140px;white-space: nowrap;">' .
    '<div><div style="display:inline-block; width: 180px;">Факт:</div><div style="display:inline-block; text-align: right; width: 80px;"><b>' . number_format($amount_f, 2, ',', ' ') . '</b>&nbsp;' . DASH_REV_SUFFIX . '</div></div>' .
    '<div><div style="display:inline-block; width: 180px;">Неотгруженные контракты:</div><div style="display:inline-block; text-align: right; width: 80px;"><b>' . number_format($amount_d, 2, ',', ' ') . '</b>&nbsp;' . DASH_REV_SUFFIX . '</div></div>'.
    '</div>';

  $chart['fact'][] = array(
    '#type' => 'chart_data_item',
    '#title' => $tooltip,
  );
  $chart['deal'][] = array(
    '#type' => 'chart_data_item',
    '#title' => $tooltip,
  );

  // пространство снизу
  $chart['fact']['#data'][] = $chart['deal']['#data'][] = $chart['plan_curr']['#data'][] = $chart['plan']['#data'][] = 0;

  $title = $regions ? taxonomy_term_load($regions[0])->name : 'Все регионы';
  $chart['xaxis']['#title'] = $title;

  return $chart;
}

function dep_2v_2g_bar_ship_plan_fact_by_region($period, $options = [])
{
  // сумма Отгрузки по Регионам
  $dbr = db_select('eck_plan', 'p');
  $dbr->condition('p.type', 'plan_ship');

  $dbr->innerJoin('field_data_field_client_td', 'fct', 'fct.entity_id = p.id');
  $dbr->condition('fct.bundle', 'plan_ship');
  $dbr->innerJoin('field_data_field_region', 'fr', 'fr.entity_id = fct.field_client_td_tid');
  $dbr->innerJoin('taxonomy_term_data', 't', 't.tid = fr.field_region_tid');
  if (!empty($options['regions']['list'])) {
    $dbr->condition('t.tid', $options['regions']['list'], 'IN');
  }
  if (!empty($options['regions']['exclude'])) {
    $dbr->condition('t.tid', $options['regions']['exclude'], 'NOT IN');
  }
  $dbr->addField('t', 'tid');
  $dbr->addField('t', 'name');
  $dbr->groupBy('tid');

  $dbr->innerJoin('field_data_field_record_type_td', 'frt', 'frt.entity_id = p.id');
  $dbr->condition('frt.bundle', 'plan_ship');

  $dbr->innerJoin('field_data_field_date', 'frd', 'frd.entity_id = p.id');
  $dbr->condition('frd.bundle', 'plan_ship');
  $dbr->condition('frd.field_date_value', $period['from'], '>=');
  $dbr->condition('frd.field_date_value', $period['to'], '<');

  $dbr->innerJoin('field_data_field_amount', 'fra', 'fra.entity_id = p.id');
  $dbr->condition('fra.bundle', 'plan_ship');
  $dbr->addExpression('SUM(fra.field_amount_value)', 'amount');

  $dbr_d = clone($dbr);
  $dbr_f = clone($dbr);

  $dbr->condition('frt.field_record_type_td_value', DASH_TYPE_PLAN);
  $dbr_f->condition('frt.field_record_type_td_value', DASH_TYPE_FACT);
  $dbr_d->condition('frt.field_record_type_td_value', DASH_TYPE_DEAL);

  $regions_plan = $dbr->execute()->fetchAllAssoc('tid');
  $regions_fact = $dbr_f->execute()->fetchAllAssoc('tid');
  $regions_deal = $dbr_d->execute()->fetchAllAssoc('tid');

  $tids = array_keys($regions_plan) + array_keys($regions_fact) + array_keys($regions_deal);

  $plan_fact = [];
  $sort_p = $sort_f = $sort_d = [];
  foreach($tids as $tid) {
    $name = $regions_plan[$tid]->name ?? ($regions_fact[$tid]->name ?? $regions_deal[$tid]->name);
    $plan_fact[$tid] = [
      'plan' => $regions_plan[$tid]->amount ?? 0,
      'fact' => $regions_fact[$tid]->amount ?? 0,
      'deal' => $regions_deal[$tid]->amount ?? 0,
      'tid' => $tid,
      'name' => $name,
    ];
  }

  // подготовим к сортировке по сумме
  foreach ($plan_fact as $item) {
    if ($item['plan']) {
      $sort_p[$item['plan']] = $item['tid'];
    } elseif ($item['fact']) {
      $sort_f[$item['fact']] = $item['tid'];
    } else {
      $sort_d[$item['deal']] = $item['tid'];
    }
  }

  // сначала сортировка по плану
  krsort($sort_p);
  // если план = 0, то сортировка по факту
  krsort($sort_f);
  // в конце по контрактам
  krsort($sort_d);
  $sort = $sort_p + $sort_f + $sort_d;

  $chart = array(
    '#type' => 'chart',
    '#chart_type' => 'bar',
    '#colors' => [DASH_COLOR_BLUE, DASH_COLOR_LIGHT_BLUE, '#ccc'],
    'xaxis' => [
      '#type' => 'chart_xaxis',
      '#raw_options' => [
        'textStyle' => ['fontName' => '<global-font-name>'],
      ]
    ],
    'yaxis' => [
      '#type' => 'chart_yaxis',
      '#raw_options' => [
        'textStyle' => ['fontName' => '<global-font-name>'],
      ],
    ],
    '#raw_options' => [
      'titleTextStyle' => ['bold' => 'true', 'fontName' => '<global-font-name>', 'fontSize' => '16'],
      'bar' => ['groupWidth' => "60%"],
      'legend' => ['position' => 'top', 'height' => 100, 'textStyle' => ['fontSize' => '12', 'fontName' => '<global-font-name>']],
      'chartArea' => ['width' => '80%', 'left' => 100],
      'isStacked' => 'true',
      'tooltip' => ['isHtml' => true],
      'annotations' => [
        'textStyle' => ['color' => '#000'],
        'datum' => ['stem' => ['color' => '#ccc', 'length' => 20]],
//        'alwaysOutside' => true,
      ],
    ],
    'fact' => [
      '#type' => 'chart_data',
      '#title' => 'Факт',
      '#data' => [],
    ],
    'deal' => [
      '#type' => 'chart_data',
      '#title' => 'Неотгруженные контракты',
      '#data' => [],
    ],
    'plan' => [
      '#type' => 'chart_data',
      '#title' => 'План',
      '#data' => [],
    ],
  );

  foreach ($sort as $tid) {
    if ($plan_fact[$tid]['fact'] || $plan_fact[$tid]['plan'] || $plan_fact[$tid]['deal']) {
      $chart['xaxis']['#labels'][] = $plan_fact[$tid]['name'];
      $amount_p = (float)$plan_fact[$tid]['plan']/DASH_REV_DIVIDER;
      $amount_d = (float)$plan_fact[$tid]['deal']/DASH_REV_DIVIDER;
      $amount_f = (float)$plan_fact[$tid]['fact']/DASH_REV_DIVIDER;

      $chart['fact']['#data'][] = $amount_f;
      $chart['deal']['#data'][] = $amount_d;
      $chart['plan']['#data'][] = max($amount_p - $amount_d - $amount_f, 0);

      $tooltip =  '<div style="font-family: sans-serif; padding: 8px 12px; min-width:180px;white-space: nowrap;">' .
        '<div><div style="display:inline-block; width: 170px;">План:</div><div style="display:inline-block; text-align: right; width: 80px;"><b>' . number_format($amount_p, 2, ',', ' ') . '</b>&nbsp;' . DASH_REV_SUFFIX . '</div></div>' .
        '<div><div style="display:inline-block; width: 170px;">Неотгруженные контракты:</div><div style="display:inline-block; text-align: right; width: 80px;"><b>' . number_format($amount_d, 2, ',', ' ') . '</b>&nbsp;' . DASH_REV_SUFFIX . '</div></div>' .
        '<div><div style="display:inline-block; width: 170px;">Факт:</div><div style="display:inline-block; text-align: right; width: 80px;"><b>' . number_format($amount_f, 2, ',', ' ') . '</b>&nbsp;' . DASH_REV_SUFFIX . '</div></div>' .
        '</div>';
      $chart['plan'][] = array(
        '#type' => 'chart_data_item',
        '#title' => $tooltip,
        '#raw_options' => [
          'annotation' => $amount_p > $amount_f + $amount_d ? number_format($amount_p, 2, ',', ' ') : '',
        ],
      );
      $chart['deal'][] = array(
        '#type' => 'chart_data_item',
        '#title' => $tooltip,
      );
      $chart['fact'][] = array(
        '#type' => 'chart_data_item',
        '#title' => $tooltip,
        '#raw_options' => [
          'annotation' => ($amount_f > $amount_p) ? number_format($amount_f, 2, ',', ' ') : '',
        ],
      );
    }
  }

  $chart['#height'] = 45*count($chart['fact']['#data']) + 120;
  $chart['#raw_options']['chartArea']['height'] = 45*count($chart['fact']['#data']);

  return $chart;
}

function dep_2v_2g_pie_revenue_pay_plan($time_from, $time_to)
{
  $dbr = db_select('eck_plan', 'p');
  $dbr->condition('p.type', 'plan_revenue');
  $dbr->innerJoin('field_data_field_date', 'frd', 'frd.entity_id = p.id');
  $dbr->condition('frd.bundle', 'plan_revenue');
  $dbr->condition('frd.field_date_value', $time_from, '>=');
  $dbr->condition('frd.field_date_value', $time_to, '<');

  $dbr->innerJoin('field_data_field_is_fact', 'ff', 'ff.entity_id = p.id');
  $dbr->condition('ff.bundle', 'plan_revenue');
  $dbr->condition('ff.field_is_fact_value', DASH_TYPE_FACT);

  $dbr->innerJoin('field_data_field_client_td', 'fct', 'fct.entity_id = p.id');
  $dbr->condition('fct.bundle', 'plan_revenue');
  $dbr->innerJoin('field_data_field_region', 'fr', 'fr.entity_id = fct.field_client_td_tid');
  $dbr->addField('fr', 'field_region_tid', 'region_tid');
  $dbr->groupBy('region_tid');

  $dbr->innerJoin('taxonomy_term_data', 't', 't.tid = fr.field_region_tid');
  $dbr->addField('t', 'name', 'region_name');

  $dbr->innerJoin('field_data_field_amount', 'fra', 'fra.entity_id = p.id');
  $dbr->condition('fra.bundle', 'plan_revenue');
  $dbr->addExpression('SUM(fra.field_amount_value)', 'amount');
  $result = $dbr->execute()->fetchAllAssoc('amount');

  $total = 0;
  foreach($result as $item) {
    $total += $item->amount;
  }

  $types = [];
  $types_data = [];
  $other = 0;
  foreach($result as $item) {
    // выводим значения больше 3% от общей суммы
    $amount = $item->amount/DASH_REV_DIVIDER;
    if ($item->amount/$total*100 > 3) {
      $types[$amount] = $item->region_name;
      $types_data[$amount] = $amount;
    } else {
      $other += $amount;
    }
  }
  if ($other) {
    $types[$other] = 'Прочие (< 3%)';
    $types_data[$other] = $other;
  }

  krsort($types);
  krsort($types_data);

  $chart = array(
    '#type' => 'chart',
    '#title' => 'Структура отгрузки по регионам',
    '#title_position' => 'center',
    '#chart_type' => 'pie',
    '#legend_position' => 'right',
    '#legend_title_font_size' => '10px',
    '#data_labels' => TRUE,
    '#tooltips' => TRUE,
    '#height' => '350',
    '#raw_options' => [
      'titleTextStyle' => ['bold' => 'true', 'fontName' => '<global-font-name>', 'fontSize' => '16'],
      'chartArea' => ['width' => '85%'],
    ],
  );
  $chart['pie_data'] = array(
    '#type' => 'chart_data',
    '#title' => 'Продукция',
    '#labels' => array_values($types),
    '#data' => array_values($types_data),
  );

  return $chart;
}

function dep_2v_2g_column_ship_plan_fact_by_nom_single($period, $nom)
{
  // собрать данные периодов с DASH_YEAR_HISTORY_START года
  $years_shift = date('Y', $period['from']) - (DASH_HISTORY_START_YEAR_TD+1);
  $years_shift = abs($years_shift)+1 > DASH_HISTORY_LENGTH ? DASH_HISTORY_LENGTH : $years_shift;
  $plan_fact_all = [];
  do {
    $time_period_start = gmmktime(0, 0, 0, date('n', $period['from']) - 12 * $years_shift, date('j', $period['from']), date('Y', $period['from']));
    $time_period_end = gmmktime(0, 0, 0, date('n', $period['to']) - 12 * $years_shift, date('j', $period['to']), date('Y', $period['to']));

    // выбрать препараты с наибольшим планом
    $dbr = db_select('eck_plan', 'p');
    $dbr->condition('p.type', 'plan_ship');

    $dbr->innerJoin('field_data_field_record_type_td', 'frt', 'frt.entity_id = p.id');
    $dbr->condition('frt.bundle', 'plan_ship');

    $dbr->innerJoin('field_data_field_date', 'frd', 'frd.entity_id = p.id');
    $dbr->condition('frd.bundle', 'plan_ship');

    $dbr->condition('frd.field_date_value', $time_period_start, '>=');
    $dbr->condition('frd.field_date_value', $time_period_end, '<');

    $dbr->innerJoin('field_data_field_nomenklatura_td', 'fn', 'fn.entity_id = p.id');
    $dbr->condition('fn.field_nomenklatura_td_tid', DASH_TD_NOM_ID_LIST_TO_EXCLUDE, 'NOT IN');

    if ($nom != 0) {
      $dbr->condition('fn.field_nomenklatura_td_tid', $nom);
      $dbr->innerJoin('taxonomy_term_data', 't', 't.tid = fn.field_nomenklatura_td_tid');
      $dbr->addField('t', 'tid');
      $dbr->addField('t', 'name');
      $dbr->groupBy('tid');
    }

    $dbr->innerJoin('field_data_field_quantity_td', 'fq', 'fq.entity_id = p.id');
    $dbr->condition('fq.bundle', 'plan_ship');
    $dbr->addExpression('SUM(fq.field_quantity_td_value)', 'qty');

//    $dbr->innerJoin('field_data_field_amount', 'fra', 'fra.entity_id = p.id');
//    $dbr->condition('fra.bundle', 'plan_ship');
//    $dbr->addExpression('SUM(fra.field_amount_value)', 'qty');

    $dbr_d = clone($dbr);
    $dbr_f = clone($dbr);

    $dbr->condition('frt.field_record_type_td_value', DASH_TYPE_PLAN);
    $dbr_f->condition('frt.field_record_type_td_value', DASH_TYPE_FACT);
    $dbr_d->condition('frt.field_record_type_td_value', DASH_TYPE_DEAL);

    $result_plan = $dbr->execute()->fetchAll();
    $result_fact = $dbr_f->execute()->fetchAll();
    $result_deal = $dbr_d->execute()->fetchAll();

    $plan_fact[$nom] = [
      'plan' => $result_plan[0]->qty,
      'fact' => $result_fact[0]->qty,
      'deal' => $result_deal[0]->qty,
      'tid' => $nom,
      'name' => $result_plan[0]->name ?? '',
    ];

    $plan_fact_all[date('Y', $time_period_start)] = $plan_fact;

    $years_shift--;
  } while ($years_shift >= 0);


  $chart = array(
    '#type' => 'chart',
    '#chart_type' => 'column',
    '#colors' => [DASH_COLOR_BLUE, DASH_COLOR_LIGHT_BLUE, '#ccc'],
    '#height' => '500',
    'xaxis' => [
      '#type' => 'chart_xaxis',
      '#raw_options' => [
        'textStyle' => ['fontName' => '<global-font-name>'],
      ]
    ],
    'yaxis' => [
      '#type' => 'chart_yaxis',
      '#min' => 0,
    ],
    '#raw_options' => [
      'titleTextStyle' => ['bold' => 'true', 'fontName' => '<global-font-name>', 'fontSize' => '16'],
      'legend' => ['position' => 'top', 'textStyle' => ['fontSize' => '12', 'fontName' => '<global-font-name>']],
      'chartArea' => ['height' => '80%', 'width' => '95%', 'left' => 70],
      'isStacked' => 'true',
      'tooltip' => ['isHtml' => true],
      'bar' => ['groupWidth' => "80%"],
    ],
    'fact' => [
      '#type' => 'chart_data',
      '#title' => 'Факт',
      '#data' => [],
    ],
    'deal' => [
      '#type' => 'chart_data',
      '#title' => 'Неотгруженные контракты',
      '#data' => [],
    ],
    'plan' => [
      '#type' => 'chart_data',
      '#title' => 'План',
      '#data' => [],
    ],
  );

  // пространство слева
  $chart['fact']['#data'][] = 0; $chart['deal']['#data'][] = 0; $chart['plan']['#data'][] = 0; $chart['xaxis']['#labels'][] = '';$chart['fact'][] = $chart['plan'][] = $chart['deal'][] = ['#type' => 'chart_data_item'];

  // столбцы по годам
  $chart['xaxis']['#title'] = '';
  $max = 0;
  foreach($plan_fact_all as $year => $item) {
    $chart['xaxis']['#labels'][] = $year . '-' . ($year+1);

    $tid = array_shift($item)['tid'];

    $qty_p = (float)$plan_fact_all[$year] ? $plan_fact_all[$year][$tid]['plan'] : 0;
    $qty_d = (float)$plan_fact_all[$year] ? $plan_fact_all[$year][$tid]['deal'] : 0;
    $qty_f = (float)$plan_fact_all[$year] ? $plan_fact_all[$year][$tid]['fact'] : 0;

    $max = max($qty_p, $qty_f, $max);

    // информация нужна только для текущего года
    $print = date('Y', $period['from']) == $year;

    $chart['fact']['#data'][] = $qty_f;
    $chart['deal']['#data'][] = $print ? $qty_d : 0;
    $chart['plan']['#data'][] = $print ? ($qty_p - $qty_d - $qty_f) : 0;

    $delta = '';
    if ($qty_p) {
      $delta = ($qty_f > $qty_p ? '(+' : '(') . number_format(($qty_f / $qty_p * 100) - 100, 0, null, ' ') . '%)';
    }
    $tooltip =  '<div style="font-family: sans-serif; padding: 8px 12px; min-width:140px;white-space: nowrap;">' .
      ($print ? '<div><div style="display:inline-block; width: 180px;">План:</div><div style="display:inline-block; text-align: right; width: 60px;"><b>' . number_format($qty_p, 0, ',', ' ') . '</b></div></div>' : '') .
      ($print ? '<div><div style="display:inline-block; width: 180px;">Неотгруженные контракты:</div><div style="display:inline-block; text-align: right; width: 60px;"><b>' . number_format($qty_d, 0, ',', ' ') . '</b></div></div>' : '') .
      '<div><div style="display:inline-block; width: 180px;">Факт:</div><div style="display:inline-block; text-align: right; width: 60px;"><b>' . number_format($qty_f, 0, ',', ' ') . '</b></div></div>' .
      '</div>';

    $chart['fact'][] = array(
      '#type' => 'chart_data_item',
      '#title' => $tooltip,
      '#raw_options' => [
        'annotation' => $print ? $delta : '',
        'style' => $print ? '' : 'color: ' . DASH_COLOR_AQUA, // изменить цвет факта предыдущих периодов
      ],
    );
    $chart['deal'][] = array(
      '#type' => 'chart_data_item',
      '#title' => $print ? $tooltip : '',
    );
    $chart['plan'][] = array(
      '#type' => 'chart_data_item',
      '#title' => $print ? $tooltip : '',
    );

    $chart['xaxis']['#title'] = $plan_fact_all[$year] ? $plan_fact_all[$year][$tid]['name'] : $chart['xaxis']['#title'];
  }

  $chart['yaxis']['#max'] = $max * 1.15; // нужен чтобы tooltip для высоких графиков помещался вверху и не моргал

  // пространство справа
  $chart['fact']['#data'][] = 0; $chart['deal']['#data'][] = 0; $chart['plan']['#data'][] = 0; $chart['xaxis']['#labels'][] = '';

  return $chart;
}

function dep_2v_2g_column_ship_plan_fact_by_nom($period, $options = [])
{
  $chart = dash_get_no_data_chart();

  // выбрать препараты с наибольшим планом
  $dbr = db_select('eck_plan', 'p');
  $dbr->condition('p.type', 'plan_ship');

  $dbr->innerJoin('field_data_field_nomenklatura_td', 'fn', 'fn.entity_id = p.id');
  $dbr->condition('fn.field_nomenklatura_td_tid', DASH_TD_NOM_ID_LIST_TO_EXCLUDE, 'NOT IN');
  $dbr->innerJoin('taxonomy_term_data', 't', 't.tid = fn.field_nomenklatura_td_tid');
  $dbr->fields('t', ['tid', 'name']);
  $dbr->groupBy('t.tid');

  $dbr->innerJoin('field_data_field_record_type_td', 'frt', 'frt.entity_id = p.id');
  $dbr->condition('frt.bundle', 'plan_ship');

  $dbr->innerJoin('field_data_field_date', 'frd', 'frd.entity_id = p.id');
  $dbr->condition('frd.bundle', 'plan_ship');

  $dbr->innerJoin('field_data_field_quantity_td', 'fq', 'fq.entity_id = p.id');
  $dbr->condition('fq.bundle', 'plan_ship');
  $dbr->addExpression('SUM(fq.field_quantity_td_value)', 'qty');

//  план только за апрель
//  $time_period_start = gmmktime(0, 0, 0, 4, 1, date('Y'));
//  $time_period_end = gmmktime(0, 0, 0, 5, 1, date('Y'));
//  $dbr->condition('frd.field_date_value', $time_period_start, '>=');
//  $dbr->condition('frd.field_date_value', $time_period_end, '<');

  $dbr->condition('frd.field_date_value', $period['from'], '>=');
  $dbr->condition('frd.field_date_value', $period['to'], '<');

  $dbr_d = clone($dbr);
  $dbr_f = clone($dbr);

  $dbr->condition('frt.field_record_type_td_value', DASH_TYPE_PLAN);
  $dbr_f->condition('frt.field_record_type_td_value', DASH_TYPE_FACT);
  $dbr_d->condition('frt.field_record_type_td_value', DASH_TYPE_DEAL);

  $result_plan = $dbr->execute()->fetchAllAssoc('tid');
  $result_fact = $dbr_f->execute()->fetchAllAssoc('tid');
  $result_deal = $dbr_d->execute()->fetchAllAssoc('tid');

  $tids = array_merge(array_keys($result_plan), array_keys($result_fact), array_keys($result_deal));

  // какие-то регионы отсутствуют в плане (= 0), какие-то в факте, перебираем оба отдельно
  $plan_fact = [];
  $sort_p = $sort_f = $sort_d = [];
  foreach($tids as $tid) {
    $name = $result_plan[$tid]->name ?? ($result_fact[$tid]->name ?? $result_deal[$tid]->name);
    $plan_fact[$tid] = [
      'plan' => $result_plan[$tid]->qty ?? 0,
      'fact' => $result_fact[$tid]->qty ?? 0,
      'deal' => $result_deal[$tid]->qty ?? 0,
      'tid' => $tid,
      'name' => $name,
    ];
  }

  // подготовим к сортировке по сумме
  foreach ($plan_fact as $item) {
    if ($item['plan']) {
      $sort_p[$item['plan']] = $item['tid'];
    } elseif ($item['fact']) {
      $sort_f[$item['fact']] = $item['tid'];
    } else {
      $sort_d[$item['deal']] = $item['tid'];
    }
  }

  // сначала сортировка по плану
  krsort($sort_p);
  // если план = 0, то сортировка по факту
  krsort($sort_f);
  krsort($sort_d);
  $sort = $sort_p + $sort_f + $sort_d;

  $chart = array(
    '#type' => 'chart',
    '#chart_type' => 'column',
    '#colors' => [DASH_COLOR_BLUE, DASH_COLOR_LIGHT_BLUE, '#ccc'],
    '#height' => '500',
    'xaxis' => [
      '#type' => 'chart_xaxis',
      '#raw_options' => [
        'textStyle' => ['fontName' => '<global-font-name>'],
      ]
    ],
    'yaxis' => [
      '#type' => 'chart_yaxis',
      '#min' => 0,
    ],
    '#raw_options' => [
      'titleTextStyle' => ['bold' => 'true', 'fontName' => '<global-font-name>', 'fontSize' => '16'],
      'legend' => ['position' => 'top', 'textStyle' => ['fontSize' => '12', 'fontName' => '<global-font-name>']],
      'chartArea' => [
        'height' => '80%',
        'width' => '95%',
        'left' => 70,
      ],
      'isStacked' => 'true',
      'tooltip' => ['isHtml' => true],
    ],
    'fact' => [
      '#type' => 'chart_data',
      '#title' => 'Факт',
      '#data' => [],
    ],
    'deal' => [
      '#type' => 'chart_data',
      '#title' => 'Неотгруженные контракты',
      '#data' => [],
    ],
    'plan' => [
      '#type' => 'chart_data',
      '#title' => 'План',
      '#data' => [],
    ],
  );

  $index = 0;
  foreach ($sort as $tid) {
    if (isset($options['range']) && $options['range'][0] <= $index && $index <= $options['range'][1]) {
      if ($plan_fact[$tid]['fact'] || $plan_fact[$tid]['plan'] || $plan_fact[$tid]['deal']) {
        $chart['xaxis']['#labels'][] = $plan_fact[$tid]['name'];
        $qty_p = (float)$plan_fact[$tid]['plan'];
        $qty_d = (float)$plan_fact[$tid]['deal'];
        $qty_f = (float)$plan_fact[$tid]['fact'];

        $chart['fact']['#data'][] = $qty_f;
        $chart['deal']['#data'][] = $qty_d;
        $chart['plan']['#data'][] = max($qty_p - $qty_d - $qty_f, 0);

        $delta = '';
        if ($qty_p) {
          $delta = ($qty_f > $qty_p ? '(+' : '(') . number_format(($qty_f / $qty_p * 100) - 100, 0, null, ' ') . '%)';
        }

        $tooltip =  '<div style="font-family: sans-serif; padding: 8px 12px; min-width:140px;white-space: nowrap;">' .
          '<div><div style="display:inline-block; width: 180px;">План:</div><div style="display:inline-block; text-align: right; width: 60px;"><b>' . number_format($qty_p, 0, ',', ' ') . '</b></div></div>' .
          '<div><div style="display:inline-block; width: 180px;">Неотгруженные контракты:</div><div style="display:inline-block; text-align: right; width: 60px;"><b>' . number_format($qty_d, 0, ',', ' ') . '</b></div></div>' .
          '<div><div style="display:inline-block; width: 180px;">Факт:</div><div style="display:inline-block; text-align: right; width: 60px;"><b>' . number_format($qty_f, 0, ',', ' ') . '</b></div></div>' .
          '</div>';
        $chart['plan'][] = array(
          '#type' => 'chart_data_item',
          '#title' => $tooltip,
        );
        $chart['deal'][] = array(
          '#type' => 'chart_data_item',
          '#title' => $tooltip,
        );
        $chart['fact'][] = array(
          '#type' => 'chart_data_item',
          '#title' => $tooltip,
          '#raw_options' => [
            'annotation' => $delta,
          ],
        );
      }
    }
    $index++;
  }

  return $chart;
}

function dep_2v_2g_column_ship_fact_gross_profit_by_week($period)
{
  $chart = dash_get_no_data_chart('Валовая прибыль (%)');

  // выбрать препараты с наибольшим планом
  if ($fact = dash_get_ship_plan_fact_by_conditions(['type' => DASH_TYPE_FACT, 'period' => $period])) {

    // сгруппировать понедельно
    $result_by_week = [];
    foreach (dash_get_weeks_list($period) as $week) {
      $result_by_week[$week['start']] = [
        'amount' => 0,
        'net_amount' => 0,
        'start' => $week['start'],
        'end' => $week['end'],
      ];

      foreach ($fact as $record) {
        // записи без себестоимости не берём (услуги и прочее)
        if ($record->date >= $week['start'] && $record->date < $week['end'] && $record->net_cost > 0) {
          $nds = $record->nds ?? 20;
          $amount_wo_nds = $record->amount / (1 + $nds / 100);
          $result_by_week[$week['start']]['amount'] += $amount_wo_nds;
          $result_by_week[$week['start']]['net_amount'] += $record->net_cost * $record->qty;
        }
      }
    }
    ksort($result_by_week);

    $chart = array(
      '#type' => 'chart',
      '#title' => 'Валовая прибыль (%)',
      '#chart_type' => 'column',
      '#colors' => [DASH_COLOR_BLUE],
      '#height' => '500',
      'xaxis' => [
        '#type' => 'chart_xaxis',
        '#raw_options' => [
          'textStyle' => ['fontName' => '<global-font-name>'],
        ]
      ],
      'yaxis' => [
        '#type' => 'chart_yaxis',
        '#min' => 0,
        '#max' => 55,
      ],
      '#raw_options' => [
        'titleTextStyle' => ['bold' => 'true', 'fontName' => '<global-font-name>', 'fontSize' => '16'],
        'legend' => ['position' => 'top', 'textStyle' => ['fontSize' => '12', 'fontName' => '<global-font-name>']],
        'chartArea' => [
          'height' => '80%',
          'width' => '95%',
          'left' => 50,
        ],
        'tooltip' => ['isHtml' => true],
      ],
      // прибыль по неделям
      'profit' => [
        '#type' => 'chart_data',
        '#title' => '% за неделю',
        '#data' => [],
      ],
      // 28%
      'line' => [
        '#type' => 'chart_data',
        '#chart_type' => 'line',
        '#data' => [],
        '#title' => '28%',
        '#target_axis' => 'yaxis',
        '#color' => DASH_COLOR_AQUA,
        '#marker_radius' => 1,
      ],
      // суммарный %
      'line_year' => [
        '#type' => 'chart_data',
        '#chart_type' => 'line',
        '#data' => [],
        '#title' => 'Суммарный %',
        '#target_axis' => 'yaxis',
        '#color' => DASH_COLOR_PURPLE,
        '#marker_radius' => 6,
      ],
    );

    $total_amount = $total_net_amount = 0;
    foreach ($result_by_week as $week) {
      if ($week['amount']) {
        $label = date('d.m', $week['start']) . '-' . date('d.m', $week['end'] - 1);

        $amount = $week['amount'] / DASH_REV_DIVIDER;
        $net_amount = $week['net_amount'] / DASH_REV_DIVIDER;

        $formula = ($amount - $net_amount) / ($amount) * 100;

        $chart['xaxis']['#labels'][] = $label;
        $chart['profit']['#data'][] = $formula;

        $total_amount += $week['amount'];
        $total_net_amount += $week['net_amount'];
        $total_formula = ($total_amount - $total_net_amount) / ($total_amount) * 100;

        $tooltip = '<div style="font-family: sans-serif; padding: 8px 12px; min-width:140px;white-space: nowrap;">' .
          '<div><div style="display:inline-block; width: 180px;">Выручка за неделю (без НДС):</div><div style="display:inline-block; text-align: right; width: 80px;"><b>' . number_format($week['amount'], 0, ',', ' ') . '</b></div></div>' .
          '<div><div style="display:inline-block; width: 180px;">Себестоимость:</div><div style="display:inline-block; text-align: right; width: 80px;"><b>' . number_format($week['net_amount'], 0, ',', ' ') . '</b></div></div>' .
          '<div><div style="display:inline-block; width: 180px;">Прибыль:</div><div style="display:inline-block; text-align: right; width: 80px;"><b>' . number_format($week['amount'] - $week['net_amount'], 0, ',', ' ') . '</b></div></div>' .
          '<div><div style="display:inline-block; width: 180px;">%</div><div style="display:inline-block; text-align: right; width: 80px;"><b>' . number_format($formula, 1, ',', ' ') . '</b></div></div>' .
          '</div>';
        $chart['profit'][] = [
          '#type' => 'chart_data_item',
          '#title' => $tooltip,
          '#raw_options' => [
            'annotation' => number_format($formula, 1, ',', ' ') . '%',
          ],
        ];

        $chart['line']['#data'][] = 28;
        $tooltip = '<div style="font-family: sans-serif; padding: 8px 12px; min-width:140px;white-space: nowrap;">' .
          '28%' .
          '</div>';
        $chart['line'][] = [
          '#type' => 'chart_data_item',
          '#title' => $tooltip,
        ];
        $chart['line_year']['#data'][] = $total_formula;
        $tooltip = '<div style="font-family: sans-serif; padding: 8px 12px; min-width:140px;white-space: nowrap;">' .
          '<div><div style="display:inline-block; width: 180px;">Суммарная выручка (без НДС):</div><div style="display:inline-block; text-align: right; width: 80px;"><b>' . number_format($total_amount, 0, ',', ' ') . '</b></div></div>' .
          '<div><div style="display:inline-block; width: 180px;">Себестоимость:</div><div style="display:inline-block; text-align: right; width: 80px;"><b>' . number_format($total_net_amount, 0, ',', ' ') . '</b></div></div>' .
          '<div><div style="display:inline-block; width: 180px;">Суммарная прибыль:</div><div style="display:inline-block; text-align: right; width: 80px;"><b>' . number_format($total_amount - $total_net_amount, 0, ',', ' ') . '</b></div></div>' .
          '<div><div style="display:inline-block; width: 180px;">%</div><div style="display:inline-block; text-align: right; width: 80px;"><b>' . number_format($total_formula, 1, ',', ' ') . '</b></div></div>' .
          '</div>';
        $chart['line_year'][] = [
          '#type' => 'chart_data_item',
          '#title' => $tooltip,
        ];
      }
    }
  }

  return $chart;
}

function dep_2v_2g_column_ship_plan_by_nom($period, $regions = [])
{
  $chart = dash_get_no_data_chart();

  // выбрать препараты с наибольшим планом
  $fact = dash_get_ship_plan_fact_by_conditions([
    'type' => DASH_TYPE_FACT,
    'period' => $period,
    'regions' => $regions,
  ]);

  if ($fact) {
    // сгруппировать по номенклатуре
    $result_by_nom = [];
    foreach ($fact as $item) {
      if (!isset($result_by_nom[$item->tid]['amount'])) {
        $result_by_nom[$item->tid] = [
          'tid' => $item->tid,
          'name' => $item->name,
          'amount' => 0,
        ];
      }
      $result_by_nom[$item->tid]['amount'] += $item->amount;
    }

    // сортировать по сумме
    $result_by_amount = [];
    foreach ($result_by_nom as $tid => $item) {
      $result_by_amount[round($item['amount']) . str_pad($tid, 10, '0', STR_PAD_LEFT)] = $tid;
    }
    krsort($result_by_amount);
    $result_by_amount = array_slice($result_by_amount, 0, 15);

    $chart = array(
      '#type' => 'chart',
      '#chart_type' => 'column',
      '#height' => '400',
      '#data_labels' => TRUE,
      '#legend_position' => 'bottom',
      'yaxis' => [
        '#type' => 'chart_yaxis',
        '#min' => 0,
        '#raw_options' => ['textStyle' => ['fontName' => '<global-font-name>']]
      ],
      '#raw_options' => [
        'titleTextStyle' => ['bold' => 'true', 'fontName' => '<global-font-name>', 'fontSize' => '16'],
        'legend' => ['position' => 'right', 'maxLines' => 3, 'textStyle' => ['fontSize' => '13', 'fontName' => '<global-font-name>']],
        'chartArea' => [
          'height' => '90%',
          'left' => 50,
        ],
      ],
    );

    foreach ($result_by_amount as $tid) {
      $name = $result_by_nom[$tid]['name'];
      $amount = $result_by_nom[$tid]['amount'];
      $chart[$tid] = array(
        '#type' => 'chart_data',
        '#title' => (string)$name,
        '#data' => [(float)$amount / DASH_REV_DIVIDER],
      );
      $chart[$tid][] = array(
        '#type' => 'chart_data_item',
        '#raw_options' => [
          'annotation' => (string)round($amount / DASH_REV_DIVIDER),
        ],
      );
    }
    if (!$result_by_amount) {
      $chart[] = array(
        '#type' => 'chart_data',
        '#data' => [],
      );
    }
  }

  return $chart;
}

/**
 * ----- Формы --------------------------------------------------------------------------------------------------------
 */
function dep_2v_2g_ship_plan_nom_filter_form($form, &$form_state)
{
  if (!isset($form_state['period'])) {
    $form_state['period'] = dash_get_page_time_bounds(DASH_PERIOD_START_MONTH_TD);
  }

  $dbr = db_select('eck_plan', 'p');
  $dbr->condition('p.type', 'plan_ship');

  $dbr->innerJoin('field_data_field_date', 'frd', 'frd.entity_id = p.id');
  $dbr->condition('frd.bundle', 'plan_ship');
  $dbr->condition('frd.field_date_value', $form_state['period']['from'], '>=');
  $dbr->condition('frd.field_date_value', $form_state['period']['to'], '<');

  $dbr->innerJoin('field_data_field_nomenklatura_td', 'fn', 'fn.entity_id = p.id');
  $dbr->condition('fn.bundle', 'plan_ship');
  $dbr->condition('fn.field_nomenklatura_td_tid', DASH_TD_NOM_ID_LIST_TO_EXCLUDE, 'NOT IN');
  $dbr->innerJoin('taxonomy_term_data', 't', 't.tid = fn.field_nomenklatura_td_tid');
  $dbr->fields('t', ['tid', 'name']);
  $dbr->orderBy('name');
  $nom = $dbr->execute()->fetchAllAssoc('tid');

  $options = ['0' => 'Сумма по всей номенклатуре'];
  foreach ($nom as $item) {
    $options[$item->tid] = $item->name;
  }

  $form['#attributes'] = ['class' => ['dash-filter-form']];
  $form['nom'] = [
    '#title' => 'Номенклатура',
    '#type' => 'select',
    '#options' => $options,
    '#default_value' => empty($_GET['nom']) || empty($options[$_GET['nom']]) ? 0 : $_GET['nom'],
    '#ajax' => [
      'wrapper' => 'nom-target',
      'callback' => 'dep_2v_2g_ship_plan_nom_filter_form_ajax_callback',
    ],
  ];

  return $form;
}
function dep_2v_2g_ship_plan_nom_filter_form_submit($form, &$form_state)
{
  $form_state['redirect'] = [
    'dashboard/current', [
      'query' => ['nom' => $form_state['values']['nom']],
      'fragment' => 'dash-ship-plan-nom-filter-form'
    ]
  ];
}
function dep_2v_2g_ship_plan_nom_filter_form_ajax_callback($form, $form_state)
{
  $data_arr = dep_2v_2g_column_ship_plan_fact_by_nom_single($form_state['period'], $form_state['values']['nom']);
  return '<div id="nom-target" class="col-xs-12 col-md-4">' . drupal_render($data_arr) . '</div>';
}


function dep_2v_2g_ship_plan_region_filter_form($form, &$form_state)
{
  if (!isset($form_state['period'])) {
    $form_state['period'] = dash_get_page_time_bounds(DASH_PERIOD_START_MONTH_TD);
  }

  $dbr = db_select('eck_plan', 'p');
  $dbr->condition('p.type', 'plan_ship');

  $dbr->innerJoin('field_data_field_date', 'frd', 'frd.entity_id = p.id');
  $dbr->condition('frd.bundle', 'plan_ship');
  $dbr->condition('frd.field_date_value', $form_state['period']['from'], '>=');
  $dbr->condition('frd.field_date_value', $form_state['period']['to'], '<');

  $dbr->innerJoin('field_data_field_client_td', 'fct', 'fct.entity_id = p.id');
  $dbr->condition('fct.bundle', 'plan_ship');
  $dbr->innerJoin('field_data_field_region', 'fr', 'fr.entity_id = fct.field_client_td_tid');

  $dbr->addField('fr', 'field_region_tid');
  $regions = $dbr->execute()->fetchCol();

  $options = ['0' => 'Сумма по всем регионам'];

  $vid = taxonomy_vocabulary_machine_name_load('regions')->vid;
  $tree = taxonomy_get_tree($vid, 0, 4);

  $options += dash_get_select_tree($tree, null, $regions);

  $form['#attributes'] = ['class' => ['dash-filter-form']];
  $form['region'] = [
    '#title' => 'Регион',
    '#type' => 'select',
    '#options' => $options,
    '#default_value' => empty($_GET['region']) || empty($options[$_GET['region']]) ? 0 : $_GET['region'],
    '#ajax' => [
      'wrapper' => 'region-target',
      'callback' => 'dep_2v_2g_ship_plan_region_filter_form_ajax_callback',
    ],
//    '#theme' => 'select_tree',
  ];

  return $form;
}
function dep_2v_2g_ship_plan_region_filter_form_submit($form, &$form_state)
{
  $form_state['redirect'] = [
    'dashboard/current', [
      'query' => ['region' => $form_state['values']['region']],
      'fragment' => 'dash-ship-plan-region-filter-form'
    ]
  ];
}
function dep_2v_2g_ship_plan_region_filter_form_ajax_callback($form, $form_state)
{
  $regions = $form_state['values']['region'] ? dash_get_term_siblings($form_state['values']['region']) : [];
  $data_arr = dep_2v_2g_bar_ship_plan_fact_by_region_single($form_state['period'], $regions);

  return '<div id="region-target" class="col-xs-12">' . drupal_render($data_arr) . '</div>';
}


function dep_2v_2g_column_ship_plan_by_nom_filter_form($form, &$form_state)
{
  if (!isset($form_state['period'])) {
    $form_state['period'] = dash_get_page_time_bounds(DASH_PERIOD_START_MONTH_TD);
  }

  $dbr = db_select('eck_plan', 'p');
  $dbr->condition('p.type', 'plan_ship');

  $dbr->innerJoin('field_data_field_date', 'frd', 'frd.entity_id = p.id');
  $dbr->condition('frd.bundle', 'plan_ship');
  $dbr->condition('frd.field_date_value', $form_state['period']['from'], '>=');
  $dbr->condition('frd.field_date_value', $form_state['period']['to'], '<');

  $dbr->innerJoin('field_data_field_client_td', 'fct', 'fct.entity_id = p.id');
  $dbr->condition('fct.bundle', 'plan_ship');
  $dbr->innerJoin('field_data_field_region', 'fr', 'fr.entity_id = fct.field_client_td_tid');

  $dbr->addField('fr', 'field_region_tid');
  $regions = $dbr->execute()->fetchCol();

  $options = ['0' => 'Сумма по всем регионам'];

  $vid = taxonomy_vocabulary_machine_name_load('regions')->vid;
  $tree = taxonomy_get_tree($vid, 0, 4);

  $options += dash_get_select_tree($tree, null, $regions);

  $form['#attributes'] = ['class' => ['dash-filter-form']];
  $form['region'] = [
    '#title' => 'Регион',
    '#type' => 'select',
    '#options' => $options,
    '#default_value' => empty($_GET['region-n']) || empty($options[$_GET['region-n']]) ? 0 : $_GET['region-n'],
    '#ajax' => [
      'wrapper' => 'nom-r-target',
      'callback' => 'dep_2v_2g_column_ship_plan_by_nom_filter_form_ajax_callback',
    ],
//    '#theme' => 'select_tree',
  ];

  return $form;
}
function dep_2v_2g_column_ship_plan_by_nom_filter_form_submit($form, &$form_state)
{
  $form_state['redirect'] = [
    'dashboard/current', [
      'query' => ['region-n' => $form_state['values']['region']],
      'fragment' => 'dash-ship-plan-region-filter-form'
    ]
  ];
}
function dep_2v_2g_column_ship_plan_by_nom_filter_form_ajax_callback($form, $form_state)
{
  $regions = $form_state['values']['region'] ? dash_get_term_siblings($form_state['values']['region']) : [];
  $data_arr = dep_2v_2g_column_ship_plan_by_nom($form_state['period'], $regions);

  return '<div id="nom-r-target" class="col-xs-12">' . drupal_render($data_arr) . '</div>';
}

function dep_2v_2g_td_column_plan_ship_period_to_period_filter_form($form, &$form_state)
{
  if (!isset($form_state['period'])) {
    $form_state['period'] = dash_get_page_time_bounds(DASH_PERIOD_START_MONTH_TD);
  }

  $dbr = db_select('eck_plan', 'p');
  $dbr->condition('p.type', 'plan_ship');

  $dbr->innerJoin('field_data_field_date', 'frd', 'frd.entity_id = p.id');
  $dbr->condition('frd.bundle', 'plan_ship');
  $dbr->condition('frd.field_date_value', $form_state['period']['from'], '>=');
  $dbr->condition('frd.field_date_value', $form_state['period']['to'], '<');

  $dbr->innerJoin('field_data_field_client_td', 'fct', 'fct.entity_id = p.id');
  $dbr->condition('fct.bundle', 'plan_ship');
  $dbr->innerJoin('field_data_field_region', 'fr', 'fr.entity_id = fct.field_client_td_tid');

  $dbr->addField('fr', 'field_region_tid');
  $regions = $dbr->execute()->fetchCol();

  $options = ['0' => 'Сумма по всем регионам'];

  $vid = taxonomy_vocabulary_machine_name_load('regions')->vid;
  $tree = taxonomy_get_tree($vid, 0, 4);

  $options += dash_get_select_tree($tree, null, $regions);

  $form['#attributes'] = ['class' => ['dash-filter-form']];
  $form['region'] = [
    '#title' => 'Регион',
    '#type' => 'select',
    '#options' => $options,
    '#default_value' => empty($_GET['region-s']) || empty($options[$_GET['region-s']]) ? 0 : $_GET['region-s'],
    '#ajax' => [
      'wrapper' => 'summary-target',
      'callback' => 'dep_2v_2g_td_column_plan_ship_period_to_period_filter_form_ajax_callback',
    ],
  ];

  return $form;
}
function dep_2v_2g_td_column_plan_ship_period_to_period_filter_form_submit($form, &$form_state)
{
  $form_state['redirect'] = [
    'dashboard/current', [
      'query' => ['region-s' => $form_state['values']['region']],
      'fragment' => 'dash-ship-plan-region-filter-form'
    ]
  ];
}
function dep_2v_2g_td_column_plan_ship_period_to_period_filter_form_ajax_callback($form, $form_state)
{
  $regions = $form_state['values']['region'] ? dash_get_term_siblings($form_state['values']['region']) : [];
  $data_arr = dep_2v_2g_td_column_plan_ship_period_to_period($form_state['period'], 'qty', $regions);

  return '<div id="summary-target" class="col-xs-12 col-md-6">' . drupal_render($data_arr) . '</div>';
}

function dep_2v_2g_line_ship_plan_fact_by_month_filter_form($form, &$form_state)
{
  if (!isset($form_state['period'])) {
    $form_state['period'] = dash_get_page_time_bounds(DASH_PERIOD_START_MONTH_TD);
  }

  $dbr = db_select('eck_plan', 'p');
  $dbr->condition('p.type', 'plan_ship');

  $dbr->innerJoin('field_data_field_date', 'frd', 'frd.entity_id = p.id');
  $dbr->condition('frd.bundle', 'plan_ship');
  $dbr->condition('frd.field_date_value', $form_state['period']['from'], '>=');
  $dbr->condition('frd.field_date_value', $form_state['period']['to'], '<');

  $dbr->innerJoin('field_data_field_client_td', 'fct', 'fct.entity_id = p.id');
  $dbr->condition('fct.bundle', 'plan_ship');
  $dbr->innerJoin('field_data_field_region', 'fr', 'fr.entity_id = fct.field_client_td_tid');

  $dbr->addField('fr', 'field_region_tid');
  $regions = $dbr->execute()->fetchCol();

  $options = ['0' => 'Сумма по всем регионам'];

  $vid = taxonomy_vocabulary_machine_name_load('regions')->vid;
  $tree = taxonomy_get_tree($vid, 0, 4);

  $options += dash_get_select_tree($tree, null, $regions);

  $form['#attributes'] = ['class' => ['dash-filter-form']];
  $form['region'] = [
    '#title' => 'Регион',
    '#type' => 'select',
    '#options' => $options,
    '#default_value' => empty($_GET['region-p']) || empty($options[$_GET['region-p']]) ? 0 : $_GET['region-p'],
    '#ajax' => [
      'wrapper' => 'plan-target',
      'callback' => 'dep_2v_2g_line_ship_plan_fact_by_month_filter_form_ajax_callback',
    ],
  ];

  return $form;
}
function dep_2v_2g_line_ship_plan_fact_by_month_filter_form_submit($form, &$form_state)
{
  $form_state['redirect'] = [
    'dashboard/current', [
      'query' => ['region-p' => $form_state['values']['region']],
      'fragment' => 'dash-ship-plan-region-filter-form'
    ]
  ];
}
function dep_2v_2g_line_ship_plan_fact_by_month_filter_form_ajax_callback($form, $form_state)
{
  $regions = $form_state['values']['region'] ? dash_get_term_siblings($form_state['values']['region']) : [];
  $data_arr = dep_2v_2g_line_ship_plan_fact_by_month($form_state['period'], $regions);

  return '<div id="plan-target" class="col-xs-12">' . drupal_render($data_arr) . '</div>';
}

