<?php

/**
 * Implementation of hook_menu().
 */
function reports_menu()
{
  $items['reports'] = array(
    'title' => 'Отчёты',
    'menu_name' => 'main-menu',
    'expanded' => true,
    'weight' => 15,
    'page callback' => 'reports_td_page',
    'access callback' => 'ext_user_has_roles',
    'access arguments' => [[ADMIN_RID, TRADE_HOUSE_USER_RID]],

  );
  $items['reports/td'] = array(
    'title' => 'Торговый Дом',
    'menu_name' => 'main-menu',
    'page callback' => 'reports_td_page',
    'access callback' => 'ext_user_has_roles',
    'access arguments' => [[ADMIN_RID, TRADE_HOUSE_USER_RID]],
    'type' => MENU_NORMAL_ITEM,
  );
  $items['data/production/edit'] = [
    'title' => 'Редактирование данных',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['reports_production_data_edit_form'],
    'access callback' => 'ext_user_has_roles',
    'access arguments' => [[ADMIN_RID, TRADE_HOUSE_USER_RID]],
    'type' => MENU_NORMAL_ITEM,
  ];

  return $items;
}

function reports_td_page()
{
  $output =  '<div class="section-title">' .
               '<h3>План-факт поступления денежных средств (в ' . DASH_REV_SUFFIX . ')</h3>' .
               '<div class="underline"></div>' .
             '</div>';
  $output .= '<div class="ajax-load" data-func="block_1"><div class="ajax-progress ajax-progress-throbber"><div class="throbber">&nbsp;</div><div class="message">Пожалуйста, подождите...</div></div></div>';

  $output .= '<div class="section-title">' .
               '<h3>Динамика поступления денежных средств год к году (в ' . DASH_REV_SUFFIX . ')</h3>' .
               '<div class="underline"></div>' .
             '</div>';
  $output .= '<div class="row">';
  $output .=   '<div class="col-xs-12 col-md-6">';
  $output .=     '<h5 class="chart-title">За месяц: ' . helper_month_label_ru(date('n')-1) . '</h5>';
  $output .=     '<div class="ajax-load" data-func="block_2" data-delay="200"><div class="ajax-progress ajax-progress-throbber"><div class="throbber">&nbsp;</div><div class="message">Пожалуйста, подождите...</div></div></div>';
  $output .=   '</div>';
  $output .=   '<div class="col-xs-12 col-md-6">';
  $output .=     '<h5 class="chart-title">С начала года: ' . helper_month_label_ru(1) . ' - ' . helper_month_label_ru(date('n')-1) . '</h5>';
  $output .=     '<div class="ajax-load" data-func="block_3" data-delay="400"><div class="ajax-progress ajax-progress-throbber"><div class="throbber">&nbsp;</div><div class="message">Пожалуйста, подождите...</div></div></div>';
  $output .=   '</div>';
  $period = dash_get_year_time_bounds(DASH_PERIOD_START_MONTH_TD);
  $output .=   '<div class="col-xs-12 col-md-6">';
  $output .=     '<h5 class="chart-title">За сезон: ' . helper_month_label_ru(DASH_PERIOD_START_MONTH_TD) . ' ' . date('Y', $period['from']) . ' - ' . helper_month_label_ru(date('n')-1) . ' ' . date('Y', $period['to']) . '</h5>';
  $output .=     '<div class="ajax-load" data-func="block_4" data-delay="600"><div class="ajax-progress ajax-progress-throbber"><div class="throbber">&nbsp;</div><div class="message">Пожалуйста, подождите...</div></div></div>';
  $output .=   '</div>';
  $output .= '</div>';

  $output .= '<div class="section-title">' .
               '<h3>План-факт отгрузки продукции (в ' . DASH_REV_SUFFIX . ')</h3>' .
               '<div class="underline"></div>' .
             '</div>';
  $output .= '<div class="ajax-load" data-func="block_5" data-delay="700"><div class="ajax-progress ajax-progress-throbber"><div class="throbber">&nbsp;</div><div class="message">Пожалуйста, подождите...</div></div></div>';

  $output .= '<div class="section-title">' .
               '<h3>План-факт производства продукции за ' . date('Y') . ' (в ' . DASH_PROD_SUFFIX . ')</h3>' .
               '<a class="edit-link autodialog" data-dialog-width="450" href="/data/production/edit">Редактировать данные</a>' .
               '<div class="underline"></div>' .
             '</div>';
  $output .= '';
  $output .= '<div class="ajax-load" data-func="block_6" data-delay="800"><div class="ajax-progress ajax-progress-throbber"><div class="throbber">&nbsp;</div><div class="message">Пожалуйста, подождите...</div></div></div>';


  return '<div class="charts" data-module="reports">' . $output . '</div>';
}

function reports_block_1()
{
  $period = dash_get_year_time_bounds(1);

  // план-факт выручки помесячно линейный
  $output = '<div class="row">';
  $data_arr =   reports_line_revenue_plan_fact($period);
  $output .=    '<div id="plan-fact-target" class="col-xs-12">' . drupal_render($data_arr) . '</div>';
  $output .= '</div>';

  return $output;
}

function reports_block_2()
{
  // период с начала предыдущего месяца по начало текущего месяца
  $period = [
    'from' => gmmktime(0, 0, 0, date('n')-1, 1, date('Y')),
    'to' => gmmktime(0, 0, 0, date('n'), 1, date('Y')),
    'end' => gmmktime(0, 0, 0, date('n'), 1, date('Y')),
  ];

  // факт поступления выручки за последний полный месяц
  $data_arr = reports_column_revenue_fact_compare($period);

  return drupal_render($data_arr);
}

function reports_block_3()
{
  // период с начала года по начало текущего месяца
  $period = dash_get_year_time_bounds(1);

  // факт поступления выручки
  $data_arr = reports_column_revenue_fact_compare($period);

  return drupal_render($data_arr);
}

function reports_block_4()
{
  // период с начала сезона
  $period = dash_get_year_time_bounds(DASH_PERIOD_START_MONTH_TD);

  // факт поступления выручки
  $data_arr = reports_column_revenue_fact_compare($period);

  return drupal_render($data_arr);
}

function reports_block_5()
{
  // период с начала года по начало текущего месяца
  $period = dash_get_year_time_bounds(1);

  // план-факт отгрузки продукции
  $data_arr = reports_line_ship_plan_fact($period);

  return drupal_render($data_arr);
}

function reports_block_6()
{
  // период с начала года по начало текущего месяца
  $period = dash_get_year_time_bounds(1);

  // план-факт отгрузки продукции
  $data_arr = reports_column_production_plan_fact($period);

  return drupal_render($data_arr);
}

/**
 * ----- Подготовка графика --------------------------------------------------------------------------------------------
 */
function reports_line_revenue_plan_fact($period)
{
  $chart = dash_get_no_data_chart();

  $plan_bounds = ['from' => $period['from'], 'to' => $period['end']];

  // собрать все записи за период
  $plan = dash_get_revenue_plan_fact_by_conditions(['type' => DASH_TYPE_PLAN, 'period' => $plan_bounds]);
  $fact = dash_get_revenue_plan_fact_by_conditions(['type' => DASH_TYPE_FACT, 'period' => $period]);

  if ($plan || $fact) {
    // сгруппировать помесячно
    $plan_fact_by_month = [];
    foreach (dash_get_months_list($period) as $month) {
      $plan_fact_by_month[$month['start']] = [
        'plan_amount' => 0,
        'fact_amount' => 0,
        'start' => $month['start'],
        'end' => $month['end'],
      ];

      foreach ($plan as $record) {
        if ($record->date >= $month['start'] && $record->date < $month['end']) {
          $plan_fact_by_month[$month['start']]['plan_amount'] += $record->amount;
        }
      }
      foreach ($fact as $record) {
        if ($record->date >= $month['start'] && $record->date < $month['end']) {
          $plan_fact_by_month[$month['start']]['fact_amount'] += $record->amount;
        }
      }
    }
    ksort($plan_fact_by_month);

    $chart = array(
      '#type' => 'chart',
      '#chart_type' => 'line',
      '#chart_id' => 'reports_line_revenue_plan_fact',
      '#font' => 'Montserrat',
      '#height' => '350',
      '#legend_position' => 'top',
      '#raw_options' => [
        'titleTextStyle' => ['bold' => 'true', 'fontSize' => '16'],
        'crosshair' => ['trigger' => 'both', 'orientation' => 'vertical'],
        'annotations' => [
          'datum' => ['stem' => ['color' => 'transparent']],
          'textStyle' => ['fontSize' => 14, 'bold' => 'true'],
        ],
        'chartArea' => [
          'width' => '90%',
          'left' => 70,
        ],
        'tooltip' => ['isHtml' => true],
      ],
      'xaxis' => [
        '#type' => 'chart_xaxis',
      ],
      'yaxis' => [
        '#type' => 'chart_yaxis',
        '#min' => 0,
      ],
      'plan' => [
        '#type' => 'chart_data',
        '#title' => 'План',
        '#raw_options' => [
          'pointSize' => 5,
          'annotations' => ['stem' => ['color' => 'transparent', 'length' => -30]],
        ],
        '#data' => [],
      ],
      'fact' => [
        '#type' => 'chart_data',
        '#title' => 'Факт',
        '#raw_options' => [
          'pointSize' => 5,
          'annotations' => ['stem' => ['color' => 'transparent', 'length' => 30]],
        ],
        '#data' => [],
      ],
    );

    $total_plan = $total_fact = 0;
    $last_plan = $last_fact = 0;
    foreach ($plan_fact_by_month as $month) {
      $chart['xaxis']['#labels'][] = helper_month_label_ru(date('n', $month['start']));

      $plan = $month['plan_amount'] / DASH_REV_DIVIDER;
      $fact = $month['fact_amount'] / DASH_REV_DIVIDER;
      $total_plan += $plan;
      $total_fact += $fact;
      // если это текущий период,
      // то считаем и выводим накопительный факт только до месяца предстоящего текущему месяцу
      $total_fact = ($month['start'] < gmmktime(0, 0, 0, date('n'), 1, date('Y'))) ? $total_fact : null;

      $chart['plan']['#data'][] = $total_plan;
      $chart['fact']['#data'][] = $total_fact;

      // запоминаем последнее значение для определения цвета графика
      if (isset($total_fact)) {
        $last_fact = $total_fact;
        $last_plan = $total_plan;
      }

      $tooltip = '<div style="padding: 8px 12px; min-width:140px;white-space: nowrap;">' .
        '<div><div style="display:inline-block; font-weight: 700;">' . helper_month_label_ru(date('n', $month['start'])) . '</div></div>' .
        '<div><div style="display:inline-block; width: 210px;">План:</div><div style="display:inline-block; text-align: right; width: 110px;"><b>' . number_format($plan, 2, ',', ' ') . '</b>&nbsp;млн.</div></div>' .
        '<div><div style="display:inline-block; width: 210px;">Факт:</div><div style="display:inline-block; text-align: right; width: 110px;"><b>' . number_format($fact, 2, ',', ' ') . '</b>&nbsp;млн.</div></div>' .
        '<div><div style="display:inline-block; width: 210px;">Выполнение:</div><div style="display:inline-block; text-align: right; width: 110px;"><b>' . number_format($fact/$plan*100, 0, ',', ' ') . '</b>&nbsp;%</div></div>' .
        '<div>&nbsp;</div>' .
        '<div><div style="display:inline-block; font-weight: 700;">Накопительный итог</div></div>' .
        '<div><div style="display:inline-block; width: 210px;">План:</div><div style="display:inline-block; text-align: right; width: 110px;"><b>' . number_format($total_plan, 2, ',', ' ') . '</b>&nbsp;млн.</div></div>' .
        '<div><div style="display:inline-block; width: 210px;">Факт:</div><div style="display:inline-block; text-align: right; width: 110px;"><b>' . number_format($last_fact, 2, ',', ' ') . '</b>&nbsp;млн.</div></div>' .
        '<div><div style="display:inline-block; width: 210px;">Выполнение:</div><div style="display:inline-block; text-align: right; width: 110px;"><b>' . number_format($last_fact/$total_plan*100, 0, ',', ' ') . '</b>&nbsp;%</div></div>' .
        '</div>';

      $chart['fact'][] = array(
        '#type' => 'chart_data_item',
        '#title' => $tooltip,
        '#raw_options' => [
          'annotation' => $total_fact ? number_format($total_fact, 0, null, ' ') : null,
        ],
      );
      $chart['plan'][] = array(
        '#type' => 'chart_data_item',
        '#title' => $tooltip,
        '#raw_options' => [
          'annotation' => $total_plan ? number_format($total_plan, 0, null, ' ') : null,
        ],
      );
    }
  }

  // определить цвет графика
  if ($last_fact > $last_plan) {
    $chart['#colors'] = [DASH_COLOR_BLUE, DASH_COLOR_LIGHT_GREEN];
  } else {
    $chart['#colors'] = [DASH_COLOR_BLUE, DASH_COLOR_DARK_RED];
  }

  return $chart;
}

function reports_column_revenue_fact_compare($period)
{
  $chart = dash_get_no_data_chart();

  // собрать данные периодов с DASH_YEAR_HISTORY_START года
  $data = [];
  foreach (dash_get_years_shift_list($period, date('n', $period['from'])) as $shift) {
    $period_shifted = dash_get_period_shifted($period, $shift);

    $fact = dash_get_revenue_plan_fact_by_conditions(['type' => DASH_TYPE_FACT, 'period' => $period_shifted]);

    $amount = 0;
    if ($fact) foreach ($fact as $record) {
      $amount += $record->amount;
    }

    if ($amount) {
    $data[date('Y', $period_shifted['from'])] = [
      'amount' => $amount / DASH_REV_DIVIDER,
    ];
    }
  }

  if ($data) {
    $chart = array(
      '#type' => 'chart',
      '#chart_type' => 'column',
      '#font' => 'Montserrat',
      '#height' => '500',
      'xaxis' => [
        '#type' => 'chart_xaxis',
      ],
      'yaxis' => [
        '#type' => 'chart_yaxis',
        '#min' => 0,
      ],
      '#raw_options' => [
        'titleTextStyle' => ['bold' => 'true', 'fontSize' => '16'],
        'legend' => ['position' => 'top', 'textStyle' => ['fontSize' => '12']],
        'chartArea' => ['height' => '80%', 'width' => '85%', 'left' => 70],
        'annotations' => [
          'textStyle' => ['fontSize' => 14, 'bold' => 'true'],
        ],
        'tooltip' => ['isHtml' => true],
        'bar' => ['groupWidth' => "70%"],
        'isStacked' => 'true',
      ],
    );

    // чтобы была возможность подписать столбцы и вывести их в разном цвете,
    // график выполнен в виде размещённых друг на друге значений за года,
    // где реальное значение только у нужного года, а остальные имеют значение null
    $year_prev = 0;
    $tooltip = '';
    foreach ($data as $year_1 => $item_1) {
      $chart[$year_1] = [
        '#type' => 'chart_data',
        '#title' => (string)$year_1,
        '#data' => [],
      ];
      foreach ($data as $year_2 => $item_2) {
        if ($year_1 == $year_2) {
          $chart['xaxis']['#labels'][] = (string)$year_1;
          $chart[$year_1]['#data'][] = $item_1['amount'];


          $delta = $data[$year_1]['amount'] - $data[$year_prev]['amount'];
          $percent = $year_prev ? number_format(abs($delta) / $data[$year_prev]['amount'] * 100, 0, ',', ' ') : '-';
          $tooltip =
            '<div style="padding: 8px 12px; min-width:140px;white-space: nowrap;">' .
            '<div><div style="display:inline-block; font-weight: 700;">' . $year_1 . '</div></div>' .
            '<div><div style="display:inline-block; width: 60px;">' . ($delta > 0 ? 'Рост' : 'Падение') . ':</div><div style="display:inline-block; text-align: right; width: 110px;"><b>' . $percent . '</b>&nbsp;%</div></div>' .
            '</div>';

          $year_prev = $year_1;
        } else {
          $chart[$year_1]['#data'][] = null;
        }

        $chart[$year_1][] = array(
          '#type' => 'chart_data_item',
          '#title' => $tooltip,
          '#raw_options' => [
            'annotation' => number_format($item_1['amount'], 1, ',', ' '),
          ],
        );

      }
    }
  }

  return $chart;
}

function reports_line_ship_plan_fact($period)
{
  $chart = dash_get_no_data_chart();

  $plan_bounds = ['from' => $period['from'], 'to' => $period['end']];

  // собрать все записи за период
  $plan = dash_get_ship_plan_fact_by_conditions(['type' => DASH_TYPE_PLAN, 'period' => $plan_bounds]);
  $fact = dash_get_ship_plan_fact_by_conditions(['type' => DASH_TYPE_FACT, 'period' => $period]);

  if ($plan || $fact) {
    // сгруппировать помесячно
    $plan_fact_by_month = [];
    foreach (dash_get_months_list($period) as $month) {
      $plan_fact_by_month[$month['start']] = [
        'plan_amount' => 0,
        'fact_amount' => 0,
        'start' => $month['start'],
        'end' => $month['end'],
      ];

      foreach ($plan as $record) {
        if ($record->date >= $month['start'] && $record->date < $month['end']) {
          $plan_fact_by_month[$month['start']]['plan_amount'] += $record->amount;
        }
      }
      foreach ($fact as $record) {
        if ($record->date >= $month['start'] && $record->date < $month['end']) {
          $plan_fact_by_month[$month['start']]['fact_amount'] += $record->amount;
        }
      }
    }
    ksort($plan_fact_by_month);

    $chart = array(
      '#type' => 'chart',
      '#chart_type' => 'line',
      '#font' => 'Montserrat',
      '#height' => '350',
      '#legend_position' => 'top',
      '#raw_options' => [
        'titleTextStyle' => ['bold' => 'true', 'fontSize' => '16'],
        'crosshair' => ['trigger' => 'both', 'orientation' => 'vertical'],
        'annotations' => [
          'datum' => ['stem' => ['color' => 'transparent']],
          'textStyle' => ['fontSize' => 14, 'bold' => 'true'],
        ],
        'chartArea' => [
          'width' => '90%',
          'left' => 70,
        ],
        'tooltip' => ['isHtml' => true],
      ],
      'xaxis' => [
        '#type' => 'chart_xaxis',
      ],
      'yaxis' => [
        '#type' => 'chart_yaxis',
        '#min' => 0,
      ],
      'plan' => [
        '#type' => 'chart_data',
        '#title' => 'План',
        '#raw_options' => [
          'pointSize' => 5,
          'annotations' => ['stem' => ['color' => 'transparent', 'length' => -40]],
        ],
        '#data' => [],
      ],
      'fact' => [
        '#type' => 'chart_data',
        '#title' => 'Факт',
        '#raw_options' => [
          'pointSize' => 5,
          'annotations' => ['stem' => ['color' => 'transparent', 'length' => 40]],
        ],
        '#data' => [],
      ],
    );

    $total_plan = $total_fact = 0;
    $last_plan = $last_fact = 0;
    foreach ($plan_fact_by_month as $month) {
      $chart['xaxis']['#labels'][] = helper_month_label_ru(date('n', $month['start']));

      $plan = $month['plan_amount'] / DASH_REV_DIVIDER;
      $fact = $month['fact_amount'] / DASH_REV_DIVIDER;
      $total_plan += $plan;
      $total_fact += $fact;
      // если это текущий период,
      // то считаем и выводим накопительный факт только до месяца предстоящего текущему месяцу
      $total_fact = ($month['start'] < gmmktime(0, 0, 0, date('n'), 1, date('Y'))) ? $total_fact : null;

      $chart['plan']['#data'][] = $total_plan;
      $chart['fact']['#data'][] = $total_fact;

      // запоминаем последнее значение для определения цвета графика
      if (isset($total_fact)) {
        $last_fact = $total_fact;
        $last_plan = $total_plan;
      }

      $tooltip = '<div style="padding: 8px 12px; min-width:140px;white-space: nowrap;">' .
        '<div><div style="display:inline-block; font-weight: 700;">' . helper_month_label_ru(date('n', $month['start'])) . '</div></div>' .
        '<div><div style="display:inline-block; width: 210px;">План:</div><div style="display:inline-block; text-align: right; width: 110px;"><b>' . number_format($plan, 2, ',', ' ') . '</b>&nbsp;млн.</div></div>' .
        '<div><div style="display:inline-block; width: 210px;">Факт:</div><div style="display:inline-block; text-align: right; width: 110px;"><b>' . number_format($fact, 2, ',', ' ') . '</b>&nbsp;млн.</div></div>' .
        '<div><div style="display:inline-block; width: 210px;">Выполнение:</div><div style="display:inline-block; text-align: right; width: 110px;"><b>' . number_format($fact/$plan*100, 0, ',', ' ') . '</b>&nbsp;%</div></div>' .
        '<div>&nbsp;</div>' .
        '<div><div style="display:inline-block; font-weight: 700;">Накопительный итог</div></div>' .
        '<div><div style="display:inline-block; width: 210px;">План:</div><div style="display:inline-block; text-align: right; width: 110px;"><b>' . number_format($total_plan, 2, ',', ' ') . '</b>&nbsp;млн.</div></div>' .
        '<div><div style="display:inline-block; width: 210px;">Факт:</div><div style="display:inline-block; text-align: right; width: 110px;"><b>' . number_format($last_fact, 2, ',', ' ') . '</b>&nbsp;млн.</div></div>' .
        '<div><div style="display:inline-block; width: 210px;">Выполнение:</div><div style="display:inline-block; text-align: right; width: 110px;"><b>' . number_format($last_fact/$total_plan*100, 0, ',', ' ') . '</b>&nbsp;%</div></div>' .
        '</div>';

      $chart['fact'][] = array(
        '#type' => 'chart_data_item',
        '#title' => $tooltip,
        '#raw_options' => [
          'annotation' => $total_fact ? number_format($total_fact, 0, null, ' ') : null,
        ],
      );
      $chart['plan'][] = array(
        '#type' => 'chart_data_item',
        '#title' => $tooltip,
        '#raw_options' => [
          'annotation' => $total_plan ? number_format($total_plan, 0, null, ' ') : null,
        ],
      );
    }
  }

  // определить цвет графика
  if ($last_fact > $last_plan) {
    $chart['#colors'] = [DASH_COLOR_BLUE, DASH_COLOR_LIGHT_GREEN];
    $chart['fact']['#raw_options']['annotations']['stem']['length'] = 40;
    $chart['plan']['#raw_options']['annotations']['stem']['length'] = -40;
  } else {
    $chart['#colors'] = [DASH_COLOR_BLUE, DASH_COLOR_DARK_RED];
    $chart['fact']['#raw_options']['annotations']['stem']['length'] = -40;
    $chart['plan']['#raw_options']['annotations']['stem']['length'] = 40;
  }

  return $chart;
}

function reports_column_production_plan_fact($period)
{
  $chart = dash_get_no_data_chart();

  // собрать все записи за период
  if ($data = dash_get_production_plan_fact_by_conditions(['period' => $period, 'manual' => 1])) {
    // сгруппировать помесячно
    $plan_fact_by_month = [];
    foreach (dash_get_months_list($period) as $month) {
      $plan_fact_by_month[$month['start']] = [
        'plan_output' => 0,
        'fact_output' => 0,
        'start' => $month['start'],
        'end' => $month['end'],
      ];

      foreach ($data as $record) {
        if ($record->date >= $month['start'] && $record->date < $month['end']) {
          if ($record->fact) $plan_fact_by_month[$month['start']]['fact_output'] += $record->output;
          else               $plan_fact_by_month[$month['start']]['plan_output'] += $record->output;
        }
      }
    }
    ksort($plan_fact_by_month);

    $chart = array(
      '#type' => 'chart',
      '#chart_type' => 'column',
      '#font' => 'Montserrat',
      '#height' => '350',
      '#legend_position' => 'top',
      '#raw_options' => [
        'titleTextStyle' => ['bold' => 'true', 'fontSize' => '16'],
        'crosshair' => ['trigger' => 'both', 'orientation' => 'vertical'],
        'annotations' => [
          'datum' => ['stem' => ['color' => 'transparent']],
          'textStyle' => ['fontSize' => 14, 'bold' => 'true'],
        ],
        'chartArea' => [
          'width' => '90%',
          'left' => 70,
        ],
        'tooltip' => ['isHtml' => true],
      ],
      'xaxis' => [
        '#type' => 'chart_xaxis',
      ],
      'yaxis' => [
        '#type' => 'chart_yaxis',
        '#min' => 0,
      ],
      'plan' => [
        '#type' => 'chart_data',
        '#title' => 'План',
        '#data' => [],
      ],
      'fact' => [
        '#type' => 'chart_data',
        '#title' => 'Факт',
        '#data' => [],
      ],
    );

    foreach ($plan_fact_by_month as $month) {
      if ($month['plan_output'] || $month['fact_output']) {
        $chart['xaxis']['#labels'][] = helper_month_label_ru(date('n', $month['start']));

        $plan = $month['plan_output'] / DASH_PROD_DIVIDER;
        $fact = $month['fact_output'] / DASH_PROD_DIVIDER;

        $chart['plan']['#data'][] = $plan;
        $chart['fact']['#data'][] = $fact;

        $tooltip = '<div style="padding: 8px 12px; min-width:140px;white-space: nowrap;">' .
          '<div><div style="display:inline-block; font-weight: 700;">' . helper_month_label_ru(date('n', $month['start'])) . '</div></div>' .
          '<div><div style="display:inline-block; width: 210px;">План:</div><div style="display:inline-block; text-align: right; width: 110px;"><b>' . number_format($plan, 2, ',', ' ') . '</b>&nbsp;' . DASH_PROD_SUFFIX . '</div></div>' .
          '<div><div style="display:inline-block; width: 210px;">Факт:</div><div style="display:inline-block; text-align: right; width: 110px;"><b>' . number_format($fact, 2, ',', ' ') . '</b>&nbsp;' . DASH_PROD_SUFFIX . '</div></div>' .
          '<div><div style="display:inline-block; width: 210px;">Выполнение:</div><div style="display:inline-block; text-align: right; width: 110px;"><b>' . ($plan ? number_format($fact/$plan*100, 0, ',', ' ') : '-') . '</b>&nbsp;%</div></div>' .
          '</div>';

        $chart['fact'][] = array(
          '#type' => 'chart_data_item',
          '#title' => $tooltip,
          '#raw_options' => [
            'annotation' => $fact ? number_format($fact, 0, null, ' ') : null,
          ],
        );
        $chart['plan'][] = array(
          '#type' => 'chart_data_item',
          '#title' => $tooltip,
          '#raw_options' => [
            'annotation' => $plan ? number_format($plan, 0, null, ' ') : null,
          ],
        );
      }
    }
  }

  return $chart;
}


/**
 * ----- Формы --------------------------------------------------------------------------------------------------------
 */

function reports_production_data_edit_form($form, &$form_state)
{
  $form = [
    '#prefix' => '<div id="data-production-edit-wrapper" class="data-production-edit-wrapper">',
    '#suffix' => '</div>',
  ];

  $intro = '<p>Форма позволяет добавлять новые и&nbsp;редактировать ранее введённые данные</p>';

  $form['intro'] = [
    '#markup' => '<div class="intro">' . $intro . '</div>',
    '#attached' => ['js' => [[
      'data' => ['messages' => ['position' => 'inline']],
      'type' => 'setting',
    ]]],
  ];

  $options_m = [0 => ' - Месяц - '];
  for($i = 1; $i <= 12; $i++) {
    $options_m[$i] = helper_month_label_ru($i);
  }
  $form['month']['month'] = [
    '#type' => 'select',
    '#options' => $options_m,
    '#default_value' => 0,
    '#prefix' => '<div class="row"><div class="col-xs-7">',
    '#suffix' => '</div>',
    '#ajax' => [
      'callback' => 'reports_production_data_edit_form_callback',
      'wrapper' => 'data-production-edit-wrapper',
    ],
  ];

  $options_y = [0 => ' - Год - '];
  for($i = DASH_HISTORY_START_YEAR_TD; $i <= date('Y'); $i++) {
    $options_y[$i] = $i;
  }
  $form['month']['year'] = [
    '#type' => 'select',
    '#options' => $options_y,
    '#default_value' => 0,
    '#prefix' => '<div class="col-xs-5">',
    '#suffix' => '</div>',
    '#ajax' => [
      'callback' => 'reports_production_data_edit_form_callback',
      'wrapper' => 'data-production-edit-wrapper',
    ],
  ];

  $form['fact'] = [
    '#type' => 'select',
    '#title' => 'Тип записи',
    '#options' => [0 => 'План', 1 => 'Факт'],
    '#prefix' => '<div class="col-xs-6">',
    '#suffix' => '</div>',
    '#ajax' => [
      'callback' => 'reports_production_data_edit_form_callback',
      'wrapper' => 'data-production-edit-wrapper',
    ],
  ];

  // если изменены месяц/год, определить наличие данных
  $is_month_selected = false;
  $record_id = 0;
  if (isset($form_state['triggering_element']['#name']) && in_array($form_state['triggering_element']['#name'], ['month', 'year', 'fact'])) {
    $volume_default = 0;
    if ($form_state['values']['month'] && $form_state['values']['year']) $is_month_selected = true;

    if ($is_month_selected) {
      $period = [
        'from' => gmmktime(0, 0, 0, (int)$form_state['values']['month'], 1, (int)$form_state['values']['year']),
        'to' => gmmktime(0, 0, 0, (int)$form_state['values']['month']+1, 1, (int)$form_state['values']['year']),
      ];
      if ($data = dash_get_production_plan_fact_by_conditions(['period' => $period, 'manual' => 1, 'fact' => $form_state['values']['fact']])) {
        $record = reset($data);
        $volume_default = $record->output;
        $record_id = $record->id;
      }
    }
    $form_state['input']['volume'] = $volume_default;
    $form_state['values']['volume'] = $volume_default;
  }


  // id записи, если найдена существующая
  $form['record'] = [
    '#type' => 'hidden',
    '#value' => $record_id,
  ];

  $form['volume'] = [
    '#type' => 'textfield',
    '#size' => 20,
    '#title' => 'Объём (л/кг/шт)',
    '#required' => true,
    '#default_value' => 0,
    '#disabled' => !$is_month_selected,
    '#prefix' => '<div class="col-xs-6">',
    '#suffix' => '</div></div>',
  ];

  $form['actions'] = ['#type' => 'actions'];
  $form['actions']['submit'] = [
    '#type' => 'submit',
    '#value' => 'Отправить',
    '#attributes' => ['class' => ['btn-primary', 'btn-wide']],
    '#disabled' => !$is_month_selected,
    '#ajax' => [
      'callback' => 'reports_production_data_edit_form_callback',
      'wrapper' => 'data-production-edit-wrapper',
    ],
  ];

  return $form;
}
function reports_production_data_edit_form_callback($form, $form_state)
{
  return $form;
}
function reports_production_data_edit_form_submit($form, $form_state)
{
  $month_start = gmmktime(0, 0, 0, (int)$form_state['values']['month'], 1, (int)$form_state['values']['year']);

  // todo удалить старые записи за месяц
  if ($form_state['values']['record']) {
    entity_delete('plan', $form_state['values']['record']);
  }

  // добавить Запись плана
  $record = dash_plan_plan_create([
    'created' => REQUEST_TIME,
    'month_ts' => $month_start,
    'nom_id' => 0,
    'fact' => $form_state['values']['fact'],
    'manual' => 1,
    'volume' => $form_state['values']['volume'],
  ]);

  // todo обновление графика
  ctools_include('ajax');
  ctools_add_js('ajax-responder');
  $output = '<div class="ajax-load" data-func="block_6"><div class="ajax-progress ajax-progress-throbber"><div class="throbber">&nbsp;</div><div class="message">Пожалуйста, подождите...</div></div></div>';
  $commands[] = ajax_command_invoke('.autodialog-content', 'dialog', array('close'));
  $commands[] = ajax_command_replace('[data-func="block_6"]', $output);
  print ajax_render($commands);
  drupal_exit();
}

/**
 * Создать Запись плана типа plan
 */
function dash_plan_plan_create($params)
{
  $transaction = db_transaction();
  try {
    $plan = entity_create('plan', [
      'type' => 'plan',
      'created' => $params['created'],
    ]);
    entity_save('plan', $plan);

    $plan_wr = entity_metadata_wrapper('plan', $plan);
    $plan_wr->field_date = $params['month_ts'];
    $plan_wr->field_nomenklatura = $params['nom_id'];
    $plan_wr->field_is_fact = $params['fact'];
    $plan_wr->field_is_manual = $params['manual'];
    $plan_wr->field_output = $params['volume'];
    $plan_wr->save();
  } catch (Exception $e) {
    $transaction->rollback();
    watchdog_exception('migration', $e);
  }

  return $plan ?? false;
}

/**
 * Удалить Записи План (план), все или за месяц
 * @param $month_ts
 */
function dash_plan_plan_delete_all($month_ts = null)
{
  $efquery = new EntityFieldQuery();
  $efquery->entityCondition('entity_type', 'plan');
  $efquery->entityCondition('bundle', 'plan');
  if ($month_ts) {
    $efquery->fieldCondition('field_date', 'value', $month_ts);
  }
  $result = $efquery->execute();
  if ($result) {
    entity_delete_multiple('plan', array_keys($result['plan']));
  }
}
