<?php

// постоянное подключение, т.к в файле есть функции для ajax вызовов
include ('includes/td.reports.inc');
include ('includes/st.reports.inc');

/**
 * Implementation of hook_menu().
 */
function reports_menu()
{
  $items['reports'] = array(
    'title' => 'Отчёты',
    'menu_name' => 'main-menu',
    'expanded' => true,
    'weight' => 15,
    'page callback' => 'drupal_get_form',
    'page arguments' => ['reports_td_period_to_form'],
    'access callback' => 'ext_user_has_roles',
    'access arguments' => [[ADMIN_RID, TRADE_HOUSE_USER_RID]],
  );
  $items['reports/td'] = array(
    'title' => 'Торговый Дом',
    'menu_name' => 'main-menu',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['reports_td_period_to_form'],
    'access callback' => 'ext_user_has_roles',
    'access arguments' => [[ADMIN_RID, TRADE_HOUSE_USER_RID]],
    'weight' => 17,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['reports/st'] = array(
    'title' => 'Страда',
    'menu_name' => 'main-menu',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['reports_st_period_form'],
    'access callback' => 'ext_user_has_roles',
    'access arguments' => [[ADMIN_RID, TRADE_HOUSE_USER_RID]],
    'weight' => 18,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['data/plan-prod/edit'] = [
    'title' => 'Редактирование данных',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['reports_plan_prod_data_edit_form'],
    'access callback' => 'ext_user_has_roles',
    'access arguments' => [[ADMIN_RID, TRADE_HOUSE_USER_RID]],
    'type' => MENU_NORMAL_ITEM,
  ];
  $items['data/plan-ship/edit'] = [
    'title' => 'Редактирование данных',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['reports_plan_ship_data_edit_form'],
    'access callback' => 'ext_user_has_roles',
    'access arguments' => [[ADMIN_RID, TRADE_HOUSE_USER_RID]],
    'type' => MENU_NORMAL_ITEM,
  ];

  $items['data/cash-income/edit'] = [
    'title' => 'Редактирование данных',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['reports_cash_income_data_edit_form'],
    'access callback' => 'ext_user_has_roles',
    'access arguments' => [[ADMIN_RID, TRADE_HOUSE_USER_RID]],
    'type' => MENU_NORMAL_ITEM,
  ];

  $items['data/ship/edit'] = [
    'title' => 'Редактирование данных',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['reports_ship_data_edit_form'],
    'access callback' => 'ext_user_has_roles',
    'access arguments' => [[ADMIN_RID, TRADE_HOUSE_USER_RID]],
    'type' => MENU_NORMAL_ITEM,
  ];

  $items['data/debt/edit'] = [
    'title' => 'Редактирование данных',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['reports_debt_data_edit_form'],
    'access callback' => 'ext_user_has_roles',
    'access arguments' => [[ADMIN_RID, TRADE_HOUSE_USER_RID]],
    'type' => MENU_NORMAL_ITEM,
  ];

  $items['data/manual-bdr/edit'] = [
    'title' => 'Редактирование данных',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['reports_manual_bdr_data_edit_form'],
    'access callback' => 'ext_user_has_roles',
    'access arguments' => [[ADMIN_RID, TRADE_HOUSE_USER_RID]],
    'type' => MENU_NORMAL_ITEM,
  ];

  return $items;
}

/**
 * hook_import_processors_alter
 */
function reports_import_processors_alter(&$processors)
{
  $path = drupal_get_path('module', 'reports') . '/includes/';

  // Справочник Статей расходов
  $processors['first_queue'][] = ['mask' => '/^scrum_hb_outcome_categories_.*\.json/',  'include' => $path . 'import.reports.inc', 'func' => 'reports_outcome_categories_import', 'archive' => 'dash/rp'];

  // План и факт расхода ДС
  $processors['last_queue'][] = ['mask' => '/^scrum_cash_outcome_.*\.json/',            'include' => $path . 'import.reports.inc', 'func' => 'reports_cash_outcome_import', 'archive' => 'dash/rp'];
  // Кредиты и задолженности (из бухгалтерии)
  $processors['last_queue'][] = ['mask' => '/^scrum_debt_.*\.json/',                    'include' => $path . 'import.reports.inc', 'func' => 'reports_debt_import', 'archive' => 'dash/rp'];
  // Остатки готовой продукции и сырья
  $processors['last_queue'][] = ['mask' => '/^scrum_remains_brief_\d.*\.json/',         'include' => $path . 'import.reports.inc', 'func' => 'reports_remains_brief_import', 'archive' => 'dash/rp'];
}

/**
 * ----- Формы --------------------------------------------------------------------------------------------------------
 */

function reports_manual_bdr_data_edit_form($form, &$form_state)
{
  // сохраняем блоки, которые нужно обновить
  if (!empty($_GET["blocks"])) {
    $form_state['blocks'] = $_GET["blocks"];
  }

  // определяем ID компании, для которой заполняется форма
  if (empty($form_state["values"]['company_id'])) {
    $company_id = $_GET["inn"] ?? null;
    if (isset($company_id)) {
      $company = dash_term_get_by_1c_id('companies', $_GET["inn"]);
      $company_id = $company->tid;
    }
  } else $company_id = $form_state["values"]['company_id'];

  $form = [
    '#prefix' => '<div id="data-manual-bdr-edit-wrapper" class="data-manual-bdr-edit-wrapper">',
    '#suffix' => '</div>',
  ];

  if (empty($company_id)) {
    $intro = '<p>Не задан идентификатор компании. Обратитесь к администратору сайта.</p>';
    $form['intro'] = ['#markup' => '<div class="intro">' . $intro . '</div>'];

    return $form;
  }

  $intro = '<p>Форма позволяет добавлять новые и&nbsp;редактировать ранее введённые данные. Только числовые значения. Рублёвые значения в млн без НДС.</p>';
  $form['intro'] = [
    '#markup' => '<div class="intro">' . $intro . '</div>',
    '#attached' => ['js' => [[
      'data' => ['messages' => ['position' => 'inline']],
      'type' => 'setting',
    ]]],
  ];

  $options_m = [0 => ' - Месяц - '];
  for($i = 1; $i <= 12; $i++) {
    $options_m[$i] = helper_month_label_ru($i);
  }
  $form['month']['month'] = [
    '#type' => 'select',
    '#options' => $options_m,
    '#default_value' => 0,
    '#prefix' => '<div class="row"><div class="col-xs-7 col-md-5">',
    '#suffix' => '</div>',
    '#ajax' => [
      'callback' => 'reports_manual_bdr_data_edit_form_callback',
      'wrapper' => 'data-manual-bdr-edit-wrapper',
    ],
  ];

  $options_y = [0 => ' - Год - '];
  for($i = DASH_HISTORY_START_YEAR_TD; $i <= date('Y'); $i++) {
    $options_y[$i] = $i;
  }
  $form['month']['year'] = [
    '#type' => 'select',
    '#options' => $options_y,
    '#default_value' => 0,
    '#prefix' => '<div class="col-xs-5 col-md-4">',
    '#suffix' => '</div>',
    '#ajax' => [
      'callback' => 'reports_manual_bdr_data_edit_form_callback',
      'wrapper' => 'data-manual-bdr-edit-wrapper',
    ],
  ];

  $form['type'] = [
    '#type' => 'select',
    '#options' => [DASH_TYPE_PLAN => 'План', DASH_TYPE_FACT => 'Факт'],
    '#prefix' => '<div class="col-xs-12 col-md-3">',
    '#suffix' => '</div>',
    '#ajax' => [
      'callback' => 'reports_manual_bdr_data_edit_form_callback',
      'wrapper' => 'data-manual-bdr-edit-wrapper',
    ],
  ];

  $options_c = [];
  $terms = taxonomy_get_tree(taxonomy_vocabulary_machine_name_load('bdr')->vid);
  foreach ($terms as $term) {
    $label = $term->name;
    if ($term->depth) {
      $label = ' ' . $label;
      for($i=1; $i <= $term->depth; $i++) { $label = '-' . $label; }
    }
    $options_c[$term->tid] = $label;
  }
  $form['category'] = [
    '#type' => 'select',
    '#title' => 'Статья бюджета',
    '#options' => $options_c,
    '#prefix' => '<div class="col-xs-6">',
    '#suffix' => '</div>',
    '#ajax' => [
      'callback' => 'reports_manual_bdr_data_edit_form_callback',
      'wrapper' => 'data-manual-bdr-edit-wrapper',
    ],
  ];

  // если изменены месяц/год, определить наличие данных
  $is_month_selected = false;
  $record_id = 0;
  if (isset($form_state['triggering_element']['#name']) && in_array($form_state['triggering_element']['#name'], ['month', 'year', 'type', 'category'])) {
    $amount_default = 0;
    if ($form_state['values']['month'] && $form_state['values']['year']) $is_month_selected = true;

    if ($is_month_selected) {
      $period = [
        'from' => gmmktime(0, 0, 0, (int)$form_state['values']['month'], 1, (int)$form_state['values']['year']),
        'to' => gmmktime(0, 0, 0, (int)$form_state['values']['month']+1, 1, (int)$form_state['values']['year']),
      ];
      if ($data = dash_manual_bdr_get_by_conditions(['company_id' => $company_id, 'period' => $period, 'type' => $form_state['values']['type'],'category_id' => $form_state['values']['category']])) {
        $record = reset($data);
        $amount_default = $record->amount;
        $record_id = $record->id;
      }
    }
    $form_state['input']['amount'] = $amount_default;
    $form_state['values']['amount'] = $amount_default;
  }

  // id записи, если найдена существующая
  $form['record'] = [
    '#type' => 'hidden',
    '#value' => $record_id,
  ];
  // от какой компании создаётся запись
  $form['company_id'] = [
    '#type' => 'hidden',
    '#value' => $company_id,
  ];

  $form['amount'] = [
    '#type' => 'textfield',
    '#size' => 20,
    '#title' => 'Числовое значение',
    '#required' => true,
    '#default_value' => '',
    '#disabled' => !$is_month_selected,
    '#prefix' => '<div class="col-xs-6">',
    '#suffix' => '</div></div>',
  ];

  $form['actions'] = ['#type' => 'actions'];
  $form['actions']['submit'] = [
    '#type' => 'submit',
    '#value' => 'Отправить',
    '#attributes' => ['class' => ['btn-primary', 'btn-wide']],
    '#disabled' => !$is_month_selected,
    '#ajax' => [
      'callback' => 'reports_manual_bdr_data_edit_form_callback',
      'wrapper' => 'data-manual-bdr-edit-wrapper',
    ],
  ];

  return $form;
}
function reports_manual_bdr_data_edit_form_callback($form, $form_state)
{
  return $form;
}
function reports_manual_bdr_data_edit_form_submit($form, $form_state)
{
  $month_start = gmmktime(0, 0, 0, (int)$form_state['values']['month'], 1, (int)$form_state['values']['year']);

  // удалить старые записи за месяц
  if ($form_state['values']['record']) {
    entity_delete('manual', $form_state['values']['record']);
  }

  // добавить Запись плана
  $record = dash_manual_bdr_create([
    'created' => REQUEST_TIME,
    'company_id' => $form_state['values']['company_id'],
    'month_ts' => $month_start,
    'type' => $form_state['values']['type'],
    'category_id' => $form_state['values']['category'],
    'amount' => $form_state['values']['amount'],
  ]);

  // обновление блоков
  if (!empty($form_state['blocks'])) {
    foreach ($form_state['blocks'] as $block) {
      $block = check_plain($block);
      $output = '<div class="ajax-load" data-func="' . $block . '"><div class="ajax-progress ajax-progress-throbber"><div class="throbber">&nbsp;</div><div class="message">Пожалуйста, подождите...</div></div></div>';
      $commands[] = ajax_command_replace('[data-func="' . $block . '"]', $output);
    }
  }

  $commands[] = ajax_command_invoke('.autodialog-content', 'dialog', array('close'));
  ctools_include('ajax');
  ctools_add_js('ajax-responder');
  print ajax_render($commands);
  drupal_exit();
}

function reports_debt_data_edit_form($form, &$form_state)
{
  // сохраняем блоки, которые нужно обновить
  if (!empty($_GET["blocks"])) {
    $form_state['blocks'] = $_GET["blocks"];
  }

  // определяем ID компании, для которой заполняется форма
  if (empty($form_state["values"]['company_id'])) {
    $company_id = $_GET["inn"] ?? null;
    if (isset($company_id)) {
      $company = dash_term_get_by_1c_id('companies', $_GET["inn"]);
      $company_id = $company->tid;
    }
  } else $company_id = $form_state["values"]['company_id'];

  $form = [
    '#prefix' => '<div id="data-debt-edit-wrapper" class="data-debt-edit-wrapper">',
    '#suffix' => '</div>',
  ];

  if (empty($company_id)) {
    $intro = '<p>Не задан идентификатор компании. Обратитесь к администратору сайта.</p>';
    $form['intro'] = ['#markup' => '<div class="intro">' . $intro . '</div>'];

    return $form;
  }

  $intro = '<p>Форма позволяет добавлять новые и&nbsp;редактировать ранее введённые данные</p>';
  $form['intro'] = [
    '#markup' => '<div class="intro">' . $intro . '</div>',
    '#attached' => ['js' => [[
      'data' => ['messages' => ['position' => 'inline']],
      'type' => 'setting',
    ]]],
  ];

  $options_m = [0 => ' - Месяц - '];
  for($i = 1; $i <= 12; $i++) {
    $options_m[$i] = helper_month_label_ru($i);
  }
  $form['month']['month'] = [
    '#type' => 'select',
    '#options' => $options_m,
    '#default_value' => 0,
    '#prefix' => '<div class="row"><div class="col-xs-7 col-md-5">',
    '#suffix' => '</div>',
    '#ajax' => [
      'callback' => 'reports_debt_data_edit_form_callback',
      'wrapper' => 'data-debt-edit-wrapper',
    ],
  ];

  $options_y = [0 => ' - Год - '];
  for($i = DASH_HISTORY_START_YEAR_TD; $i <= date('Y'); $i++) {
    $options_y[$i] = $i;
  }
  $form['month']['year'] = [
    '#type' => 'select',
    '#options' => $options_y,
    '#default_value' => 0,
    '#prefix' => '<div class="col-xs-5 col-md-4">',
    '#suffix' => '</div>',
    '#ajax' => [
      'callback' => 'reports_debt_data_edit_form_callback',
      'wrapper' => 'data-debt-edit-wrapper',
    ],
  ];

  $form['type'] = [
    '#type' => 'select',
    '#options' => [DASH_TYPE_PLAN => 'План'],
    '#prefix' => '<div class="col-xs-12 col-md-3">',
    '#suffix' => '</div>',
    '#ajax' => [
      'callback' => 'reports_debt_data_edit_form_callback',
      'wrapper' => 'data-debt-edit-wrapper',
    ],
  ];

  $form['kind'] = [
    '#type' => 'select',
    '#title' => 'Вид задолженности',
    '#options' => [DASH_DEBT_KIND_CREDIT => 'Внешние кредиты'],
    '#prefix' => '<div class="col-xs-6">',
    '#suffix' => '</div>',
    '#ajax' => [
      'callback' => 'reports_debt_data_edit_form_callback',
      'wrapper' => 'data-debt-edit-wrapper',
    ],
  ];

  // если изменены месяц/год, определить наличие данных
  $is_month_selected = false;
  $record_id = 0;
  if (isset($form_state['triggering_element']['#name']) && in_array($form_state['triggering_element']['#name'], ['month', 'year', 'type', 'kind'])) {
    $amount_default = 0;
    if ($form_state['values']['month'] && $form_state['values']['year']) $is_month_selected = true;

    if ($is_month_selected) {
      $period = [
        'from' => gmmktime(0, 0, 0, (int)$form_state['values']['month'], 1, (int)$form_state['values']['year']),
        'to' => gmmktime(0, 0, 0, (int)$form_state['values']['month']+1, 1, (int)$form_state['values']['year']),
      ];
      if ($data = dash_debt_get_by_conditions([
        'company_id' => $company_id, 'period' => $period, 'manual' => 1,
        'type' => $form_state['values']['type'], 'kinds' => [$form_state['values']['kind']]
      ])) {
        $record = reset($data);
        $amount_default = $record->amount;
        $record_id = $record->id;
      }
    }
    $form_state['input']['amount'] = $amount_default;
    $form_state['values']['amount'] = $amount_default;
  }

  // id записи, если найдена существующая
  $form['record'] = [
    '#type' => 'hidden',
    '#value' => $record_id,
  ];
  // от какой компании создаётся запись
  $form['company_id'] = [
    '#type' => 'hidden',
    '#value' => $company_id,
  ];

  $form['amount'] = [
    '#type' => 'textfield',
    '#size' => 20,
    '#title' => 'Сумма (руб.)',
    '#required' => true,
    '#default_value' => 0,
    '#disabled' => !$is_month_selected,
    '#prefix' => '<div class="col-xs-6">',
    '#suffix' => '</div></div>',
  ];

  $form['actions'] = ['#type' => 'actions'];
  $form['actions']['submit'] = [
    '#type' => 'submit',
    '#value' => 'Отправить',
    '#attributes' => ['class' => ['btn-primary', 'btn-wide']],
    '#disabled' => !$is_month_selected,
    '#ajax' => [
      'callback' => 'reports_debt_data_edit_form_callback',
      'wrapper' => 'data-debt-edit-wrapper',
    ],
  ];

  return $form;
}
function reports_debt_data_edit_form_callback($form, $form_state)
{
  return $form;
}
function reports_debt_data_edit_form_submit($form, $form_state)
{
  $month_start = gmmktime(0, 0, 0, (int)$form_state['values']['month'], 1, (int)$form_state['values']['year']);

  // удалить старые записи за месяц
  if ($form_state['values']['record']) {
    entity_delete('debt', $form_state['values']['record']);
  }

  // добавить Запись плана
  $record = dash_debt_create([
    'created' => REQUEST_TIME,
    'company_id' => $form_state['values']['company_id'],
    'month_ts' => $month_start,
    'type' => $form_state['values']['type'],
    'kind' => $form_state['values']['kind'],
    'manual' => 1,
    'amount' => $form_state['values']['amount'],
  ]);

  // обновление блоков
  if (!empty($form_state['blocks'])) {
    foreach ($form_state['blocks'] as $block) {
      $block = check_plain($block);
      $output = '<div class="ajax-load" data-func="' . $block . '"><div class="ajax-progress ajax-progress-throbber"><div class="throbber">&nbsp;</div><div class="message">Пожалуйста, подождите...</div></div></div>';
      $commands[] = ajax_command_replace('[data-func="' . $block . '"]', $output);
    }
  }

  $commands[] = ajax_command_invoke('.autodialog-content', 'dialog', array('close'));
  ctools_include('ajax');
  ctools_add_js('ajax-responder');
  print ajax_render($commands);
  drupal_exit();
}

function reports_ship_data_edit_form($form, &$form_state)
{
  // сохраняем блоки, которые нужно обновить
  if (!empty($_GET["blocks"])) {
    $form_state['blocks'] = $_GET["blocks"];
  }

  // определяем ID компании, для которой заполняется форма
  if (empty($form_state["values"]['company_id'])) {
    $company_id = $_GET["inn"] ?? null;
    if (isset($company_id)) {
      $company = dash_term_get_by_1c_id('companies', $_GET["inn"]);
      $company_id = $company->tid;
    }
  } else $company_id = $form_state["values"]['company_id'];

  $form = [
    '#prefix' => '<div id="data-ship-edit-wrapper" class="data-ship-edit-wrapper">',
    '#suffix' => '</div>',
  ];

  if (empty($company_id)) {
    $intro = '<p>Не задан идентификатор компании. Обратитесь к администратору сайта.</p>';
    $form['intro'] = ['#markup' => '<div class="intro">' . $intro . '</div>'];

    return $form;
  }

  $intro = '<p>Форма позволяет добавлять новые и&nbsp;редактировать ранее введённые данные</p>';
  $form['intro'] = [
    '#markup' => '<div class="intro">' . $intro . '</div>',
    '#attached' => ['js' => [[
      'data' => ['messages' => ['position' => 'inline']],
      'type' => 'setting',
    ]]],
  ];

  $options_m = [0 => ' - Месяц - '];
  for($i = 1; $i <= 12; $i++) {
    $options_m[$i] = helper_month_label_ru($i);
  }
  $form['month']['month'] = [
    '#type' => 'select',
    '#options' => $options_m,
    '#default_value' => 0,
    '#prefix' => '<div class="row"><div class="col-xs-7 col-md-5">',
    '#suffix' => '</div>',
    '#ajax' => [
      'callback' => 'reports_ship_data_edit_form_callback',
      'wrapper' => 'data-ship-edit-wrapper',
    ],
  ];

  $options_y = [0 => ' - Год - '];
  for($i = DASH_HISTORY_START_YEAR_TD; $i <= date('Y'); $i++) {
    $options_y[$i] = $i;
  }
  $form['month']['year'] = [
    '#type' => 'select',
    '#options' => $options_y,
    '#default_value' => 0,
    '#prefix' => '<div class="col-xs-5 col-md-4">',
    '#suffix' => '</div>',
    '#ajax' => [
      'callback' => 'reports_ship_data_edit_form_callback',
      'wrapper' => 'data-ship-edit-wrapper',
    ],
  ];

  $form['type'] = [
    '#type' => 'select',
    '#options' => [1 => 'План', 2 => 'Факт'],
    '#prefix' => '<div class="col-xs-12 col-md-3">',
    '#suffix' => '</div>',
    '#ajax' => [
      'callback' => 'reports_ship_data_edit_form_callback',
      'wrapper' => 'data-ship-edit-wrapper',
    ],
  ];

  // если изменены месяц/год, определить наличие данных
  $is_month_selected = false;
  $record_id = 0;
  if (isset($form_state['triggering_element']['#name']) && in_array($form_state['triggering_element']['#name'], ['month', 'year', 'type'])) {
    $amount_default = $qty_default = 0;
    if ($form_state['values']['month'] && $form_state['values']['year']) $is_month_selected = true;

    if ($is_month_selected) {
      $period = [
        'from' => gmmktime(0, 0, 0, (int)$form_state['values']['month'], 1, (int)$form_state['values']['year']),
        'to' => gmmktime(0, 0, 0, (int)$form_state['values']['month']+1, 1, (int)$form_state['values']['year']),
      ];
      if ($data = dash_ship_get_by_conditions(['company_id' => $company_id, 'period' => $period, 'manual' => 1, 'type' => $form_state['values']['type']])) {
        $record = reset($data);
        $qty_default = $record->qty;
        $amount_default = $record->amount;
        $record_id = $record->id;
      }
    }
    $form_state['input']['qty'] = $qty_default;
    $form_state['values']['qty'] = $qty_default;
    $form_state['input']['amount'] = $amount_default;
    $form_state['values']['amount'] = $amount_default;
  }


  // id записи, если найдена существующая
  $form['record'] = [
    '#type' => 'hidden',
    '#value' => $record_id,
  ];
  // от какой компании создаётся запись
  $form['company_id'] = [
    '#type' => 'hidden',
    '#value' => $company_id,
  ];

  $form['amount'] = [
    '#type' => 'textfield',
    '#size' => 20,
    '#title' => 'Сумма (руб.)',
    '#required' => true,
    '#default_value' => 0,
    '#disabled' => !$is_month_selected,
    '#prefix' => '<div class="col-xs-6">',
    '#suffix' => '</div>',
  ];
  $form['qty'] = [
    '#type' => 'textfield',
    '#size' => 20,
    '#title' => 'Кол-во (л/кг/шт)',
    '#default_value' => 0,
    '#disabled' => !$is_month_selected,
    '#prefix' => '<div class="col-xs-6">',
    '#suffix' => '</div></div>',
  ];

  $form['actions'] = ['#type' => 'actions'];
  $form['actions']['submit'] = [
    '#type' => 'submit',
    '#value' => 'Отправить',
    '#attributes' => ['class' => ['btn-primary', 'btn-wide']],
    '#disabled' => !$is_month_selected,
    '#ajax' => [
      'callback' => 'reports_ship_data_edit_form_callback',
      'wrapper' => 'data-ship-edit-wrapper',
    ],
  ];

  return $form;
}
function reports_ship_data_edit_form_callback($form, $form_state)
{
  return $form;
}
function reports_ship_data_edit_form_submit($form, $form_state)
{
  $month_start = gmmktime(0, 0, 0, (int)$form_state['values']['month'], 1, (int)$form_state['values']['year']);

  // удалить старые записи за месяц
  if ($form_state['values']['record']) {
    entity_delete('ship', $form_state['values']['record']);
  }

  // добавить Запись плана
  $record = dash_ship_create([
    'created' => REQUEST_TIME,
    'company_id' => $form_state['values']['company_id'],
    'month_ts' => $month_start,
    'type' => $form_state['values']['type'],
    'manual' => 1,
    'amount' => $form_state['values']['amount'],
    'qty' => $form_state['values']['qty'],
    'net_cost' => 0,
    'nom_id' => 0,
    'client_id' => 0,
  ]);

  // обновление блоков
  if (!empty($form_state['blocks'])) {
    foreach ($form_state['blocks'] as $block) {
      $block = check_plain($block);
      $output = '<div class="ajax-load" data-func="' . $block . '"><div class="ajax-progress ajax-progress-throbber"><div class="throbber">&nbsp;</div><div class="message">Пожалуйста, подождите...</div></div></div>';
      $commands[] = ajax_command_replace('[data-func="' . $block . '"]', $output);
    }
  }

  $commands[] = ajax_command_invoke('.autodialog-content', 'dialog', array('close'));
  ctools_include('ajax');
  ctools_add_js('ajax-responder');
  print ajax_render($commands);
  drupal_exit();
}

function reports_cash_income_data_edit_form($form, &$form_state)
{
  // сохраняем блоки, которые нужно обновить
  if (!empty($_GET["blocks"])) {
    $form_state['blocks'] = $_GET["blocks"];
  }

  // определяем ID компании, для которой заполняется форма
  if (empty($form_state["values"]['company_id'])) {
    $company_id = $_GET["inn"] ?? null;
    if (isset($company_id)) {
      $company = dash_term_get_by_1c_id('companies', $_GET["inn"]);
      $company_id = $company->tid;
    }
  } else $company_id = $form_state["values"]['company_id'];

  $form = [
    '#prefix' => '<div id="data-cash-income-edit-wrapper" class="data-cash-income-edit-wrapper">',
    '#suffix' => '</div>',
  ];

  if (!$company_id) {
    $intro = '<p>Не задан идентификатор компании. Обратитесь к администратору сайта.</p>';
    $form['intro'] = ['#markup' => '<div class="intro">' . $intro . '</div>'];

    return $form;
  }

  $intro = '<p>Форма позволяет добавлять новые и&nbsp;редактировать ранее введённые данные</p>';
  $form['intro'] = [
    '#markup' => '<div class="intro">' . $intro . '</div>',
    '#attached' => ['js' => [[
      'data' => ['messages' => ['position' => 'inline']],
      'type' => 'setting',
    ]]],
  ];

  $options_m = [0 => ' - Месяц - '];
  for($i = 1; $i <= 12; $i++) {
    $options_m[$i] = helper_month_label_ru($i);
  }
  $form['month']['month'] = [
    '#type' => 'select',
    '#options' => $options_m,
    '#default_value' => 0,
    '#prefix' => '<div class="row"><div class="col-xs-7">',
    '#suffix' => '</div>',
    '#ajax' => [
      'callback' => 'reports_cash_income_data_edit_form_callback',
      'wrapper' => 'data-cash-income-edit-wrapper',
    ],
  ];

  $options_y = [0 => ' - Год - '];
  for($i = DASH_HISTORY_START_YEAR_TD; $i <= date('Y'); $i++) {
    $options_y[$i] = $i;
  }
  $form['month']['year'] = [
    '#type' => 'select',
    '#options' => $options_y,
    '#default_value' => 0,
    '#prefix' => '<div class="col-xs-5">',
    '#suffix' => '</div>',
    '#ajax' => [
      'callback' => 'reports_cash_income_data_edit_form_callback',
      'wrapper' => 'data-cash-income-edit-wrapper',
    ],
  ];

  $form['type'] = [
    '#type' => 'select',
    '#title' => 'Тип записи',
    '#options' => [1 => 'План', 2 => 'Факт'],
    '#prefix' => '<div class="col-xs-6">',
    '#suffix' => '</div>',
    '#ajax' => [
      'callback' => 'reports_cash_income_data_edit_form_callback',
      'wrapper' => 'data-cash-income-edit-wrapper',
    ],
  ];

  // если изменены месяц/год, определить наличие данных
  $is_month_selected = false;
  $record_id = 0;
  if (isset($form_state['triggering_element']['#name']) && in_array($form_state['triggering_element']['#name'], ['month', 'year', 'type'])) {
    $amount_default = 0;
    if ($form_state['values']['month'] && $form_state['values']['year']) $is_month_selected = true;

    if ($is_month_selected) {
      $period = [
        'from' => gmmktime(0, 0, 0, (int)$form_state['values']['month'], 1, (int)$form_state['values']['year']),
        'to' => gmmktime(0, 0, 0, (int)$form_state['values']['month']+1, 1, (int)$form_state['values']['year']),
      ];
      if ($data = dash_cash_income_get_by_conditions(['company_id' => $company_id, 'period' => $period, 'manual' => 1, 'type' => $form_state['values']['type']])) {
        $record = reset($data);
        $amount_default = $record->amount;
        $record_id = $record->id;
      }
    }
    $form_state['input']['amount'] = $amount_default;
    $form_state['values']['amount'] = $amount_default;
  }


  // id записи, если найдена существующая
  $form['record'] = [
    '#type' => 'hidden',
    '#value' => $record_id,
  ];
  // от какой компании создаётся запись
  $form['company_id'] = [
    '#type' => 'hidden',
    '#value' => $company_id,
  ];

  $form['amount'] = [
    '#type' => 'textfield',
    '#size' => 20,
    '#title' => 'Сумма (руб.)',
    '#required' => true,
    '#default_value' => 0,
    '#disabled' => !$is_month_selected,
    '#prefix' => '<div class="col-xs-6">',
    '#suffix' => '</div></div>',
  ];

  $form['actions'] = ['#type' => 'actions'];
  $form['actions']['submit'] = [
    '#type' => 'submit',
    '#value' => 'Отправить',
    '#attributes' => ['class' => ['btn-primary', 'btn-wide']],
    '#disabled' => !$is_month_selected,
    '#ajax' => [
      'callback' => 'reports_cash_income_data_edit_form_callback',
      'wrapper' => 'data-cash-income-edit-wrapper',
    ],
  ];

  return $form;
}
function reports_cash_income_data_edit_form_callback($form, $form_state)
{
  return $form;
}
function reports_cash_income_data_edit_form_submit($form, $form_state)
{
  $month_start = gmmktime(0, 0, 0, (int)$form_state['values']['month'], 1, (int)$form_state['values']['year']);

  // удалить старые записи за месяц
  if ($form_state['values']['record']) {
    entity_delete('cash_income', $form_state['values']['record']);
  }

  // добавить Запись плана
  $record = dash_cash_income_create([
    'created' => REQUEST_TIME,
    'company_id' => $form_state['values']['company_id'],
    'month_ts' => $month_start,
    'type' => $form_state['values']['type'],
    'manual' => 1,
    'amount' => $form_state['values']['amount'],
  ]);

  // обновление блоков
  if (!empty($form_state['blocks'])) {
    foreach ($form_state['blocks'] as $block) {
      $block = check_plain($block);
      $output = '<div class="ajax-load" data-func="' . $block . '"><div class="ajax-progress ajax-progress-throbber"><div class="throbber">&nbsp;</div><div class="message">Пожалуйста, подождите...</div></div></div>';
      $commands[] = ajax_command_replace('[data-func="' . $block . '"]', $output);
    }
  }

  $commands[] = ajax_command_invoke('.autodialog-content', 'dialog', array('close'));
  ctools_include('ajax');
  ctools_add_js('ajax-responder');
  print ajax_render($commands);
  drupal_exit();
}

function reports_plan_prod_data_edit_form($form, &$form_state)
{
  // сохраняем блоки, которые нужно обновить
  if (!empty($_GET["blocks"])) {
    $form_state['blocks'] = $_GET["blocks"];
  }

  $form = [
    '#prefix' => '<div id="data-plan-prod-edit-wrapper" class="data-plan-prod-edit-wrapper">',
    '#suffix' => '</div>',
  ];

  $intro = '<p>Форма позволяет добавлять новые и&nbsp;редактировать ранее введённые данные</p>';

  $form['intro'] = [
    '#markup' => '<div class="intro">' . $intro . '</div>',
    '#attached' => ['js' => [[
      'data' => ['messages' => ['position' => 'inline']],
      'type' => 'setting',
    ]]],
  ];

  $options_m = [0 => ' - Месяц - '];
  for($i = 1; $i <= 12; $i++) {
    $options_m[$i] = helper_month_label_ru($i);
  }
  $form['month']['month'] = [
    '#type' => 'select',
    '#options' => $options_m,
    '#default_value' => 0,
    '#prefix' => '<div class="row"><div class="col-xs-7">',
    '#suffix' => '</div>',
    '#ajax' => [
      'callback' => 'reports_plan_prod_data_edit_form_callback',
      'wrapper' => 'data-plan-prod-edit-wrapper',
    ],
  ];

  $options_y = [0 => ' - Год - '];
  for($i = DASH_HISTORY_START_YEAR_TD; $i <= date('Y'); $i++) {
    $options_y[$i] = $i;
  }
  $form['month']['year'] = [
    '#type' => 'select',
    '#options' => $options_y,
    '#default_value' => 0,
    '#prefix' => '<div class="col-xs-5">',
    '#suffix' => '</div>',
    '#ajax' => [
      'callback' => 'reports_plan_prod_data_edit_form_callback',
      'wrapper' => 'data-plan-prod-edit-wrapper',
    ],
  ];

  $form['fact'] = [
    '#type' => 'select',
    '#title' => 'Тип записи',
    '#options' => [0 => 'План', 1 => 'Факт'],
    '#prefix' => '<div class="col-xs-6">',
    '#suffix' => '</div>',
    '#ajax' => [
      'callback' => 'reports_plan_prod_data_edit_form_callback',
      'wrapper' => 'data-plan-prod-edit-wrapper',
    ],
  ];

  // если изменены месяц/год, определить наличие данных
  $is_month_selected = false;
  $record_id = 0;
  if (isset($form_state['triggering_element']['#name']) && in_array($form_state['triggering_element']['#name'], ['month', 'year', 'fact'])) {
    $volume_default = 0;
    if ($form_state['values']['month'] && $form_state['values']['year']) $is_month_selected = true;

    if ($is_month_selected) {
      $period = [
        'from' => gmmktime(0, 0, 0, (int)$form_state['values']['month'], 1, (int)$form_state['values']['year']),
        'to' => gmmktime(0, 0, 0, (int)$form_state['values']['month']+1, 1, (int)$form_state['values']['year']),
      ];
      if ($data = dash_plan_prod_get_by_conditions(['period' => $period, 'manual' => 1, 'fact' => $form_state['values']['fact']])) {
        $record = reset($data);
        $volume_default = $record->output;
        $record_id = $record->id;
      }
    }
    $form_state['input']['volume'] = $volume_default;
    $form_state['values']['volume'] = $volume_default;
  }


  // id записи, если найдена существующая
  $form['record'] = [
    '#type' => 'hidden',
    '#value' => $record_id,
  ];

  $form['volume'] = [
    '#type' => 'textfield',
    '#size' => 20,
    '#title' => 'Объём (л/кг/шт)',
    '#required' => true,
    '#default_value' => 0,
    '#disabled' => !$is_month_selected,
    '#prefix' => '<div class="col-xs-6">',
    '#suffix' => '</div></div>',
  ];

  $form['actions'] = ['#type' => 'actions'];
  $form['actions']['submit'] = [
    '#type' => 'submit',
    '#value' => 'Отправить',
    '#attributes' => ['class' => ['btn-primary', 'btn-wide']],
    '#disabled' => !$is_month_selected,
    '#ajax' => [
      'callback' => 'reports_plan_prod_data_edit_form_callback',
      'wrapper' => 'data-plan-prod-edit-wrapper',
    ],
  ];

  return $form;
}
function reports_plan_prod_data_edit_form_callback($form, $form_state)
{
  return $form;
}
function reports_plan_prod_data_edit_form_submit($form, $form_state)
{
  $month_start = gmmktime(0, 0, 0, (int)$form_state['values']['month'], 1, (int)$form_state['values']['year']);

  // удалить старые записи за месяц
  if ($form_state['values']['record']) {
    entity_delete('plan', $form_state['values']['record']);
  }

  // добавить Запись плана
  $record = dash_plan_prod_create([
    'created' => REQUEST_TIME,
    'month_ts' => $month_start,
    'nom_id' => 0,
    'fact' => $form_state['values']['fact'],
    'manual' => 1,
    'volume' => $form_state['values']['volume'],
  ]);

  // обновление блоков
  if (!empty($form_state['blocks'])) {
    foreach ($form_state['blocks'] as $block) {
      $block = check_plain($block);
      $output = '<div class="ajax-load" data-func="' . $block . '"><div class="ajax-progress ajax-progress-throbber"><div class="throbber">&nbsp;</div><div class="message">Пожалуйста, подождите...</div></div></div>';
      $commands[] = ajax_command_replace('[data-func="' . $block . '"]', $output);
    }
  }

  $commands[] = ajax_command_invoke('.autodialog-content', 'dialog', array('close'));
  ctools_include('ajax');
  ctools_add_js('ajax-responder');
  print ajax_render($commands);
  drupal_exit();
}

function reports_plan_ship_data_edit_form($form, &$form_state)
{
  // сохраняем блоки, которые нужно обновить
  if (!empty($_GET["blocks"])) {
    $form_state['blocks'] = $_GET["blocks"];
  }

  $form = [
    '#prefix' => '<div id="data-plan-ship-edit-wrapper" class="data-plan-ship-edit-wrapper">',
    '#suffix' => '</div>',
  ];

  $intro = '<p>Форма позволяет добавлять новые и&nbsp;редактировать ранее введённые данные</p>';

  $form['intro'] = [
    '#markup' => '<div class="intro">' . $intro . '</div>',
  ];

  $options_m = [0 => ' - Месяц - '];
  for($i = 1; $i <= 12; $i++) {
    $options_m[$i] = helper_month_label_ru($i);
  }
  $form['month']['month'] = [
    '#type' => 'select',
    '#options' => $options_m,
    '#default_value' => 0,
    '#prefix' => '<div class="row"><div class="col-xs-7 col-md-5">',
    '#suffix' => '</div>',
    '#ajax' => [
      'callback' => 'reports_plan_ship_data_edit_form_callback',
      'wrapper' => 'data-plan-ship-edit-wrapper',
    ],
  ];

  $options_y = [0 => ' - Год - '];
  for($i = DASH_HISTORY_START_YEAR_TD; $i <= date('Y'); $i++) {
    $options_y[$i] = $i;
  }
  $form['month']['year'] = [
    '#type' => 'select',
    '#options' => $options_y,
    '#default_value' => 0,
    '#prefix' => '<div class="col-xs-5 col-md-4">',
    '#suffix' => '</div>',
    '#ajax' => [
      'callback' => 'reports_plan_ship_data_edit_form_callback',
      'wrapper' => 'data-plan-ship-edit-wrapper',
    ],
  ];

  $form['type'] = [
    '#type' => 'select',
    '#options' => [DASH_TYPE_PLAN_DEPR => 'План'],
    '#prefix' => '<div class="col-xs-12 col-md-3">',
    '#suffix' => '</div>',
    '#ajax' => [
      'callback' => 'reports_plan_ship_data_edit_form_callback',
      'wrapper' => 'data-plan-ship-edit-wrapper',
    ],
  ];

  // если изменены месяц/год, определить наличие данных
  $is_month_selected = false;
  $record_id = 0;
  if (isset($form_state['triggering_element']['#name']) && in_array($form_state['triggering_element']['#name'], ['month', 'year', 'type'])) {
    $qty_default = $amount_default = 0;
    if ($form_state['values']['month'] && $form_state['values']['year']) $is_month_selected = true;

    if ($is_month_selected) {
      $period = [
        'from' => gmmktime(0, 0, 0, (int)$form_state['values']['month'], 1, (int)$form_state['values']['year']),
        'to' => gmmktime(0, 0, 0, (int)$form_state['values']['month']+1, 1, (int)$form_state['values']['year']),
      ];
      if ($data = dash_plan_ship_get_by_conditions(['period' => $period, 'manual' => 1, 'type' => (int)$form_state['values']['type']])) {
        $record = reset($data);
        $qty_default = $record->qty;
        $amount_default = $record->amount;
        $record_id = $record->id;
      }
    }
    $form_state['input']['qty'] = $qty_default;
    $form_state['values']['qty'] = $qty_default;
    $form_state['input']['amount'] = $amount_default;
    $form_state['values']['amount'] = $amount_default;
  }

  // id записи, если найдена существующая
  $form['record'] = [
    '#type' => 'hidden',
    '#value' => $record_id,
  ];

  $form['amount'] = [
    '#type' => 'textfield',
    '#size' => 20,
    '#title' => 'Сумма (руб.)',
    '#default_value' => 0,
    '#disabled' => !$is_month_selected,
    '#prefix' => '<div class="col-xs-6">',
    '#suffix' => '</div>',
  ];
  $form['qty'] = [
    '#type' => 'textfield',
    '#size' => 20,
    '#title' => 'Кол-во (л/кг/шт)',
    '#default_value' => 0,
    '#disabled' => !$is_month_selected,
    '#prefix' => '<div class="col-xs-6">',
    '#suffix' => '</div></div>',
  ];

  $form['actions'] = ['#type' => 'actions'];
  $form['actions']['submit'] = [
    '#type' => 'submit',
    '#value' => 'Отправить',
    '#attributes' => ['class' => ['btn-primary', 'btn-wide']],
    '#disabled' => !$is_month_selected,
    '#ajax' => [
      'callback' => 'reports_plan_ship_data_edit_form_callback',
      'wrapper' => 'data-plan-ship-edit-wrapper',
    ],
  ];

  return $form;
}
function reports_plan_ship_data_edit_form_callback($form, $form_state)
{
  return $form;
}
function reports_plan_ship_data_edit_form_submit($form, $form_state)
{
  $month_start = gmmktime(0, 0, 0, (int)$form_state['values']['month'], 1, (int)$form_state['values']['year']);

  // удалить старые записи за месяц
  if ($form_state['values']['record']) {
    entity_delete('plan', $form_state['values']['record']);
  }

  // добавить Запись плана
  $record = dash_plan_ship_create([
    'created' => REQUEST_TIME,
    'month_ts' => $month_start,
    'nom_id' => 0,
    'client_id' => 0,
    'type' => $form_state['values']['type'],
    'manual' => 1,
    'qty' => $form_state['values']['qty'],
    'amount' => $form_state['values']['amount'],
    'net_cost' => 0,
  ]);

  // обновление блоков
  if (!empty($form_state['blocks'])) {
    foreach ($form_state['blocks'] as $block) {
      $block = check_plain($block);
      $output = '<div class="ajax-load" data-func="' . $block . '"><div class="ajax-progress ajax-progress-throbber"><div class="throbber">&nbsp;</div><div class="message">Пожалуйста, подождите...</div></div></div>';
      $commands[] = ajax_command_replace('[data-func="' . $block . '"]', $output);
    }
  }

  $commands[] = ajax_command_invoke('.autodialog-content', 'dialog', array('close'));
  ctools_include('ajax');
  ctools_add_js('ajax-responder');
  print ajax_render($commands);
  drupal_exit();
}
