<?php


/**
 * Implements hook_cron()
 */
function import_cron()
{
  // поставить заявки в очередь на импорт
  if (variable_get('admin_import_enabled', false)) {
    import_queue_incoming_exchange_files();
  }
}

/**
 * Implements hook_cron_queue_info().
 */
function import_cron_queue_info()
{
  $queues['incoming_exchange_queue'] = array(
    'worker callback' => 'import_process_incoming_exchange_file',
  );

  return $queues;
}

function import_queue_incoming_exchange_files()
{
  $directory = 'private://exchange/';
  $queue_path = $directory . 'import_queue';

  // формат массива обработчиков импорта
  $processors = [
    // первая очередь импорта данных, необходимых для второй очереди
    'first_queue' => [
      [
        'mask'    => '/^scrum_td_region.*\.json/',    // маска поиска файла
        'include' => 'file.inc',                      // файл с функцией импорта
        'func'    => 'import_import_regions'          // название функции импорта
      ],
    ],
    // вторая очередь
    'last_queue' => [],
  ];

  $processors = [
    'first_queue' => [],
    // вторая очередь
    'last_queue' => [
      ['mask' => '/^scrum_revenue.*\.json/',          'func' => 'import_import_revenue'],         // -- Выручка
    ],
  ];

  // дать возможность модулям добавить свой импорт
  drupal_alter('import_processors', $processors);

  $ie_queue = DrupalQueue::get('incoming_exchange_queue');

//  $ie_queue->deleteQueue();

  // получить список файлов по шаблону и добавить в очередь
  foreach($processors as $queue) {
    foreach($queue as $processor) {
      if ($files = file_scan_directory($directory, $processor['mask'], ['recurse' => false], 0)) {
        foreach($files as $file) {
          // перемещаем обнаруженные файлы в папку очереди, чтобы не обнаружить при следующем запуске крона
          if (file_prepare_directory($queue_path, FILE_CREATE_DIRECTORY)) {
            if ($new_uri = file_unmanaged_move($file->uri, $queue_path . '/' . $file->filename)) {
              $file->uri = $new_uri;
              $ie_queue->createItem(['file' => $file, 'processor' => $processor]);
  //            watchdog('import', 'Файл @file поставлен в очередь на импорт.', ['@file' => $file->uri], WATCHDOG_INFO);
            }
          }
        }
      }
    }
  }
}

function import_process_incoming_exchange_file($options)
{
  $directory = 'private://exchange/';

  // импортировать
  $array = drupal_json_decode(file_get_contents($options['file']->uri));

  if (!empty($options['processor']['include'])) require_once $options['processor']['include'];

  $archive = $options['processor']['archive'] ?? 'dash';
  if (call_user_func($options['processor']['func'], $array)) {
    $path = $directory . 'success/' . $archive . '/' . date('Y') . '/' . date('m') . '/' . date('d');
  } else {
    $path = $directory . 'fail/' . $archive . '/' . date('Y') . '/' . date('m') . '/' . date('d');
  }
  file_prepare_directory($path, FILE_CREATE_DIRECTORY);
  file_unmanaged_move($options['file']->uri, $path . '/' . $options['file']->filename);
}

/**
 * -- функции импорта общие для подразделений
 */
function import_import_revenue($array)
{
  if (is_array($array) && $array['company'] && !empty($array['load'])) {
    $month_arr = explode('.', $array['month']);
    $month_start = gmmktime(0, 0, 0, $month_arr[1], 1, $month_arr[2]);
    $rev_import_time = time();

    // подготовка Выручки
    $revenue = [];
    foreach ($array['load'] as $rev_item) {
      $date_arr = explode('.', $rev_item['date']);
      $date_start = gmmktime(0, 0, 0, $date_arr[1], $date_arr[0], $date_arr[2]);

      $revenue[] = [
        'date' => $date_start,
        'type' => $rev_item['type_revenue'],
        'amount' => $rev_item['sum'],
      ];
    }

    if ($revenue) {
      // удалить старую Выручку за месяц
      import_revenue_month_delete($array['company'], $month_start);

      // создание Выручки на месяц
      foreach ($revenue as $date => $rev_item) {
        $revenue = entity_create('revenue', [
          'type' => 'revenue',
          'created' => $rev_import_time,
        ]);
        entity_save('revenue', $revenue);

        $revenue_wr = entity_metadata_wrapper('revenue', $revenue);
        $revenue_wr->field_date = $rev_item['date'];
        $revenue_wr->field_revenue_type = $rev_item['type'];
        $revenue_wr->field_amount = $rev_item['amount'];
        $revenue_wr->field_company = $array['company'];
        $revenue_wr->save();
      }

      watchdog('import', 'Выручка импортирована.', [], WATCHDOG_INFO);
      // drupal_set_message('Выручка импортирована.');
      return $revenue;
    }
  } else {
    watchdog('import', 'Импорт выручки не выполнен.', [], WATCHDOG_ERROR);
    return false;
  }
}

function import_revenue_month_delete($company, $month_start)
{
  if ($month_start) {
    $next_month_start = gmmktime(0, 0, 0, date('n', $month_start)+1, 1, date('Y', $month_start));

    $efquery = new EntityFieldQuery();
    $efquery
      ->entityCondition('entity_type', 'revenue')
      ->entityCondition('bundle', 'revenue')
      ->fieldCondition('field_date', 'value', $month_start, '>=')
      ->fieldCondition('field_date', 'value', $next_month_start, '<')
      ->fieldCondition('field_company', 'value', $company);

    $result = $efquery->execute();
    if ($result) {
      entity_delete_multiple('revenue', array_keys($result['revenue']));
    }
  }
}





