<?php


/**
 * Implements hook_cron()
 */
function import_cron()
{
  // поставить заявки в очередь на импорт
  if (variable_get('admin_import_enabled', false)) {
    import_queue_incoming_exchange_files();
  }
}

/**
 * Implements hook_cron_queue_info().
 */
function import_cron_queue_info()
{
  $queues['incoming_exchange_queue'] = array(
    'worker callback' => 'import_process_incoming_exchange_file',
  );

  return $queues;
}

function import_queue_incoming_exchange_files()
{
  $directory = 'private://exchange/';
  $queue_path = $directory . 'import_queue';

  // формат массива обработчиков импорта
  $processors = [
    // первая очередь импорта данных, необходимых для второй очереди
    'first_queue' => [
      [
        'mask'    => '/^scrum_td_region.*\.json/',    // маска поиска файла
        'include' => 'file.inc',                      // файл с функцией импорта
        'func'    => 'import_import_regions'          // название функции импорта
      ],
    ],
    // вторая очередь
    'last_queue' => [],
  ];

  $processors = [
    'first_queue' => [
      ['mask' => '/^scrum_hb_clients.*\.json/',       'func' => 'import_clients', 'archive' => 'dash/common'],          // -- Справочник Направлений деятельности
      ['mask' => '/^scrum_hb_directions.*\.json/',    'func' => 'import_directions', 'archive' => 'dash/common'],       // -- Справочник Клиентов
      ['mask' => '/^scrum_hb_nomenclature.*\.json/',  'func' => 'import_nomenclature', 'archive' => 'dash/common'],     // -- Справочник Номенклатуры
    ],
    // вторая очередь
    'last_queue' => [
      ['mask' => '/^scrum_revenue.*\.json/',          'func' => 'import_import_revenue', 'archive' => 'dash/common'],   // -- Выручка
    ],
  ];

  // дать возможность модулям добавить свой импорт
  drupal_alter('import_processors', $processors);

  $ie_queue = DrupalQueue::get('incoming_exchange_queue');

//  $ie_queue->deleteQueue();

  // получить список файлов по шаблону и добавить в очередь
  foreach($processors as $queue) {
    foreach($queue as $processor) {
      if ($files = file_scan_directory($directory, $processor['mask'], ['recurse' => false], 0)) {
        foreach($files as $file) {
          // перемещаем обнаруженные файлы в папку очереди, чтобы не обнаружить при следующем запуске крона
          if (file_prepare_directory($queue_path, FILE_CREATE_DIRECTORY)) {
            if ($new_uri = file_unmanaged_move($file->uri, $queue_path . '/' . $file->filename)) {
              $file->uri = $new_uri;
              $ie_queue->createItem(['file' => $file, 'processor' => $processor]);
  //            watchdog('import', 'Файл @file поставлен в очередь на импорт.', ['@file' => $file->uri], WATCHDOG_INFO);
            }
          }
        }
      }
    }
  }
}

function import_process_incoming_exchange_file($options)
{
  $directory = 'private://exchange/';

  // импортировать
  $array = drupal_json_decode(file_get_contents($options['file']->uri));

  if (!empty($options['processor']['include'])) require_once $options['processor']['include'];

  $archive = $options['processor']['archive'] ?? 'dash';
  if (call_user_func($options['processor']['func'], $array)) {
    $path = $directory . 'success/' . $archive . '/' . date('Y') . '/' . date('m') . '/' . date('d');
  } else {
    $path = $directory . 'fail/' . $archive . '/' . date('Y') . '/' . date('m') . '/' . date('d');
  }
  file_prepare_directory($path, FILE_CREATE_DIRECTORY);
  file_unmanaged_move($options['file']->uri, $path . '/' . $options['file']->filename);
}

/**
 * -- функции импорта общие для подразделений
 */
function import_import_revenue($array)
{
  if (is_array($array) && $array['company'] && !empty($array['load'])) {
    $month_arr = explode('.', $array['month']);
    $month_start = gmmktime(0, 0, 0, $month_arr[1], 1, $month_arr[2]);
    $rev_import_time = time();

    // подготовка Выручки
    $revenue = [];
    foreach ($array['load'] as $rev_item) {
      $date_arr = explode('.', $rev_item['date']);
      $date_start = gmmktime(0, 0, 0, $date_arr[1], $date_arr[0], $date_arr[2]);

      $revenue[] = [
        'date' => $date_start,
        'type' => $rev_item['type_revenue'],
        'amount' => $rev_item['sum'],
      ];
    }

    if ($revenue) {
      // удалить старую Выручку за месяц
      import_revenue_delete_by_month($array['company'], $month_start);

      // создание Выручки на месяц
      foreach ($revenue as $date => $rev_item) {
        $revenue = entity_create('revenue', [
          'type' => 'revenue',
          'created' => $rev_import_time,
        ]);
        entity_save('revenue', $revenue);

        $revenue_wr = entity_metadata_wrapper('revenue', $revenue);
        $revenue_wr->field_revenue_date = $rev_item['date'];
        $revenue_wr->field_revenue_type = $rev_item['type'];
        $revenue_wr->field_revenue_amount = $rev_item['amount'];
        $revenue_wr->field_revenue_company = $array['company'];
        $revenue_wr->save();
      }

      watchdog('import', 'Выручка импортирована.', [], WATCHDOG_INFO);
      // drupal_set_message('Выручка импортирована.');
      return $revenue;
    }
  } else {
    watchdog('import', 'Импорт выручки не выполнен.', [], WATCHDOG_ERROR);
    return false;
  }
}

function import_revenue_delete_by_month($company, $month_start)
{
  if ($month_start) {
    $next_month_start = gmmktime(0, 0, 0, date('n', $month_start)+1, 1, date('Y', $month_start));

    $efquery = new EntityFieldQuery();
    $efquery
      ->entityCondition('entity_type', 'revenue')
      ->entityCondition('bundle', 'revenue')
      ->fieldCondition('field_revenue_date', 'value', $month_start, '>=')
      ->fieldCondition('field_revenue_date', 'value', $next_month_start, '<')
      ->fieldCondition('field_revenue_company', 'value', $company);

    $result = $efquery->execute();
    if ($result) {
      entity_delete_multiple('revenue', array_keys($result['revenue']));
    }
  }
}


function import_clients($array)
{
  if (is_array($array) && !empty($array['load'])) {

    if ($array['inn']) {
      $company = dash_term_get_by_1c_id('companies', $array['inn']);

      $new_records = [];
      foreach ($array['load'] as $client) {
        if ($client['id'] && $client['name']) {

          $term = dash_client_get_by_1c_id($array['inn'], $client['id']);

          $client_wr = entity_metadata_wrapper('taxonomy_term', $term);
          $client_wr->name = $client['name'];
          $client_wr->field_client_group = $client['group'] ?? '';
          $client_wr->field_status = 1;
          $client_wr->field_kccc_company = $company->tid;

          if (!empty($array['region_id'])) {
            $region = dash_term_get_by_1c_id('regions', $array['region_id']);
          }
          $client_wr->field_region = empty($region) ? 0 : $region->tid;

          $client_wr->save();

          $new_records[] = $client_wr->getIdentifier();
        }
      }

      // если полное обновление справочника, то отключить записи, которых нет в файле
      if ($array['reload']) {
        db_update('field_data_field_status')
          ->fields(['field_status_value' => 0])
          ->condition('entity_type', 'taxonomy_term')
          ->condition('bundle', 'clients')
          ->condition('entity_id', $new_records, 'NOT IN')
          ->execute();
      }

      watchdog('import', 'Клиенты импортированы.', [], WATCHDOG_INFO);
      return true;
    }
  }

  watchdog('import', 'Импорт клиентов не выполнен.', [], WATCHDOG_ERROR);
  return false;
}

function import_directions($array)
{
  if (is_array($array) && !empty($array['load'])) {

    $new_records = [];
    foreach ($array['load'] as $direction) {
      if ($direction['id'] && $direction['name']) {

        if ($term = dash_direction_get_by_1c_id($direction['id'])) {
          $d_wr = entity_metadata_wrapper('taxonomy_term', $term);
          $d_wr->name = $direction['name'];
          $d_wr->field_status = 1;
          $d_wr->save();

          $new_records[] = $d_wr->getIdentifier();
        }
      }
    }

    // если полное обновление справочника, то отключить записи, которых нет в файле
    if ($array['reload']) {
      db_update('field_data_field_status')
        ->fields(['field_status_value' => 0])
        ->condition('entity_type', 'taxonomy_term')
        ->condition('bundle', 'directions')
        ->condition('entity_id', $new_records, 'NOT IN')
        ->execute();
    }

    watchdog('import', 'Направления импортированы.', [], WATCHDOG_INFO);
    return true;
  }

  watchdog('import', 'Импорт направлений не выполнен.', [], WATCHDOG_ERROR);
  return false;
}

function import_nomenclature($array)
{
  if (is_array($array) && $array['inn'] && !empty($array['load'])) {
    if ($company = dash_term_get_by_1c_id('companies', $array['inn'])) {

      $new_records = [];
      foreach($array['load'] as $nom) {
        if ($nom['id'] && $nom['name'] && $nom['art'] && $nom['client_id']) {
          // найти клиента
          if ($client = dash_term_get_by_1c_id('clients', $nom['client_id'])) {
            // проверить наличие записи Номенклатуры по артикулу (тк не у всех прописан ID)
            $term = dash_nomenklatura_get_by_1c_artikul($array['inn'], $nom['art']);
            // если нет по артикулу, искать по ID или создать
            if (!$term) {
              $term = dash_term_get_by_1c_id($array['inn'], $nom['id']);
            }

            if ($term) {
              // обновить значения полей
              $term_wr = entity_metadata_wrapper('taxonomy_term', $term);
              $term_wr->name = $nom['name'];
              $term_wr->field_1c_id = trim($nom['id']);
              $term_wr->field_nom_artikul = trim($nom['art']);
              $term_wr->field_nom_unit = $nom['ei'] ?? '';
              $term_wr->field_nom_type = $nom['vid'];
              $term_wr->field_nom_client = $client->tid;
              $term_wr->field_kccc_company = $company->tid;
              $term_wr->field_status = 1;
              $term_wr->save();

              $new_records[] = $term_wr->getIdentifier();
            }
          } else {
            watchdog('import', 'Импорт номенклатуры не выполнен. Не найден давалец с ID: ' . $nom['client_id'], [], WATCHDOG_ERROR);
            return false;
          }
        }
      }

      // если полное обновление справочника, то отключить записи, которых нет в файле
      if ($array['reload']) {
        db_update('field_data_field_status')
          ->fields(['field_status_value' => 0])
          ->condition('entity_type', 'taxonomy_term')
          ->condition('bundle', 'nomenklatura')
          ->condition('entity_id', $new_records, 'NOT IN')
          ->execute();
      }

      // drupal_set_message('Номенклатура импортирована.');
      watchdog('import', 'Номенклатура импортирована.', [], WATCHDOG_INFO);
      return true;
    }
  }

  watchdog('import', 'Импорт номенклатуры не выполнен.', [], WATCHDOG_ERROR);
  return false;
}
